balancer/balancer-v2-monorepo

- contracts/pools/oracle/PoolPriceOracle.sol
- contracts/pools/oracle/Samples.sol
- contracts/pools/weighted/WeightedPool2Tokens.sol
- contracts/pools/weighted/WeightedPool2TokensMiscData.sol
- contracts/test/PoolPriceOracleMock.sol
- contracts/test/WeightedPool2TokensMock.sol
- hardhat.config.ts
- test/helpers/models/pools/weighted/WeightedPool.ts
- test/helpers/models/pools/weighted/WeightedPoolDeployer.ts
- test/pools/PoolPriceOracle.test.ts
- test/pools/weighted/WeightedPool.test.ts
It reduces the bytecode of the weighted pool factory for 2 tokens from `24.726` to `23.942`
It also reduces the gas costs of swaps, e.g. for one pool it's being reduced from `133.1k` and `110.2k` to `132.5k` and `110.0k`, for buffer updates and re-use respectively
> Weighted: Reduce bytecode size

- package.json
- pkg/asset-manager-utils/package.json
- pkg/deployments/package.json
- pkg/pool-stable/package.json
- pkg/pool-utils/package.json
- pkg/pool-weighted/package.json
- pkg/solidity-utils/package.json
- pkg/standalone-utils/package.json
- pkg/vault/package.json
It seems to make more sense to keep a single list at the top instead of copy-pasting the same list accross all packages.
> Add contributors to monorepo package.json

- .github/workflows/ci.yml
- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IDistributor.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/contracts/interfaces/IRewardsContract.sol
- pkg/distributors/hardhat.config.ts
- pkg/distributors/lib/merkleTree.ts
- pkg/distributors/package.json
- pkg/distributors/test/MerkleRedeem.test.ts
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/tsconfig.json
- pkg/solidity-utils/contracts/openzeppelin/MerkleProof.sol
- pkg/solidity-utils/contracts/openzeppelin/Ownable.sol
- pvt/helpers/src/models/misc/signatures.ts
- pvt/helpers/src/test/tokenBalance.ts
- yarn.lock
This adds two implementations of a `Distributor` - a contract that distributes tokens such as rewardTokens from liquidity mining earned by an asset manager, or BAL.
**MultiRewards**
Allows users to claim rewards proportional to staked bpt
A user may either
- `getRewards` claim these tokens to an EOA
- `getRewardsAsInternalBalance` claim these tokens to internal balance, for easy reinvestment/swaps
Credit to @TomAFrench who started this work on  `MultiRewards` on the asset-managers repo
**MerkleRedeem**
Allows users to claim rewards per the entries in a merkle tree.  It's based on: https://github.com/balancer-labs/erc20-redeemable/tree/master/merkle/contracts.  An alternative approach for rewards computed off chain would be a `permit` type scheme to facillitate custom distributions …
> Added Distributor package for distributing rewards

- pkg/asset-manager-utils/contracts/SinglePoolAaveATokenAssetManager.sol
- pkg/asset-manager-utils/test/SinglePoolAaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
This allows you to stake bpt from multiple pools to earn multiple reward tokens so we can have a singleton staking contract
TODO
- Batch ERC20/vault transfers for lower gas use (as is this does multiple erc20 transfers if you were to claim BAL from multiple pools)
- Rename to avoid confusion with Curve's `MultiRewards` contract.  Accepting suggestions better than `MultiMultiRewards`
First step of https://github.com/balancer-labs/balancer-v2-monorepo/issues/602
> Multipool support for multirewards

- pkg/asset-manager-utils/contracts/AssetManager.sol
- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/SinglePoolAssetManager.sol
- pkg/asset-manager-utils/contracts/test/TestAssetManager.sol
- pkg/asset-manager-utils/test/AssetManager.test.ts
- pkg/asset-manager-utils/test/SinglePoolAaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/SinglePoolAssetManager.test.ts
There's very few circumstances where we would want to use `totalAUM` over `readAUM()` as it can lag behind the true AUM and so is unsuitable in most cases.
I've removed the final few places where we use this variable along with `realiseGains`.
> Remove tracking of AUM within asset managers

- pkg/pool-weighted/README.md
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/pool-weighted/contracts/smart/LiquidityBootstrappingPool.sol
- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
- pkg/pool-weighted/test/WeightedPool.test.ts
- pkg/pool-weighted/test/WeightedPool2Tokens.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
In talking through how to make mutable weight pools efficient, we noted that the max token index was only used for calculating fees on joins/exits, and those functions also needed all the token weights. So combining the max weight token index and normalizedWeights getters could be more efficient. The weights can be used on their own (e.g., in the invariant calculations) sometimes, but the max index is only needed for fees.
> Combine getNormalizedWeights and getMaxWeightTokenIndex

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
A few (hopefully) uncontroversial documentation updates suggested by Certora https://balancerlabs.slack.com/archives/C01HPPLFD25/p1623075861021100
They also provided some updates to documentation on AAVE interfaces (pkg/asset-manager-utils/contracts/aave/*).  I'm reluctant to modify the documentation for code from another project that has otherwise been purposefully left untouched (changes are just typos).  Do others agree?
> a few documentation pointers from certora

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
Previously we were just performing a withdrawal from the Vault to retrieve fees to be paid out to the keeper. The pool then thinks that it still has those funds in its managed balance.
We now update the managed balance to account for these fees being lost.
> Fix updating pool balances to account for fees

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
Adds an upper critical level to ensure that AM is rebalanced when overinvested without having to wait for an arb opportunity.
Tests have been changed only as much to get them to pass again. I have another PR which adds full tests for this and improves handling of rebalancing tests
> Add an upper critical level for rebalancing

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
- pkg/asset-manager-utils/test/helpers/rebalance.ts
This PR essentially just does some standardisation of calculating rebalance amounts + fees which makes it easier to refactor into a `itRebalancesCorrectly` set of tests in future.
The only change that would survive #632 would be exposing a public view function to return `_getPoolBalances`.
> Offchain fees calculation

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
Previously we would deposit funds back into the vault and then update the pool's managed balance with the new AUM after the withdrawal. This can result in an issue where if the AM gets a large amount of gains such that it's depositing more than the current managed balance as recorded on the Vault then it can result in an underflow.
I've swapped these two operations so that we would update that it's aware of the new higher managed balance before performing the deposit.
> prevent possible underflow in capitalOut

- pkg/asset-manager-utils/contracts/test/TestAssetManager.sol
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
Use of `capitalIn` has been removed from the setup for tests in `RewardsAssetManager`. Instead, tokens are minted directly to the AM to increase its AUM.
`AaveATokenAssetManager` tests have not been updated to match.
> Remove use of capitalIn from test setup

- pkg/pool-stable/contracts/StablePool.sol
By having the initial value in an event, amplification parameter values can be computed by just looking at events.
> Stable: Emit AmpUpdateStopped in construction

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
This PR adds an initial implementation of "soft" rebalances to prevent the rebalance relayer using extra gas when not necessary.
The critical levels which were used for fees are now used to determine whether a "soft" rebalance should occur or not.
> Soft rebalance

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
- pkg/asset-manager-utils/test/helpers/rebalance.ts
- pkg/pool-utils/contracts/BasePool.sol
This takes `PoolConfig` out of `IAssetManager` (as it is highly specialized to each AM), and renames it in `RewardsAM` as I found `PoolConfig` too generic of a term (and also confusing).
I also removed the associated tests in AaveAssetManager, as there's no point in having those duplicated.
> Rename AM PoolConfig

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/contracts/test/MockRewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
This renames `readAUM()` to `getAUM()`, for consistency with all other getters (`getPoolID()`, `getVault()`, etc.).
It also removes `balanceOf` by adding the `poolId` parameter to `getAUM()`. This IMO also makes the code more understandable: it was quite weird that we were using `readAUM()` directly, and it hinged on the fact that the AM only controls one pool.
> Refactor AM's readAUM()

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
External functions cannot be called using `super` if we want to extend it, using `public` makes it possible. Required for #603
> Pools: Mark external virtual functions as public

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
This, uh, deletes quite a bit of code.
It basically makes `capitalIn` and `capitalOut` internal, as they don't make much sense with the existence of `rebalance`. It also deletes their tests, since they were essentially duplicates of `rebalance`'s tests, and removes their usage in test setup.
Additionally, I removed both capital and rebalance tests from the AaveAssetManager tests. While duplicates of the basic AM tests, these had _some_ usefulness, but I think it makes more sense to write more focused ones in a PR after this one than to make these improvements now, since this change is quite unrelated.
> Make capitalin/out internal

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
We currently have no way to forcibly withdraw funds from the pool if it has been invested. A malicious pool owner can then invest 100% of the pool's funds and lock all LP funds.
A simple mitigation for the time being is to ensure that the owner can never invest more than 90% of the pool's assets.
> Prevent setting the target investment percentage above 90%

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/contracts/aave/IAaveIncentivesController.sol
- pkg/asset-manager-utils/contracts/test/aave/MockAaveRewards.sol
- pkg/asset-manager-utils/contracts/test/aave/MockLendingPool.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
To simplify the factory logic for the Aave weighted pools factory, we now pull addresses where possible from the Aave contracts.
> Pull aToken + reward asset addresses from Aave contracts

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/vault/contracts/interfaces/IBasePool.sol
- pkg/vault/contracts/test/MockPool.sol
LP can now claim rewards from multiple rewarders for pools where they have staked bpt.
For instance, a pool with multiple tokens lent out to aave would earn stkAAVE from multiple asset managers (1 per token).
Whenever an LP stakes or unstakes, the rewards they have earned thus far are calculated, to account for the rewards they earned with their historical bpt staked.  Since this has to happen on the full set of rewards for a pool (the set of {reward token, rewarder} combinations), we need to limit (whitelist) who can issue rewards, to avoid griefing attacks (from unbounded iteration).
This has no hard-coded upper limit on `O(rewardTokens*rewarders)`, running out of gas could prevent you from receiving any rewards for a pool (and only that pool)
**Rewarders*
- Any address the pool adds to …
> Multiple rewarders per rewards token

- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/test/MockBasePool.sol
- pkg/pool-utils/contracts/test/MockRelayedBasePool.sol
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
While the base scaling factors (decimals) are cheap to compute, the MetaStablePool will perform external calls to retrieve them, making this very costly. This PR keeps those in memory and passes them around as needed. 
Benchmark analysis doesn't seem to show any difference in gas costs of joins nor exits.
Part of https://github.com/balancer-labs/balancer-v2-monorepo/issues/655
> Compute scaling factors only once

- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/test/StablePool.test.ts
- pkg/pool-utils/contracts/test/MockVault.sol
- pvt/helpers/src/models/pools/stable/StablePool.ts
- pvt/helpers/src/models/pools/stable/types.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/vault/Vault.ts
- pvt/helpers/src/models/vault/types.ts
This PR fix an issue with getRate function in Stable pool. The issue was that it did not upscale the balances before calculating the invariant. 
It also adds some tests and refactor the swap model for stable pool to be similar to weighted pool. 
Closes #653
> Fix getRate scaling for Stable Pool

- pkg/deployments/hardhat.config.ts
- pkg/deployments/package.json
- pkg/deployments/src/contracts.ts
- pkg/deployments/src/task.ts
- pkg/deployments/src/types.ts
- pkg/deployments/src/verifier.ts
- pkg/deployments/tasks/20210624-stable-pool/index.ts
- pkg/deployments/tasks/20210624-stable-pool/test/deploy.test.ts
- yarn.lock
Since we don't follow the expected layout for the `artifacts` directory in the `deployments` subrepo, the Hardhat's verifier plugin fails if try to use it as is. But, since we do have the required files to perform verifications,  we could point out hardhat where to fetch them from. Unfortunately, this is not possible with the current plugin interface. We have already reached out the Hardhat team to see if they can expose a few parameters to allow us parameterize these paths. In the meantime, I just grabbed a few lines of code form the hardhat plugin to build our own verifier.
The changing part here is that we should now use always `build-info` files instead of the `artifacts` ones.
> Deployments: Implement contracts verifier

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/contracts/test/MockAssetManagedPool.sol
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
- pkg/vault/contracts/test/MockPool.sol
Asset managers now only listen to the pool for setting their config.
The majority of this change is from swapping out the mocked pool implementations with a normal weighted pool and updating the test suite setup. Due to the order in which things need to be deployed I've updated the `WeightedPool` model to allow the vault address to be injected rather than deploying its own vault..
> Turn on access control on asset manage config

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/pool-utils/contracts/RelayedBasePool.sol
- pkg/solidity-utils/contracts/helpers/BaseSplitCodeFactory.sol
Addressed:
- Optimization - excess calculations
- Unnecessary checked arithmetics
- Missing function from interface
- Unused return variable names
- Documentation errors, grammatical mistakes, and typos
Not addressed in this PR:
- Unsafe casting to int256
- Edge case reverts due to unsafe addition
- Overflow
- Wrong documentation
- Incomplete documentation
> Certora fixes related to asset managers

- pkg/deployments/.gitignore
- pkg/deployments/hardhat.config.ts
- pkg/deployments/package.json
- pkg/deployments/src/contracts.ts
- pkg/deployments/src/signers.ts
- pkg/deployments/src/task.ts
- pkg/deployments/src/test.ts
- pkg/deployments/src/types.ts
- pkg/deployments/tasks/20210418-vault/index.ts
- pkg/deployments/tasks/20210624-stable-pool/index.ts
- pkg/deployments/tasks/20210624-stable-pool/test/task.deploy.ts
- pkg/deployments/tasks/20210624-stable-pool/test/task.fork.ts
- pkg/deployments/tasks/20210624-stable-pool/test/task.test.ts
This PR introduces two new types of tests specially useful for deployments.
1. `yarn test:deploy` will run deployment tests whose intention is to assert statements after a deploy was executed
2. `yarn test:fork` will run a simulation on a forked network to assert different statements before the deploy
> Deployments: Set up view and fork tests

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/contracts/test/MockRewardsAssetManager.sol
This is just a minor change that moves in the direction of having `getX()` type getters, like the rest of our contracts have. There are more improvements to be made related to these parts of the code (such as caching the value of `_poolId` to avoid repeated storage reads) - this PR just focuses on naming.
> Asset Manager consistent getters

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
This is now redundant with isWhitelistedRewarder and no longer needed on the asset manager side
> Multirewards - remove isReadyToDistribute

- pkg/distributors/contracts/MultiRewards.sol
Much in the same way that we can't figure out excess funds in the vault because we aren't tracking global quantities, it is better to just remove the capability to recover airdropped funds in this case
> Multirewards - remove function to recover airdropped funds

- pkg/deployments/tasks/20210418-weighted-pool/index.ts
- pkg/deployments/tasks/20210418-weighted-pool/output/polygon.json
This PR adds a task definition which I used to verify the Polygon deployments of the weighted pool factories - also included are the deployed addresses on this network.
> Add weighted pool factory task

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
Uses a mapping rather than an `EnumerableSet` to more efficiently manage list of rewarders allowed to distribute in the staking contract
Renames whitelist -> allowlist re: @FernandoMartinelli 's point about outdated language https://balancerlabs.slack.com/archives/C0146NRBJEP/p1624636747191400
> MultiRewards distributor: rewarder allowlist

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/Reinvestor.sol
- pkg/distributors/contracts/test/MockRewardCallback.sol
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
- pkg/distributors/test/Reinvestor.test.ts
- pkg/solidity-utils/contracts/openzeppelin/EnumerableSet.sol
This implements #659 - allowing an LP to claim rewards to a callback contract
As an example of such a callback contract, `Reinvestor` reinvests rewards tokens in a specified `WeightedPool`
For example, a LP may want to claim all their BAL reward into a BAL-ETH pool
> MultiRewards: Allow LPs to claim rewards to a contract with a callback function

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/RebalancingRelayer.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
Now LPs can force a divestment due to #706, we no longer need to hardcode an upper limit to the investment percentage.
> Remove upper limit on AM investment level

- pkg/asset-manager-utils/contracts/RebalancingRelayer.sol
- pkg/asset-manager-utils/test/RebalancingRelayer.test.ts
- pkg/pool-utils/contracts/test/MockRelayedBasePool.sol
We now call `updateBalanceOfPool` on all asset managers prior to joins/exits.
Fixes #695
> feat: update pool balance prior to join/exit

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
Fix: Explicitly check reward exists in `notifyRewardAmount` before starting reward period (previously this function would have `reverted` if called before `addReward` because of division by zero (with an uninitialized reward duration).
> MultiRewards Distributor: check reward exists in `notifyRewardAmount`

- .github/workflows/ci.yml
It looks like we're running the tests for `solidity-utils` in the `standalone-utils` task rather than the `standalone-utils` tests.
> ci: run correct test suite for standalone-utils

- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/test/MerkleRedeem.test.ts
Removes `useInternalBalance` param from `claimWeek` and `claimWeeks` to unify function interface between v1 and v2 version of this contract.  This way we can use the same frontend as we use for [claim.balancer.fi](claim.balancer.fi) for this contract.
[v1 contract](https://github.com/balancer-labs/erc20-redeemable/blob/master/merkle/contracts/MerkleRedeem.sol)
> Merkle Distributor - backwards compatibility

- pkg/pool-stable/contracts/meta/MetaStablePool.sol
Requested by @johngrantuk so that SOR can use subgraph to get the current rates, instead of having to read on-chain state.
Not a fan of how the code turned out, dealing with immutable state variables is very annoying, and I tried to reduce the bytecode size impact this change would have at the same time.
I left the event arguments un-indexed as the other events were not indexed either - I think we should review this.
> Meta: Add update cache event

- pkg/pool-stable/contracts/meta/MetaStablePool.sol
- pkg/pool-stable/contracts/test/meta/MockMetaStablePool.sol
- pkg/pool-stable/test/meta/MetaStablePool.test.ts
- pkg/pool-utils/contracts/oracle/PoolPriceOracle.sol
- pkg/pool-utils/contracts/oracle/QueryProcessor.sol
- pkg/pool-utils/contracts/test/oracle/MockPoolPriceOracle.sol
- pkg/pool-utils/test/oracle/PoolPriceOracle.test.ts
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/pool-weighted/contracts/test/MockWeightedPool2Tokens.sol
- pkg/pool-weighted/test/WeightedPool2Tokens.test.ts
- pvt/benchmarks/misc.ts
- pvt/helpers/src/contract.ts
- pvt/helpers/src/models/pools/stable/StablePoolDeployer.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
This reduces the bytecode size of MetaStablePools enough that they can be deployed. With 200 runs, they end up at 23.919kB.
The way bytecode is reduced is by removing all oracle query functionality outside of the pool contract itself, and into a linked library. This adds a slight overhead of ~3k gas (2600 from the `delegatecall`), but gets rid of the binary search code and exponentiation (from `fromLowResLog`).
Ideally, we'd be able to deploy the library at construction time in either the Pool or the Factory. Unfortunately, Solidity does not allow for this (though I'll create a language proposal soon with this idea). Some available options are:
1) use linked libraries, which requires external (i.e. outside of Solidity itself) linking (bytecode modification)
2) use delegatecall directly, …
> Oracle: Move query methods to linked library

- pvt/benchmarks/deployment.ts
Current benchmark to measure contracts bytecode size, is somewhat misleading. It tells the size in kB but in general smart contract size is read in bytes.
> Chore: Fix bytecode size benchmark

- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/contracts/meta/MetaStablePool.sol
This PR simply defines a few getters to avoid accessing immutable variables directly. It shouldn't change any further logic.
> Meta: Reduce bytecode size below limit

- pkg/balancer-js/package.json
- pkg/balancer-js/src/utils/assetHelpers.ts
- pkg/balancer-js/src/utils/index.ts
- pkg/balancer-js/test/tokens.test.ts
- pkg/distributors/test/Reinvestor.test.ts
- yarn.lock
Sorting tokens to deploy a new pool or add/remove liquidity has quite a few gotchas associated with it current. Integrators need to:
1. Sort tokens from in order of ascending address
2. Add a special case to sort the zero address as if it were the WETH address for their particular network.
3. Apply the same sorting to asset manager addresses / token weights to maintain the relative ordering.
These rules are somewhat non-obvious if you haven't dug through the contract code so `AssetHelpers` is a standard implementation which should allow integrators hide these complications from users.
Example usage:
```typescript
weightedPoolFactory.create(
name,
symbol,
...new AssetHelpers(WETH_ADDRESS).sortTokens(tokens, weights, assetManagers),
swapFeePercentage,
owner,
)
```
> Add AssetHelpers class to assist with sorting token addresses

- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/PoolTokenManipulator.sol
- pkg/distributors/contracts/Reinvestor.sol
I've made a couple of minor changes to #761 so that we only make addresses payable once we're feeding them into a `userBalanceOp` which improves readability imo. I've also removed some shadowing of a function name in `PoolTokenManipulator`.
If you're happy with these changes then we can merge into #761 and immediately merge that.
> Reward callbacks update

- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/PoolTokenManipulator.sol
- pkg/distributors/contracts/Reinvestor.sol
- pkg/distributors/contracts/interfaces/IRewardsCallback.sol
- pkg/distributors/test/MerkleRedeem.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/Reinvestor.test.ts
use an `IRewardsCallback` interface for rewards callbacks to enforce function call and prevent callback abuse
This fixes a significant bug in which a callback could be used to call contract functions on the vault or pools that manage `Distributor` balances
This has a subset of the changes here: https://github.com/balancer-labs/balancer-v2-monorepo/pull/719/commits/189f884faee08e79ced3390afa758e04496e41fe + the `poolTokenManipulator` refactor that was part of that PR
> Distributors:  IRewardsCallback

- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/MultiRewardsAuthorization.sol
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
This delegates control of the `MultiRewards` contract to the `Vault`'s authorizer
Namely, this gives it the power to allowlist rewarders.  Pool controllers and asset managers are allowed to allowlist themselves for their own pools
I opted to move all authentication functions to the `MultiRewardsAuthorization` contract for a cleaner separation of concerns
_The end result of using the authorizer here is a little confusing because_
_- the allowlist requires {pool, rewarder} specific control which the authorizer cannot provide with it's actionId based approach (afaik)_
_- pool controller and asset managers need implicit access to add allowlisted rewarders, and the mix of implicit access and the authorizers explicit access is confusing_
> MultiRewards: use authorizer pattern for access control

- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
As suggested on the https://github.com/balancer-labs/balancer-v2-monorepo/pull/719 review
This syntax is easier to read
> de-overload stake function to stakeFor a recipient

- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/Exiter.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/Exiter.test.ts
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
This
a) simplifies accounting for the reward rollup by removing unnecessary rewarder parameter in mapping
b) Implements an `Exiter` callback contract that exits a pool with all the bpt sent to it and passes tokens on to the LP
Nearly the same as this, except the rewards are sent to the LP directly from the staking contract (open for debate)
This opens the door for a lot of interesting use cases, like being able to seamlessly transfer assets from one pool to another without relayers, or to exit a pool and liquidate to WETH or something (provided a list of swaps).
I propose we focus more on the `MultiRewards#exitWithCallback` function for the purpose of this PR and discuss what exactly we want out of the callback contract as we think through UX - we may end up with a lot of these generic …
> Distributor: MultiRewards Exiter

- pkg/distributors/contracts/Exiter.sol
- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/Reinvestor.sol
- pkg/distributors/contracts/interfaces/IDistributorCallback.sol
- pkg/distributors/contracts/test/MockRewardCallback.sol
This makes it even less likely that unintended callback functions will be callable from the distributors by renaming the callback `distributorCallback(...)`
`IRewardsCallback` -> `IDistributorCallback`, and `callback` -> `distributorCallback`
> Distributors: renamed callback

- pkg/deployments/CHANGELOG.md
- pkg/deployments/README.md
- pkg/deployments/package.json
An issue the new structure has is that importing a contract now requires knowing not only the task id, contract name and network, but also the internal id used in the `output/<network>.json` file, which so far has been roughly arbitrary (e.g. `factory` for the multiple factories, `vault` for the vault, etc.). We might want to use the contract name instead of these, as I don't expect a task will include multiple deployments of the same contract.
> Deployments: Polish publish task

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
re: https://balancerlabs.slack.com/archives/C01HPPLFD25/p1628551516002400?thread_ts=1628436115.001800&cid=C01HPPLFD25
Prevents gas limit issues when claiming rewards for a pool with many reward tokens
64 is a stand-in for a more scientifically chosen number
> Distributors: MultiRewards maximum number of reward tokens per pool

- pkg/distributors/contracts/PoolTokenCache.sol
- pkg/distributors/contracts/Reinvestor.sol
- pkg/distributors/test/PoolTokenCache.test.ts
- pkg/distributors/test/Reinvestor.test.ts
- pkg/solidity-utils/contracts/openzeppelin/EnumerableMap.sol
- pkg/solidity-utils/contracts/openzeppelin/EnumerableSet.sol
This follows up https://github.com/balancer-labs/balancer-v2-monorepo/pull/769 with a few improvements and comments, mostly related to cache purging. I then realized that a Pool changing its token set is a very uncommon event that doesn't make sense to optimize for, but oh well.
I also extracted the few cache tests we had into its own file, adding a few basic ones.
> Cache purge

- pkg/balancer-js/src/pool-weighted/encoder.ts
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/pool-weighted/contracts/WeightedPool2TokensFactory.sol
- pkg/pool-weighted/contracts/WeightedPoolUserDataHelpers.sol
- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
- pvt/benchmarks/joinExit.ts
- pvt/benchmarks/multihop.ts
- pvt/benchmarks/singlePair.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/pools/weighted/types.ts
Also added to WeightedPool2Tokens, because it tested that it had WeightedPoolBehavior. Because I breathed on it, also had to use the SplitCode factory. Maybe ok, since anyone doing anything with it will immediately run out of gas? So it will save integrators troubleshooting if we just bite the bullet and ship it that way.
Or we'd have to move the new join out of the behavior suite.
> Add new proportional JoinKind

- pkg/deployments/src/types.ts
- pkg/deployments/tasks/20210418-authorizer/index.ts
- pkg/deployments/tasks/20210418-authorizer/input.ts
- pkg/deployments/tasks/20210418-vault/input.ts
The multisig which acts as the Authorizer admin lives here: https://explorer.arbitrum.io/address/0x6207ed574152496c9B072C24FD87cE9cd9E17320
And the WETH address (`0x82aF49447D8a07e3bd95BD0d56f35241523fBab1`) is taken from the official Arbitrum mainnet token list: https://bridge.arbitrum.io/token-list-42161.json
Please let me know if I missed anything.
> Add deployment config for Arbitrum mainnet

- pkg/balancer-js/src/utils/errors.ts
- pkg/pool-weighted/contracts/smart/InvestmentPool.sol
- pkg/pool-weighted/test/InvestmentPool.test.ts
- pkg/solidity-utils/contracts/helpers/BalancerErrors.sol
This was a thing we talked about that dropped. LBPs (V1 and V2) let you effectively do immediate weight changes, but that's less dangerous because there are no LPs (well, there could be on V1 if they configure it that way).
That would be dangerous on a big public pool, though. This is a simple hard-coded limit. Could pass it in if we wanted to make it configurable, but we'd either still need a hard-coded minimum, or rely on managers to not make it 0, or users to notice that it's 0 and the pool requires more trust.
Keeping it dirt simple for now. It at least prevents instantaneous weight changes.
> Investment Pools: minimum weight change duration

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
Owner of a linear pool ca already change the target values, so should also be able to change the cache duration of the wrapped token's rate.
> Linear: Allow owner to set the cache duration of wrapped token's rate

- pkg/pool-linear/contracts/LinearMath.sol
- pkg/pool-linear/test/math.ts
This PR fixes an error in toNominal function.
It also optimize calcs for `calcBptOutPerMainIn` and `calcBptInPerMainOut`: 
```
const newBptSupply = bptSupply.mul(decimal(1).sub(deltaNominalMain.div(invariant)));
const bptIn = bptSupply.sub(newBptSupply);
```
equals
`const bptIn = bptSupply.mul(deltaNominalMain).div(invariant);`
> Linear pool math optimization and fixes

- pkg/pool-stable/contracts/StableMath.sol
- pkg/pool-stable/test/StableMath.test.ts
- pkg/solidity-utils/contracts/openzeppelin/Address.sol
Noticed this when updating docs - there is no test for either of the "didn't converge" messages (probably very hard to trigger).
> Correct error message

- pkg/typechain/package.json
`dist/index.js` rather than `dist/index.ts`
> fix entrypoint to @balancer-labs/typechain package

- pkg/balancer-js/src/utils/assetHelpers.ts
- pkg/balancer-js/test/tokens.test.ts
All instances of WETH were being converted to ETH, rather than just when the user provided ETH as one of the inputs.
> Fix conversion of WETH to ETH in sortTokens

- pkg/deployments/README.md
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/abi/MerkleRedeem.json
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/index.ts
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/input.ts
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/output/arbitrum.json
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/readme.md
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/test/task.deploy.ts
- pkg/deployments/tasks/20210913-bal-arbitrum-merkle/test/task.fork.ts
We have opted to use a merkle redeem contract for liquidity mining rewards on arbitrum.  This deploys the merkle redeem contract for BAL rewards and will be run as
```
npx hardhat deploy --id 20210913-bal-arbitrum-merkle --key <KEY> --network arbitrum
```
> deploying BAL distribution contract on Arbitrum

- pkg/distributors/contracts/MultiRewards.sol
Based on the comments in https://github.com/balancer-labs/balancer-v2-monorepo/pull/805.
This saves storage pointers to avoid recomputing them (which involves hash and memory-intensive operations), saving gas (though I haven't measured the effect).
There's multiple places where this could be applied: I only performed the change in the most critical functions (those that are called during `stake` or `unstake`) to try to keep the diff small, but am not against doing it accross the entire contract.
> Save storage pointers to save gas

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPoolFactory.test.ts
Exposing externally token addresses and indexes info to be used by SOR or graph queries.
> Linear pool - add getters

- pkg/pool-stable/contracts/StableMath.sol
This removes a fixed point division by FixedPoint.ONE, which by definition achieves nothing other than wasting gas.
It is likely a leftover of a previous implementation where we manually changed the number of decimals.
> [OZ-L07] Remove stable math redundant div

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
Fixes behavior of stake with permit to allow a user to stake tokens on another users behalf
As noted here https://github.com/balancer-labs/balancer-v2-monorepo/pull/801#discussion_r701839593 `msg.sender` must stake the user with the LP as the recipient to avoid mempool attacks
> Distributors: Stake with permit (OZ-M01)

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
Prevents a rewarder from setting a reward duration for a reward before they add it, and thus lock themselves out of adding the reward
> Distributors: added check to setRewardsDuration that a reward exists OZ-H01

- pkg/pool-linear/contracts/LinearMath.sol
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/contracts/test/MockLinearMath.sol
- pkg/pool-linear/test/LinearMath.test.ts
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-linear/test/math.ts
This PR enables swaps between wrapped token and bpt. 
It adds the math  needed to the math contract and typescript library.
It adds the functionality to swap them to the linear pool contract. 
It adds tests for math and for swapsl.
> Linear: Add swap for BPT-wrapped

- pkg/deployments/README.md
- pkg/deployments/tasks/20210920-vita-merkle/abi/MerkleRedeem.json
- pkg/deployments/tasks/20210920-vita-merkle/index.ts
- pkg/deployments/tasks/20210920-vita-merkle/input.ts
- pkg/deployments/tasks/20210920-vita-merkle/readme.md
- pkg/deployments/tasks/20210920-vita-merkle/test/task.deploy.ts
- pkg/deployments/tasks/20210920-vita-merkle/test/task.fork.ts
The VITA side of Joint LM rewards for https://www.coingecko.com/en/coins/vitadao which they will be administering every week.
This is a direct port of the the LDO LM rewards contract, with updated build-info from the more recent Arbitrum BAL merkleredeem contract
Let me know if this looks right and I'll deploy
> Deployments: added deployment task for vita liquidity mining

- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/test/StablePool.test.ts
From the OZ preliminary report:
>Owing to the fact that one version of _setAmplificationData calls the other version of _setAmplificationData, both events will be emitted in a single transaction when the constructor of StablePool calls _setAmplificationData. Additionally, if startAmplificationParameterUpdate is called followed by a call to stopAmplificationParameterUpdate, two instances of AmpUpdateStarted will be emitted followed by one instance of AmpUpdateStopped.
This makes it so stopping no longer emits a 'start' event.
> [OZ-M02] Remove start amp events on amp stop

- pkg/distributors/contracts/MultiRewards.sol
As openzeppelin points out:
> The getRewardForDuration function of the MultiRewards contract returns the product of the
rewardRate and the rewardsDuration for a given pool rewarder rewardsToken combo. The
rewardsDuration for a reward is initially set at addReward and is used to calculate the rewardRate.
After the periodFinish, the rewarder can update the rewardDuration by way of the
setRewardsDuration function.
> 
> The problem is that the setRewardsDuration function does not also update the rewardRate. This way,
the product given by getRewardForDuration will be between unrelated factors, and will thus produce
an incorrect value.
Suggest we remove this function completely to avoid any miscalculations and instead read relevant values from the `public rewardData` mapping
> Distributors: remove problematic getRewardForDuration function [OZ-M03]

- pkg/pool-linear/contracts/LinearMath.sol
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/contracts/test/MockLinearMath.sol
- pkg/pool-linear/test/LinearMath.test.ts
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-linear/test/math.ts
Fix wrong use of rate in linear math. In depth tests for this will be added in future PRs. 
This PR also simplifies `_calcWrappedOutPerMainIn` and `_calcWrappedInPerMainOut` math functions
> Linear pool fix rate math

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable/contracts/StableMath.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/contracts/test/MockStableMath.sol
This leads to gas savings when protocol fees are enabled.
> Avoid double invariant computation of invariant on Phantom Pools

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
Following on from #895, I've named `seedAllocations` -> `createDistribution` to be more in keeping with the rest of the terminology.
I've also removed the underscore from `_merkleRoot`
> Merkle orchard renaming

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
- pvt/benchmarks/merkleClaim.ts
Closes #895 and #890
This PR recognizes that the predominant use case of merkle redeem distribution is for periodic distributions of the same token
It therefore optimizes for gas by storing a users claim status in a way that minimizes storage writes
> Orchard per user storage

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
There's no new functionality in this PR, just changing how we lay out the contract.
- Getter functions have all been moved to the top of the file to match how we lay out the pool contracts
- The order of args in `claimDistributionsWithCallback` have been changed to match that in the other two `claimDistributions` functions.
- The order of args in other functions such as `_verifyClaim` have been updated so that we always provide them in the order `channelId (token+distributor) > distribution > recipient address` as we had some inconsistencies and this seems the most logical way to set it out.
- `liquidityProvider` has been replaced with `claimer` as there's no requirement to provide liquidity to be included in a distribution.
> Reorganise some MerkleOrchard functions

- pkg/balancer-js/package.json
- pkg/balancer-js/rollup.config.ts
I've made ethers a peer dependency of balancer-js to prevent us from potentially having multiple versions of ethers when we use balancer-js.
`@balancer-labs/typechain` has also been made external rather than being bundled.
> Fixup balancer-js dependencies

- pkg/standalone-utils/contracts/relayer/BaseRelayerLibrary.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
I've added this for the situation in which we're performing a migration of the canonical relayer. In this case we'd ideally revoke approval for the previous relayer to minimise the attack surface so I've added an additional `relayer` parameter to `setRelayerApproval` to allow us to change the approval of relayers on the user's behalf.
Giving a relayer the ability to approval other relayers is very powerful so I've restricted this to only allow revocation of the approval of other addresses.
> Allow relayers to revoke approval from other relayers on behalf of user

- pkg/standalone-utils/contracts/interfaces/IBaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/BaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/VaultActions.sol
- pkg/standalone-utils/test/VaultActions.test.ts
- pvt/helpers/src/models/tokens/Token.ts
- pvt/helpers/src/test/expectEvent.ts
This PR adds support for chaining exits from pools. Using chained values as an input to an exit is fine, things looks very similar to joins in this regard.
When we're tracking the result of the exit however it's another story. Due to how `vault.exitPool` doesn't return anything we need to read the user's balance of each token before and after the exit, taking into account that users may be performing an exit in terms of ETH. On top of that, users have the option to exit to their internal balance which means we need a parallel mechanism to handle this case - resulting in the monster below.
Comments, etc. will be cleaned up in a bit.
> Chained exits

- pkg/standalone-utils/contracts/interfaces/IBalancerRelayer.sol
- pkg/standalone-utils/contracts/relayer/BalancerRelayer.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
Just something I noticed was missing when working in https://github.com/balancer-labs/balancer-v2-monorepo/pull/993. See [here](https://github.com/balancer-labs/balancer-v2-monorepo/pull/993/files#diff-a233ed90cf6cc158c25e4b12d3be951cad8ac7c05b11574c9d55c307f1266561R45) how the Vault address had to be retrieved from the library instead of the relayer.
> Add Vault getter to BalancerRelayer

- pkg/balancer-js/package.json
- pkg/balancer-js/rollup.config.ts
Reverts #984, as that's causing trouble due to mismatched versions of ethers. Next time we attempt to improve this, we should make sure that all packages respect the requested peer-dependencies.
> Revert peer dependency changes in balancer js

- pkg/distributors/contracts/Reinvestor.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/contracts/StablePoolUserData.sol
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/pool-weighted/contracts/WeightedPoolUserData.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/standalone-utils/contracts/relayer/VaultActions.sol
This prevents from contracts using the enum importing the entire Pool code, which among other things results in huge code verification (see #993).
> Move userdata enums to libraries

- pkg/pool-linear/contracts/LinearPool.sol
I looked into improving testing for this, but unfortunately the suite is not quite prepared to handle tokens with different numbers of decimals, so I simply produced the change at the contract level.
> Fix LinearPool.setTargets scaling

- pkg/distributors/test/Distributor.test.ts
Fixes tests introduced in #967 to support changes from #980
> fix: update distributor tests to use new Authorizer interface

- pkg/balancer-js/src/utils/errors.ts
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/solidity-utils/contracts/helpers/BalancerErrors.sol
I also ended up reworking the tests to make it clearer what we're testing in each case, since the old tests did not differentiate being below/above only the old or new targets.
> Make LinearPool setTargets stricter

- pkg/pool-linear/contracts/LinearPoolFactory.sol
This is required due to changes such as https://github.com/balancer-labs/balancer-v2-monorepo/pull/1029 which increase the factory bytecode past the limit.
> Linear: use split code factory

- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/distributors/contracts/MultiDistributor.sol
- pkg/distributors/contracts/interfaces/IMultiDistributor.sol
- pkg/distributors/test/MultiDistributor.test.ts
- pkg/distributors/test/MultiDistributorCallbacks.test.ts
- pkg/distributors/test/Reinvestor.test.ts
- pkg/distributors/test/helpers/MultiDistributor.ts
I've added `sender` and `recipient` arguments for `stake`, `unstake` and `claim` functions on the `Multidistributor` which allow redirecting the output to a different address. Tests for `unstake` and `claim` have been updated to use the same pattern used by `stake` for testing this.
I haven't made the same change for `exit` as `exitWithCallback` currently has the tokens being split (staked to msg.sender, rewards to callback). I'm not sure if we want to change behaviour to sending staked BPT to the callback contract (adds complexity and scope for locked tokens if a callback doesn't expect this) or complicating the interface by allowing two types of "recipient". I don't think it would be the end of the world to keep this function simpler (as a relayer which wants to redirect output could …
> MultiDistributor: update staking interface

- pkg/distributors/contracts/MultiDistributor.sol
This PR makes the suggested changes to comments as suggested by Certora and reworded one line which seems to be confusing.
> MultiDistributor: fix typos in comments

- pkg/distributors/contracts/MultiDistributor.sol
(I've actually got some more changes locally but probably best to wait until we have the benchmarks in master before looking at this.)
fixes #1013 
This PR:
- Moves safety checks on `_unaccountedUnclaimedTokens` to external getters (This is safe as we only call it on subscribed distributions)
- Passes the new `globalTokensPerStake` to the `_unaccountedUnclaimedTokens` call to avoid recalculation
- Switches `_updateDistributionRate` to take a storage pointer rather than looking up the distribution again from its id.
> MultiDistributor: gas golfing

- pkg/distributors/contracts/MultiDistributor.sol
- pkg/distributors/test/MultiDistributor.test.ts
We currently don't emit what the duration of a newly created distribution channel is. This PR emits that data
> MultiDistributor: add missing event on distribution channel creation

- pkg/distributors/contracts/MultiDistributor.sol
- pkg/distributors/contracts/interfaces/IMultiDistributor.sol
- pkg/distributors/test/MultiDistributor.test.ts
We currently don't emit which distribution the token is being claimed from in the `TokensClaimed` event. This prevents offchain trackers from reconstructing the currently claimable balances for each user for each distribution.
I've switched this event to emit the distributionId instead as distributionToken can be determined from this or the transfer event which is also emitted.
> MultiDistributor: Emit distributionId in claim event

- pkg/distributors/contracts/MultiDistributor.sol
`_updateGlobalTokensPerStake`  better reflects the purpose of this function in relation to `_updateUserTokensPerStake` than `_updateDistributionRate`
> MultiDistributor: rename _updateDistributionRate to _updateGlobalTokensPerStake

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-linear/test/math.ts
This PR fixes `getRate` in linear pool because invariant was wrongly calculated when getting the rate. 
Tests were also added to verify that it cannot be manipulated.
Two of those tests are skipped because they will run ok once we fix `toNominal` and `fromNominal` in Linear Math.
> Linear: fix get rate

- pkg/distributors/contracts/MultiDistributor.sol
- pvt/benchmarks/multiDistributor.ts
I've created some super simple benchmarking scripts for the remaining MultiDistributor actions and made a few optimisations.
Some micro changes have knocked ~300 gas per subscribed distribution off of most operations. Subscribing and unsubscribing from distributions are now ~2000 gas cheaper as I noticed that we're hitting a cold storage slot whereas we can reuse the SLOAD we use for `distribution.stakingToken`
We still have struct packing optimisations left to look at but that needs #1025 to be in so we can be sure on the bounds of certain fields.
> MultiDistributor: extra gas golfing

- pkg/pool-linear/contracts/LinearMath.sol
This PR replaces FixedPoint for Math lib in places where the first one is not needed.
> Linear: replace lib FixedPoint for Math 

- pkg/distributors/contracts/MultiDistributor.sol
- pkg/distributors/contracts/interfaces/IMultiDistributor.sol
- pkg/distributors/test/MultiDistributor.test.ts
Builds on #1040 
This PR adds support for relayers to fund a distribution owned by another address. This allows seamless use of the `RewardScheduler` without having to have users subscribe to a whole new distribution.
PR to update `RewardScheduler` to make use of this will come separately.
> MultiDistributor: add ability for distribution owners to delegate funding to contracts, etc.

- pkg/pool-linear/test/AaveLinearPool.test.ts
Nothing big, but there wasn't test coverage for the revert when an invalid mainToken is provided to the `AaveLinearPool` constructor.
> Add a test case for AaaveLinearPool - revert when incorrect mainToken provided in constructor

- pkg/solidity-utils/contracts/math/FixedPoint.sol
- pkg/solidity-utils/contracts/test/FixedPointMock.sol
- pkg/solidity-utils/test/FixedPoint.test.ts
This PR reduces gas cost when computing power of 1, 2 or 4 by avoiding fractional exponentiation. 
For **50/50 weighted pool it saves 3.5K of gas on each swap**. 
It also reduces the same amount of gas for half of  80/20 weighted pool swaps. 
And swaps for some other pools depending on their weights.
> FixedPoint: improve pow to save gas

- pkg/pool-weighted/test/WeightedPool2Tokens.test.ts
- pvt/helpers/src/models/tokens/TokenList.ts
- pvt/helpers/src/numbers.ts
Was working on this when the PR got merged out from under me :)
It might not be the most elegant way to do this, but it tests both an 18 and non-18 decimal token, verifying that the join/exit logic is now correct.
> Test the oracle pool with non-18-decimal tokens

- pkg/gauges/contracts/GaugeController.vy
- pkg/gauges/contracts/VotingEscrow.vy
- pkg/gauges/contracts/VotingEscrowDelegation.vy
As we're updating the vyper version used by the contracts we can make use of immutable variables. I've gone through all the addresses are hardcoded or held in storage and set them to be immutable variables. Immutable variables don't get getters by default so I've created explicit getters to replace those automatically generated before.
I've also taken the opportunity to pull addresses from onchain where possible to enforce consistency and remove a redundant variable. 
Closes #1098
> Use immutable variables in vyper contracts

- pkg/gauges/contracts/gauges/LiquidityGaugeV5.vy
Extension of #1103 to cover the liquidity gauge contract
> refactor: use immutables over hardcoded addresses in liquidity gauge

- pkg/gauges/contracts/gauges/LiquidityGaugeV5.vy
This PR replicates the same infinite approvals that we have for BPT on gauge deposit tokens, motivation being to simplify the use of these in combination with relayers.
Also why does Vyper not have public functions?
Fixes #1099
> Add infinite approval for Vault on gauge deposit tokens

- pkg/gauges/contracts/BalancerTokenAdmin.sol
- pkg/gauges/contracts/VotingEscrow.vy
- pkg/gauges/test/BalancerTokenAdmin.test.ts
Merge after #1125.
Now that the [veBAL proposal is out](https://forum.balancer.fi/t/introducing-vebal-tokenomics/2512), we can set various parameters to match its contents. The initial inflation rate and the maximum lock time have been updated.
Fixes #1079
> Set constants for veBAL system

- pkg/gauges/contracts/VotingEscrowDelegationProxy.sol
- pkg/gauges/contracts/interfaces/IVeDelegation.sol
This PR adds a proxy contract which sits between the gauges and a delegation contract so that we can modify where we read the adjusted balances from without migrating the entire gauge or potentially having a split config of different gauges reading from different contracts.
Curve equivalent: https://etherscan.io/address/0x8E0c00ed546602fD9927DF742bbAbF726D5B0d16#code
> feat: add veBoost proxy equivalent in solidity

- pkg/vault/contracts/Authorizer.sol
- pkg/vault/test/Authorizer.test.ts
- pvt/helpers/src/models/authorizer/Authorizer.ts
Fixes #588 
Summing up the approach:
- Whoever has permission to do sth, if there is a delay set for that action, they can schedule an action to do that instead (they can't perform the action themselves).
- Changing the delay of an action implies scheduling an action using current delay for that action
- A specific permission per action is required to change its delay
- When actions are scheduled an optional list of executors can be given, if none, anyone can execute them
- Actions can be executed only once after the delay has passed
- Scheduled actions can be cancelled by the creator only at any time if it wasn't executed yet
> Authorizer: Implement built-in timelocks

- pkg/balancer-js/src/utils/signatures.ts
- pkg/gauges/contracts/BalancerMinter.sol
- pkg/gauges/test/BalancerMinter.test.ts
The implementation is rather straightforward, as we rely on OZ's EIP712 for most of the heavy lifting. The rest of the code is adapted from SignaturesValidator.
The `setMinter` name can be confusing, since the contract we're calling _is_ the minter, but oh well. Given this will be user-facing (as they'll need to sign an EIP712 blob called 'SetMinterApproval'), we may want to consider an alternative name for this.
Fixes https://github.com/balancer-labs/balancer-v2-monorepo/issues/1113
> Add setMinterApprovalWithSignature

- pkg/pool-linear/contracts/erc4626/ERC4626LinearPool.sol
- pkg/pool-linear/test/ERC4626LinearPool.test.ts
There was a misunderstanding about the role of the asset wrapped by ERC4626.  It should be a rebasing yield-bearing asset
So in the USD+ case, ERC4626 wraps the USD+ into StaticUSD+, which is paired with USDC
This means there must be a 1:1 relationship of the paired asset (USDC) and the wrapped asset (USD+)
> Remove erroneous check on erc4626 linear pools

- pkg/vault/contracts/Authorizer.sol
The authorizer was using `canPerform` unnecessarily for internal methods, there were no timelocks supported for the authorizer itself, thus it doesn't make sense to use it. We should use `hasPermission` instead.
> Authorizer: Use `hasPermission` instead of `canPerform` internally

- pkg/liquidity-mining/contracts/GaugeController.vy
There's currently no easy way to check if a particular gauge exists on the GaugeController or not. The currently accessible methods throw up some challenges:
1. Checking the potential gauge's type will revert if the gauge does not exist
2. Checking the weight of a potential gauge and treating a zero weight as non-existance will result in false negatives for gauges with zero weights.
This means that the best solution currently is wrapping a call to `GaugeController.gauge_types(addr)` in a try catch block which is very icky. I've then added a `gauge_exists` function based on `gauge_types` which just returns whether the gauge's type is valid or not.
`gauge_exists` should return false in all situations where `gauge_types` reverts and true otherwise (note that gauge types are always gte 0 …
> Add method to check if a gauge exists on the GaugeController

- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
- pkg/standalone-utils/test/LidoWrapping.test.ts
- pkg/standalone-utils/test/VaultActions.test.ts
- pkg/standalone-utils/test/helpers/chainedReferences.ts
- pkg/standalone-utils/test/helpers/tokenTransfer.ts
- pvt/helpers/src/test/expectEvent.ts
We've got a lot of duplicated code in the relayer tests at the minute which is annoying me a bit and will only get worse once we add relayer libraries for ERC4626, veBAL, etc.
This PR just pulls some of the duplicated code out into helper files and cleans up some code smells so should be pretty straightforward to review.
`expectEvent` has also had a fix applied where it was treating addresses as case sensitive when filtering.
> Refactor relayer tests

- pkg/asset-manager-utils/test/RebalancingRelayer.test.ts
- pkg/pool-utils/test/BasePool.test.ts
- pkg/pool-utils/test/LegacyBasePool.test.ts
- pkg/vault/contracts/Authorizer.sol
- pkg/vault/test/AssetManagement.test.ts
- pkg/vault/test/Authorizer.test.ts
- pkg/vault/test/ExitPool.test.ts
- pkg/vault/test/FlashLoan.test.ts
- pkg/vault/test/InternalBalance.test.ts
- pkg/vault/test/JoinPool.test.ts
- pkg/vault/test/PoolRegistry.test.ts
- pkg/vault/test/SwapValidation.test.ts
- pkg/vault/test/Swaps.test.ts
- pkg/vault/test/VaultAuthorization.test.ts
- pvt/helpers/src/models/authorizer/Authorizer.ts
- pvt/helpers/src/models/authorizer/AuthorizerDeployer.ts
- pvt/helpers/src/models/authorizer/types.ts
- pvt/helpers/src/models/vault/VaultDeployer.ts
Fixes #1083 
Note that we can make the authorizer depend on the Vault since this will be a new version of it, otherwise we would have had circular dependencies. 
I think we miss denoting that `IVault` extends `IAuthentication` in `IVault.sol`. Should we add it? (cc @nventuro)
> Authorizer: Ensure delays correctness

- pkg/liquidity-mining/contracts/gauges/SingleRecipientGauge.sol
- pkg/liquidity-mining/contracts/gauges/SingleRecipientGaugeFactory.sol
- pkg/liquidity-mining/contracts/interfaces/ISingleRecipientLiquidityGauge.sol
This PR aims to improve onchain discover-ability of SingleRecipientGauges. The `SingleRecipientGaugeFactory` now maintains a record of the gauge deployed for a given recipient and prevents duplicated gauges for a single recipient.
This does raise a little bit of complexity for the inbetween period where we're merkle dropping rewards for Polygon and Arbitrum as we'll need separate addresses to claim each network's rewards but I think a small amount of pain there is outweighed by the benefits in future.
This change is also motivated by the fact that we'll need this behaviour on the Polygon/Arbitrum gauge factories to help prevent duplicated gauges being added to the gauge factory.
> Prevent multiple SingleRecipientGauges for the same recipient

- pkg/governance-scripts/contracts/20220322-veBAL-activation/veBALDeploymentCoordinator.sol
We're currently passing in the `GaugeController` address to internal functions within the `veBALDeploymentCoordinator` but there's not really much point in doing so as there's only a single `GaugeController` (so this arg will always be the same) and it's stored in an immutable variable (so no gas savings).
We can then just read from the immutable variable within the internal functions to reduce some visual noise.
> Remove redundant gaugeController argument from _addGaugeType and _setGaugeTypeWeight

- pkg/liquidity-mining/contracts/gauges/LiquidityGaugeV5.vy
- pkg/liquidity-mining/contracts/gauges/StakelessGauge.sol
- pkg/liquidity-mining/contracts/interfaces/ILiquidityGauge.sol
Killing and unkilling gauges are now two separate functions so we can assign different delays to each action.
> Splits set_killed function into killGauge and unkillGauge

- pkg/governance-scripts/contracts/20220322-veBAL-activation/veBALDeploymentCoordinator.sol
- pkg/liquidity-mining/contracts/test/MockGaugeController.sol
- pkg/liquidity-mining/test/GaugeAdder.test.ts
This PR connects the `veBALDeploymentCoordinator` to the gauge factories and `GaugeAdder` contracts.
At construction time we provide two arrays - one of pools for which we want to deploy gauges for (these will be automatically added to the `GaugeController`), one of the 4 recipients to receive the BAL for the gauge types which won't initially have their proper gauge contracts (`SingleRecipientGauges` will be deployed to point at all of these).
> veBALDeploymentCoordinator gauge deployment

- pvt/helpers/src/models/pools/stable/math.ts
calculateApproxInvariant used incorrect javascript `>` operator, which resulted in incorrect converge. Additionally converge must happen when BigNumber integer representation of `inv - prevInv` is <= integer 1
> fix: Decimal math errors in stable-pool math.ts

- pkg/governance-scripts/contracts/20220322-veBAL-activation/veBALDeploymentCoordinator.sol
- pkg/standalone-utils/test/BALTokenHolder.test.ts
This changes the Coordinator so that instead of creating single recipient gauges with the end recipient being immutable, it sets BALTokenHolders as their recipient, which in turn delegate to governance how the funds held there are used. The coordinator sets up permissions so that the current end recipients can withdraw them.
For the LM Committee gauge, this means that the end recipient is now decoupled from the gauges, and can be changed by revoking and granting permissions on the Authorizer, without needing to kill the gauge. 
For the other three temporary gauge types, we could either kill the gauges and replace them with their expected final versions once those are done, or grant those contracts permission to withdraw funds from the holder (making the gauges less temporary).
> Use BALTokenHolder factory in coordinator

- pkg/liquidity-mining/contracts/AuthorizerAdaptor.sol
There's nothing groundbreaking here. I noticed we had already removed mutability of the gauge in the factory, but never got rid of the admin functionality.
edit: updated in light of https://github.com/balancer-labs/balancer-v2-monorepo/pull/1195 to remove the duplicated content
> Misc fixes on LM system

- pkg/liquidity-mining/contracts/GaugeAdder.sol
- pkg/liquidity-mining/contracts/interfaces/IGaugeAdder.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGaugeFactory.sol
- pkg/liquidity-mining/test/GaugeAdder.test.ts
This PR implements a global mapping for BPT addresses to the canonical gauge address. This is required as because we support multiple factories it's possible to have multiple gauges for the same pool eligible to be added to the GaugeController. Without this PR, we'd then have to rely on the entities authorised to call `addEthereumGauge` not to do so for these gauges.
~~Having this mapping is also very useful for building an onchain registry for the veBAL system as we can allow a trustless migration of this data to a standalone registry contract.~~ Actually we could just do it from gauge to address using the GaugeContoller.
Note that this will prevent us from deploying a new gauge implementation for a particular pool unless we migrate the GaugeAdder contract but I think that this is a …
> Prevent duplicate gauges for a pool being added to GaugeController

- pkg/liquidity-mining/contracts/VotingEscrow.vy
This PR implements fixes to the `balanceOf(address, uint256)` and `totalSupply(uint256)` functions in the `VotingEscrow` contract such that they can calculate historical values which fall before the current epoch.
This is a relatively light touch change as we're just performing binary searches to find the correct epoch for the provided timestamp and then passing this into the existing implementation.
> Fix reading historical balances/total supply by timestamp

- pvt/helpers/src/models/pools/weighted/math.ts
This PR updates typescript math for weighted pool to use the proper compare operator when using Decimal or BigNumber.
> Weighted pool: use correct compare operators

- pkg/pool-linear/contracts/erc4626/ERC4626LinearPool.sol
- pkg/pool-linear/contracts/erc4626/ERC4626LinearPoolFactory.sol
- pkg/pool-linear/contracts/test/MockERC4626Token.sol
- pkg/pool-linear/test/ERC4626LinearPool.test.ts
- pkg/solidity-utils/contracts/misc/IERC4626.sol
[EIP-4626](https://eips.ethereum.org/EIPS/eip-4626) has been finalized as of yesterday. This PR updates the `ERC4626LinearPool` in light of new additions to the standard. It builds upon the previous work from #1120.
Notably, after the initial development effort of the linear pool, the EIP-4626 standard added `convertToAssets` and `convertToShares` functions, which should be more reliable than the pool's former rate calculation method of `totalAssets/totalSupply`. These functions provide assets<>shares conversions free of any deposit/withdrawal fees, slippage, or caller-specific logic, which was exactly the spirit of the pool's original rate calculation.
Note that, although some additional pieces of the interface have been renamed, and the `Withdraw` event now has an extra parameter, the …
> Linear Pool: ERC4626 Finalized

- pkg/liquidity-mining/test/FeeDistributor.test.ts
CI seems to be failing due to some drift from the current timestamp within the hardhat network and in TS. We then make sure to pull from hardhat consistently.
> fix: make sure to use EVM time when calculating startTime

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
We currently have a concept of a `tokenStartTime` so that the contract knows from when users should attempt to claim a particular token if they haven't interacted with it before. This means that if we add a new token to be distributed then people don't have to make zero-value claims all the way from `_startTime` in order to sync the contract up to the current week.
However the issue is we need the same concept for users (`userStartTime`), otherwise if someone were to lock veBAL in 2 years time and want to claim BAL tokens then they would have to go through all previous BAL distributions whilst we know that they won't receive any fees from before their first lock.
We then save the timestamp of the first week which the user would be eligible for a distribution and when first claiming a …
> Prevent late lockers from having to claim many weeks of zero-value distributions

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
As discussed during #1191 reviews, we must take care when handling token checkpoints around the week boundaries.
Setting a minimum interval between automatic token checkpoints results in checkpoints on Wednesday preventing claims of the most recent week on Thursday despite the entire week being complete (and therefore would be expected to be claimable).
A better way of handling this would be to avoid multiple intra-week checkpoints while ensuring that we get accurate checkpoints on either side of a week boundary. We then switch to performing a checkpoint only once per week unless we're nearing the end of the week to ensure we get an accurate final reading (provided someone claims tokens on a wednesday).
> Improve token checkpointing logic

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
I've packed the user and token level data into structs to take advantage of packing storage. We could potentially go further by loading the struct into memory and then performing only a single write back to storage but we can do that later if necessary.
> Use structs to pack storage slots in FeeDistributor

- pkg/liquidity-mining/contracts/gauges/ethereum/SingleRecipientGaugeFactory.sol
- pkg/liquidity-mining/contracts/gauges/polygon/PolygonRootGaugeFactory.sol
- pkg/liquidity-mining/contracts/interfaces/ISingleRecipientGaugeFactory.sol
We're going to have 3 factories which deploy `ISingleRecipientGauges` and so need a defined interface to read from the factory getters. This is needed for governance scripts which interact with these factories
> Add a proper interface for all single recipient gauge factories

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
I've checked over all the usage of arithmetic and added comments in situations where SafeMath is unnecessary and SafeMath where it is potentially necessary.
As much of the maths in this contract uses timestamps and user epochs which are small we don't need SafeMath in many places. In fact the only place I can see needing it is when checking how many new tokens the contract has received: if someone can forcibly burn some tokens from the FeeDistributor address is could cause an underflow when calculating how many new tokens to distribute.
> Add SafeMath to FeeDistributor

- pkg/liquidity-mining/contracts/gauges/arbitrum/ArbitrumRootGauge.sol
- pkg/liquidity-mining/contracts/gauges/arbitrum/ArbitrumRootGaugeFactory.sol
- pkg/liquidity-mining/contracts/gauges/arbitrum/IArbitrumFeeProvider.sol
- pkg/liquidity-mining/contracts/gauges/arbitrum/IGatewayRouter.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
This PR adds a new StakelessGauge implementation which will bridge the minted BAL to a recipient on Arbitrum.
For context how to use the Arbitrum bridge to verify _postMintAction, see [here](https://developer.offchainlabs.com/docs/bridging_assets#default-standard-bridging) and [here](https://developer.offchainlabs.com/docs/l1_l2_messages#ethereum-to-arbitrum-retryable-tickets)
Snippets relevant to setting Arbitrum fee parameters:
>The current base submission fee returned by ArbRetryableTx.getSubmissionPrice increases once every 24 hour period by at most 50% of its current value. Since any amount overpaid will be credited to the credit-back-address, it is highly recommended that applications judiciously overpay relative to the current price.
>
>In a future release, the base submission fee …
> feat: add ArbitrumRootGauge contract

- pkg/liquidity-mining/test/ChildChainStreamer.test.ts
- pkg/liquidity-mining/test/RewardsOnlyGauge.test.ts
This adds tests which perform sanity checks that the ChildChainStreamer distributes rewards linearly and that RewardsOnlyGauge will claim these and distribute them proportionally to LP deposits
> Add smoke tests for child chain gauges

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
- pkg/liquidity-mining/contracts/interfaces/IFeeDistributor.sol
We currently have no easy way to calculate how many rewards a user is expected to receive until the week completes. We could build this into the FeeDistributor but in order to calculate this externally we need to know how many tokens are being distributed in a the current week.
This PR adds a simple getter for this value so if the FeeDistributor doesn't support this natively we can still calculate this value.
> Add a getter to FeeDistributor for the amount of tokens distributed in a given week

- pkg/liquidity-mining/contracts/fee-distribution/FeeDistributor.sol
Currently `FeeDistributor` starts accepting checkpoints from a timestamp `startTime` which is enforced to fall in the week after which the contract is deployed (or potentially multiple weeks in the future).
This has the nice property of that it ensures that `votingEscrow` will have been deployed in a week prior to `startTime` and so a total supply checkpoint for `startTime` will exist. Otherwise if `VotingEscrow` and `FeeDistributor` were deployed in the same week and `FeeDistributor` immediately started accepting fees then users would need a balance of `veBAL` on the Thursday previous to `veBAL`'s deployment. This is bad.
If we deployed the `FeeDistributor` as is today, then the earliest valid value for `startTime` is the 14th. After this any tokens sitting on the `FeeDistributor` can be …
> Allow FeeDistributor to start distributions immediately when deployed

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
Extracts optimisation to avoid rereading token weights from  d7de6f6222741c0ac44ce1db5896acf1cafefef6
> refactor: remove unnecessary reads of normalized weights

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
By normalising after we interpolate the weight of a token we save a warm SLOAD per weight calculated. This saves 2 SLOADs on swaps and `numTokens` on weight updates. As a bonus the code looks prettier.
My only concern with this is if `_denormWeightSum` is small then we're compressing the range of values we're interpolating over and so we're more likely to see rounding errors. My thoughts on this however is that:
- You'd have to work pretty hard to reduce `_denormWeightSum` in such a way that this was significant based on how many decimal places we have to work with and that's assuming that it's even possible.
- Before these rounding errors became significant you'd likely be changing your weights by so much over such a small period of time that you'd be arbed hugely anyway.
**That said …
> Normalise weights after interpolation instead of before

- pkg/governance-scripts/contracts/20220322-veBAL-activation/veBALDeploymentCoordinator.sol
- pkg/liquidity-mining/contracts/admin/DistributionScheduler.sol
- pkg/liquidity-mining/contracts/interfaces/IRewardTokenDistributor.sol
- pkg/liquidity-mining/contracts/interfaces/IStakingLiquidityGauge.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
- pkg/liquidity-mining/contracts/test/MockRewardTokenDistributor.sol
- pkg/liquidity-mining/test/DistributionScheduler.test.ts
This contract aims to allow partners to schedule distributions of their tokens on gauges without needing to fire off a transaction at the same time every week, instead they can queue up multiple weeks worth of rewards and leave the triggering of the distribution to bots like Defender.
Anyone may provide tokens to the `DistributionScheduler` along with a timestamp at which it is to be sent to the gauge, this is then stored in a linked list of all the other distributions of this token to a particular gauge. We can then just iterate through this list up to the current timestamp in order to start any distributions which are scheduled to do so.
We require that distributions start at Thurs 00:00 UTC for consistency with BAL rewards and also to prevent DOS from having many 1 wei distributions …
> add DistributionScheduler contract

- pkg/pool-weighted/test/GradualValueChange.test.ts
This PR adds tests for the GradualValueChange library to ensure that it correctly interpolates values when there is a zero duration change.
> Add tests for GradualValueChange with zero duration

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
This PR changes the checks for any ongoing gradual changes to first check the end time and only if we fail that determine which condition we're failing on.
This saves us from decoding the start time and performing a comparison against the current time if we know it's going to succeed (as we know we're past the end time.)
> Optimise checks for if a gradual change is scheduled/ongoing

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Currently we perform a lot of warm SLOADs whenever we perform a weight update as we're reading `_denormWeightSum` twice per token. This isnt ideal as we can easily get >50 reads for large pools.
Another factor feeding into this is when we are adding a new token we need to write the denormalised weight of the new token into storage using the value of `_denormWeightSum` **after** the token is added rather than before.
> Refactor _encodeTokenState to allow passing a custom denormalisation factor

- pkg/pool-utils/hardhat.config.ts
The risk of getting used to broken CI... we don't always notice when other things are broken
> fix: fix pool-utils CI to allow it to deploy oversized ManagedPool

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/solidity-utils/contracts/helpers/ERC20Helpers.sol
This PR tries to avoid all the SLOADs associated with refreshing the list of tokens in the pool by constructing the new array in memory by appending the new token onto the old array.
> ManagedPool: construct the updated array of tokens in the pool in memory

- pkg/pool-weighted/test/ManagedPool.test.ts
This addresses RNG issues, as well as incomplete intializations. With these, all ManagedPool tests pass.
> Fix flaky ManagedPool tests

- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/test/task.fork.ts
Holdover error from #1286 as we're trying to read from `factory` from the output rather than  `NoProtocolFeeLiquidityBootstrappingPoolFactory`
> Fix fork test for NoProtocolFeeLBP

- pkg/deployments/src/task.ts
As #1310 logs the deployment transaction hashes for _all_ contract deployments, this had the unfortunate side-effect that we log the deployment transactions of contracts deployed as part of our fork tests into `mainnet.json`.
We're most likely to perform these fork tests around the point in which we're performing a live deployment so as well as introducing noise into the json files, there's a good chance that we may omit committing the actual deployment transaction.
> Prevent fork tests from adding to `deployment-txs`

- pkg/vault/contracts/test/MockAuthenticatedContract.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
I noticed that we had a couple of contexts descriptions backwards so fixed this.
Something that made me a little uneasy about the current tests is they always call into the Vault which is a "special" contract in the context of the Authorizer (calling into the `setAuthorizer` function in particular). If instead we have a generic authenticated contract we don't have to think about whether we're testing something specific for that function or not.
Swapping out the contract which we test against also makes it easier for us to test handling the return value in later changes.
> Update Authorizer tests

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This PR replaces any public state variables with private versions and a getter.
One question this raises is whether we want to be more careful about potential confusion between `isPermissionGranted` and `hasPermission` (I've added some natspec on this). One option is to not expose the `isPermissionGranted` getter but this would cause confusion when trying to figure out if someone's permission is local or global.
> Add explicit getters for TimelockAuthorizer

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
We only really expect a delay to be set up at around the same time at which we're performing the initial setup of a new permission. As it's an infrequent action with potential for griefing (a 2 year delay to withdraw protocol fees wouldn't be fun) it makes sense that only the root can perform this action.
> Only allow root to schedule a change to a delay

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
This PR aims to fix the "whack-a-mole" problem where giving granter powers to an address allows it to create infinitely more granters such that it's impossible for those granter powers to be meaningfully revoked. (Similarly with revoker powers).
To fix this we only allow the root address to create more granters/revokers, ensuring that an entity can only create more entities if they are "one level down the org chart".
I've retained the ability to granters to remove other granters as these act as a good first line of defense if a granter goes rogue (assuming that it's first action isn't to kill off the other granters) as we expect them to be more agile than the root and will likely become aware of the rogue granter before the root does.
> Only allow root to create new granters or revokers

- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
Currently when migrating a role we migrate the admin role for that role at the same time. The issue with this is that all roles have the _same_ admin role - the global admin role.
We're then migrating twice the number of roles unnecessarily as shown by the tests still passing even after we remove the code to migrate the role admins.
> Stop migrating role-admins

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/contracts/test/MockAuthenticatedContract.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
When we deploy the `TimelockAuthorizer` we grant permissions for the first `root` to grant or revoke all actions (`WHATEVER` on `EVERYWHERE`). This allows them to grant permissions to other accounts without having to first make themselves a granter for that permission.
I noticed while working on the migrator that we don't clean up these permissions when transferring the `root` account. If we transfer `root` then the old `root` will retain it's global grant/revoke permissions and the new `root` will need to manually give themselves these permissions before they can do anything.
This seems like a recipe for accidentally leaving very powerful permissions on an old `root` account which can then be used to grief later down the line so I've updated `claimRoot` to properly transfer these to the …
> Ensure that global permissions are properly transferred along with root status.

- pkg/pool-utils/contracts/factories/BasePoolSplitCodeFactory.sol
- pkg/pool-utils/test/factories/BasePoolSplitCodeFactory.test.ts
Having removed the non-split factory in #1339, we now have only one. Add the "mortality" functionality directly to this base class (requiring no modifications to derived contracts), instead of doing a separate Mixin. 
Closes #1127
> Add disable function to BasePoolSplitCodeFactory

- pkg/pool-stable/test/StablePool.test.ts
- pkg/pool-utils/contracts/LegacyBasePool.sol
- pkg/pool-utils/contracts/test/MockLegacyBasePool.sol
- pkg/pool-utils/test/LegacyBasePool.test.ts
This makes all pools process a zero-valued protocol swap fee percentage. StablePool was already resetting last invariant on recovery mode deactivation, so we don't need to worry about that. 
The diff is best reviewed with no whitespace changes.
> Pay no protocol fees on recovery mode

- pkg/pool-stable/contracts/StableMath.sol
Spotted in a code review with @rabmarut, this addition from [line 210 of the Curve code](https://etherscan.io/address/0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7#code) should have an overflow check, as Vyper does by default.
> Add missing overflow check on stable invariant

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/optimism/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
Uses #1395 to skip token action ids. 
Note that not all factories have been deployed in all networks, and not all deployed factories have been used, so some contracts only have entries in a number of networks. In particular, many Arbitrum and Optimism factories have not been used.
> Add action IDs for Pools

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-utils/contracts/BasePool.sol
With this, the only remaining dependent on LegacyBasePool is PhantomStablePool. This change was rather easy, as LinearPools ignore protocol fees (the main difference between Legacy and Base).
> Migrate LinearPool to BasePool

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/test/BasePool.test.ts
- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
- pkg/pool-weighted/test/InvariantGrowthProtocolFees.behavior.ts
- pkg/pool-weighted/test/ManagedPool.test.ts
Port remaining Recovery Mode functionality to BasePool, in preparation for deprecating LegacyBasePool. All normal joins/exits revert when paused. Temporarily skip WeightedPool tests broken by this.
> Base pool parity

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pvt/helpers/src/models/pools/stable-phantom/StablePhantomPool.ts
Part of the preparation for adding joins/exits, mint less than the max balance initially, making "room" for minting BPT later in joins.
> PhantomStable: Mint half max BPT

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pvt/helpers/src/models/pools/stable-phantom/StablePhantomPool.ts
They artificially only supported up to 4 tokens, but this need not be the case.
> Support 5 tokens in PhantomStable

- pkg/pool-utils/contracts/AumProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockAumProtocolFeeCache.sol
- pkg/pool-utils/test/AumProtocolFeeCache.test.ts
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Required for https://github.com/balancer-labs/balancer-v2-monorepo/issues/1370, but also nice to have in general.
AumProtocolFeeCache inherited from ProtocolFeeCache for no reason at all - I removed this, and in the process fixed a test that was wrong,
> Remove dependency on FeeCache from AumFeeCache

- pkg/pool-utils/contracts/RelayedBasePool.sol
- pkg/pool-utils/contracts/test/MockRelayedBasePool.sol
RelayedBasePool is the last thing other than StablePool that depends on LegacyBasePool.
> Remove last dependency on LegacyBasePool

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-utils/contracts/ProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/pool-utils/test/ProtocolFeeCache.test.ts
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
This makes the module replicate the `BasePool` behavior (replace protocol fees with zero, support recovery mode), meaning it can be used by Pools without requiring any further changes (such as the fee override we used to have).
Fixes #1370.
> Make fee cache aware of recovery mode

- pkg/balancer-js/src/pool-stable/encoder.ts
- pkg/interfaces/contracts/pool-stable-phantom/StablePhantomPoolUserData.sol
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pvt/helpers/src/models/pools/stable-phantom/StablePhantomPool.ts
- pvt/helpers/src/models/vault/Vault.ts
- pvt/helpers/src/models/vault/types.ts
Support single token exit, verifying that it is equivalent to a BPT for token swap
> PhantomPool: add single token exit

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This PR uses a more flexible delay mechanism for changing the delays of actions. Instead of always waiting for the entirety of the current delay before the new delay can be introduced it now only requires:
```
max(old_delay - new_delay, min_delay)
```
This ensures that we always have to wait at least `old_delay` before an action may be executed when reducing its delay, however when increasing the delay we don't need to wait for a long time unnecessarily. We introduce a minimum delay to allow for scrutiny of any pending delay changes to avoid potential mistakes.
closes #1436
> Add smarter timelock delay mechanism

- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
This PR adds a new `_delaysData` argument to the TimelockAuthorizerMigrator which allows us to set an initial set of delays for various actions.
~~Thanks to #1438, this doesn't result in us extending the amount of time necessary for the migrator to execute out to the longest delay being set.~~ Delay mechanism smart, Tom dumb.
I've got an optional commit on here which reduces the number of SSTOREs we do to keep track of the execution IDs to execute but we could equally remove that.
> Set up initial TimelockAuthorizer delays in Migrator

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
I've written down some of the assumptions on root liveness made in `manageGranter/Revoker` into the natspec, i.e. that the root will slap down a malicious granter/revoker before the attacker can perform an action as we can't rely on the other granters/revokers to cancel the malicious actions (as their granter/revoker status would be revoked.)
> Add more explicit docs around managing granters/revokers and cancelling malicious actions

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
I'm open to being convinced that this is unnecessary but it feels like a risk free way of making the system safer as well as improving UX for the root.
Root has a global permission for `GRANT_ACTION_ID` for `WHATEVER`. If we assume that it create any granter of the same scope then it should have a right to cancel all scheduled granting of permissions which cannot be removed by anyone else (similarly for revoking of permissions).
Root doesn't however have a global permission to perform all actions. Should there be an action for which there is a delay for both granting and performing then if an address with that permission goes rogue then it's conceivable that the root will not be able to grant itself that permission in time to cancel any malicious actions.
Concrete (if pretty contrived) …
> Always allow root to cancel a scheduled action

- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
This removes the multi-step process of migrating roles as used before and instead just sets them in the constructor. This method seems to work for something in the range of 400-500 roles being migrated so is plenty for us.
We maintain a couple of extra functions so that we can set up delays and start the root migration separately to ensure it's properly set up before switch out the authorizer on the vault.
> Simplify TimelockAuthorizerMigrator

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizerDeployer.ts
- pvt/helpers/src/models/authorizer/types.ts
I find it a bit jarring to have to translate from `admin` to `root`. This PR does a find and replace on admin to root in the tests and TS helpers around the TimelockAuthorizer.
> Rename admin to root in TimelockAuthorizer tests

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
To remove the overload from the `getActionId` function I've introduced the concept of "extended action IDs". Whenever we calculate something of the form `keccak(actionId, how)`, the output is now an extended action ID.
Renaming the two argument version of `getActionId` to `getExtendedActionId` then removes the overloading from the interface.
Separately to this, the main usage of extended action IDs are going to be for the 4 actions of the authorizer (grant, revoke, execute, set delay). It's then probably worth creating specialised getters for these action as it saves users from having to make two calls into the authorizer (one to get the base action ID) and knowing to cast the execution ID to a bytes32.
I've then broken it out into `getGrantPermissionActionId`, …
> Remove overload from  `TimelockAuthorizer.getActionId`

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
I've added a healthy dose of paranoia to the tests for the authorizer.
We now check that root's powers to remove malicious granters/revokers can't be removed by removing its global grant/revoke permissions.
We also have a demonstration that starting from a root account with no permissions we can execute an authorizer migration in a couple of scenarios.
> Add more recovery scenario tests to TimelockAuthorizer

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerMigrator.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This PR aims to address two sources of potential confusion in the new Authorizer:
1. An overloading of the concept of "global" which can mean either a) a permission to perform an action anywhere or b) a permission to perform any form of a particular action in different places in the code.
2. The concept of "WHATEVER" which doesn't really have any easily understood meaning except by examining how it's used.
---
We have the concept of an "extended" action ID in the new Authorizer which was defined as `keccak(actionId, how)`. To give a permission to perform any `how` of an action, we would grant a permission for the action ID for when `how = WHATEVER`.
These terms are now renamed so that an extended action ID is now defined as `keccak(baseActionId, specifier)`. `WHATEVER` is then renamed to …
> Rename some concepts in TimelockAuthorizer to help reduce potential confusion.

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-utils/contracts/BaseGeneralPool.sol
- pkg/pool-utils/contracts/BaseMinimalSwapInfoPool.sol
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
Add check to top-level onSwap, remove from derived contracts. Linear pools still need the modifier, as they implement the IGeneralPool interface, vs inheriting from it.
> Move logic to revert on swap when paused to base contracts

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
The difference between these two functions is a little subtle so I think it's worth beating people over the head with it.
> Add natspec for canPerformSpecificallyOrGenerally and hasPermissionSpecificallyOrGenerally

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pkg/pool-utils/contracts/BaseGeneralPool.sol
Override higher level swap hooks from BaseGeneralPool to handle swaps with BPT separately. Override the swap fee calculations in the base class so that join/exit Swaps are exactly the same as regular swaps with BPT (and update tests to reflect this).
> PhantomStable: make join/exitSwap consistent with regular swaps

- pkg/liquidity-mining/test/FeeDistributor.test.ts
We were not testing the actual token transfer when claiming. I also made it so both users get different token amounts, and each token have their own unique amount (best seen commit-by-commit).
> Improve FeeDistributor tests

- pkg/deployments/tasks/20220609-stable-pool-v2/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210624-stable-pool/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210727-meta-stable-pool/test/task.fork.ts
#1435 renamed the StablePool maths helpers which are used in the Stable and Metastable fork tests. This prevents us from running any of the fork tests.
This PR updates the imports in the fork tests to point at the `stable-phantom` directory.
> Update stable pool tests to pull invariant calculation from stable phantom helpers

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Address some stale comments, mostly referring to not minting/burning BPT in PhantomStable pools, which is no longer the case.
(I swear I fixed some of these in other PRs.)
> PhantomStable: Update stale comments

- pkg/interfaces/contracts/pool-linear/IStaticAToken.sol
- pkg/pool-linear/contracts/LinearPoolRebalancer.sol
- pkg/pool-linear/contracts/aave/AaveLinearPoolRebalancer.sol
- pkg/pool-linear/contracts/test/MockStaticAToken.sol
Marking as WIP as some things are still missing, mostly tests.
In terms of features, we might want to do an early return if the main balance is between the targets, unless a `force` value is passed. 
Also, it'd likely be a good idea to make it so the reward is always either the main token or the wrapped token, though this will require interacting with the wrapping entity to query the rate (so that we don't e.g. wrap the full amount).
It's also fairly simple to make this abstract and then specialize it for Aave the same way we did LinearPools, making this more reusable.
> Add LinearPoolRebalancer

- pkg/pool-stable-phantom/contracts/StableMath.sol
Our friends at COW protocol point out that since we no longer have directional rounding on the invariant calculation, these comments are obsolete.
> StableMath: remove stale comment

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
In most of the join/exit hooks in `PhantomStablePool` we make use of the arguments which are length checked by the vault of validating user input, however in `_joinExactTokensInForBPTOut` however we use the `_getTotalTokens()` function.
I've removed the usage of `getTotalTokens` for consistency but we may want to switch the other way.
> Standardise input length checking across join hooks

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
I've applied the optimisation from the LinearPoolRebalancer here as we know that a PhantomStablePool will always have 3+ tokens.
https://github.com/balancer-labs/balancer-v2-monorepo/blob/2b70ac0863a654b863fbd105d0a5a48caaa81478/pkg/pool-linear/contracts/LinearPoolRebalancer.sol#L68-L73
> Optimise reads in `getVirtualSupply()`

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
I haven't made the `execute` function non-reentrant but I've documented our thinking on reentrancy in `TimelockAuthorizer`. Making `execute` non-reentrant would prevent us from having a delayed action set up which would result in another delayed action being executed (although I don't think the chances of this occurring are very high).
I've also prevented calls into the `TimelockExecutor` being scheduled (although as noted, these will revert due to the address check in `TimelockExecutor.execute` anyway)
> Add documentation around reentrancy in the TimelockAuthorizer

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
`getTokenRateCache` doesn't return empty values and `exemptFromYieldProtocolFeeToken` has been renamed to `protocolFeeExemptTokenFlags`
> Fix errors in PSP natspec

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This PR should be a noop as it's just moving functions around within the PhantomStablePool contract.
I'd recommend going through each commit one by one as I've moved all the functions on a particular topic together in each commit. Once that's done it would be good to take a look at the contract as a whole to get a feel for the flow.
Generally in each section we should have all getter functions sitting above the relevant setter functions (see Amplification section for an example)
> Reorder functions in PhantomStablePool

- .github/actions/setup/action.yml
- .github/workflows/ci.yml
- .github/workflows/deployment-checks.yml
This PR combines installing node and cached installs of dependencies into a single "setup" action so we don't need have these steps repeated in each job.
> Abstract away boilerplate in CI into a custom action

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Some of these functions feel a bit confusing due to nested if statements (`_getTokenRateRatios`  being the main offender).
This PR tries to keep these functions as flat as possible to improve (imo) readability.
> Remove layers of nesting from functions iterating over tokens

- pkg/deployments/src/forkTests.ts
- pkg/deployments/tasks/2022xxxx-timelock-authorizer/test/task.fork.ts
This is probably a nice to have; it allows using `.only` and `.skip` in `describeForkTests` as if they were regular `describe` blocks. It's useful when there's an incomplete fork test for a task that has not been deployed. 
Illustrating the use case, this PR also skips the timelock authorizer fork test which is expected to fail at this point. The CI task for fork tests should be green in this PR.
> Adding .only and .skip to describeForkTests.

- pkg/liquidity-mining/contracts/BoostV2.vy
This adds a simple function to avoid having to migrate boosts one by one.
> Allow veBoost2 to migrate multiple boosts in a single call

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This PR pulls in the change to `_scalingFactors()` from https://github.com/balancer-labs/balancer-v2-monorepo/pull/1496/commits/6ddccdf2d58eaef398ac93f111aea8969ca611dd into master to minimise the diff of #1496
> Improve readability of _scalingFactors() in PhantomStablePool

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pkg/pool-stable-phantom/test/StablePhantomPoolFactory.test.ts
#1496 currently include a switch from 4 to 5 protocol fee exemption flags as well as implementing the actual exemption from fees.
This PR splits off the first feature as this can be easily tested and merged in isolation.
> Add an explicit yield protocol fee exemption flag for BPT

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
#1530 didn't properly get rid of the `tokensAndBPTRateProviders` and `exemptFromYieldProtocolFeeFlags` arrays so this PR cleans them up.
> Remove duplicated creation of arrays in StablePhantomPool constructor

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/interfaces/contracts/standalone-utils/IProtocolFeePercentagesProvider.sol
- pkg/solidity-utils/contracts/openzeppelin/SafeCast.sol
- pkg/standalone-utils/contracts/ProtocolFeePercentagesProvider.sol
- pkg/standalone-utils/test/ProtocolFeePercentagesProvider.test.ts
This new extensible component will hold all protocol fees, and should be the preferred solution when querying and altering them. Swap and flash loan fees can still be queried and set via the ProtocolFeesCollector (as this contract fallbacks to it for those), but ideally we'd just work with this new one for consistency and simplicity.
By making fee types immutable (except for their current value), I believe this will suffice for all expected use cases.
Note that there's a single function to set fee values, which means a single permission will allow setting fees for any type. In the future, we expect to expand our action id system to be more granular when it comes to action parameters, and make a contract with more fine-tuned access control the only account that can call …
> Add ProtocolFeePercentagesProvider

- pkg/pool-weighted/test/ManagedPool.test.ts
- pvt/helpers/src/models/types/TypesConverter.ts
- pvt/helpers/src/models/vault/Vault.ts
- pvt/helpers/src/models/vault/VaultDeployer.ts
- pvt/helpers/src/models/vault/types.ts
This is a bit of a pre-requisite for us to create pools that use this provider. I thought the Vault model would be a good place to do this, since it is a singleton like the Vault, and it only depends on it.
> Add ProtocolFeeProvider to Vault model deployment

- pkg/interfaces/contracts/pool-utils/IBasePoolSplitCodeFactory.sol
- pkg/interfaces/contracts/pool-utils/ILastCreatedPoolFactory.sol
- pkg/pool-linear/contracts/LinearPoolRebalancer.sol
- pkg/pool-linear/contracts/aave/AaveLinearPool.sol
- pkg/pool-linear/contracts/aave/AaveLinearPoolFactory.sol
- pkg/pool-linear/contracts/aave/AaveLinearPoolRebalancer.sol
- pkg/pool-linear/test/AaveLinearPool.test.ts
- pkg/pool-linear/test/AaveLinearPoolFactory.test.ts
- pkg/pool-utils/contracts/factories/BasePoolSplitCodeFactory.sol
- pkg/pool-utils/test/factories/BasePoolSplitCodeFactory.test.ts
This ended up being non-trivial due to a circular dependency in the LinearPool and its AssetManager. I found a nice way to solve said cycle at the factory, at the cost of having to add a `getLastCreatedPool()` getter (if we wanted to, we could always `delete` this slot, but that's overkill IMO).
The bigger downside is that it seems there's no way (outside of assembly memory shenanigans) to craft the full creation code of a contract (including abi-encoded constructor arguments) without making a full copy of the original creation code, due to how `abi.encodePacked` works. However, even taking this into account, the total cost of a Linear Pool + Rebalancer deployment is ~5.5M gas, which is way below block sizes (if a bit on the expensive side :sweat_smile:).
Given that the constructor …
> Use AaveLinearPoolRebalancer in AaveLinearPools

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
Using a bitmap for the exempt flags (vs separate booleans) saves ~400 bytes.
> Stable: Use bitmap for exempt token flags

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This saves ~500 bytes, putting the total bytecode at 23.7kB, meaning we're below the limit!
> Use token getters in Phantom Pool

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Rather than creating two arrays which don't include BPT, then iterating through both multiplying together we can just have one and apply the token rate ratios directly and then drop the BPT element.
> Simplify calculation of adjustedBalances

- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
This will prevent accidentally using them outside of getters, at least on other files.
> Make immutable state variables private

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This comb is very fine-toothed. Previously we had both calculatedAmount and amountCalculated. Now we have both givenAmount and amountGiven. Use the naming convention that's internally consistent and also matches the Vault.
> Stable Comb: Match Vault nomenclature

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
We were validating the length of the exemptions array - but only after the main constructor, after the code using it has already run. Move the check to the contract where it's used. Also add a test for it.
Note that we are now validating the rateProviders length twice (there is also a 3-way InputHelpers.ensureInputLengthMatch in the main constructor). We could drop rateProviders and make it a two way (tokens + durations), but I don't think this redundancy is too bad: not very expensive, and future proofed in case we change something in StablePoolStorage, forget the dependency, and fail to add the check back into the main contract.
> Stable: move exemption check

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
It is a bit messy to pay protocol fees at the beginning of _onJoinPool and _onExitPool, but then rely on the individual functions to update the invariant afterwards. Refactor with the pay/reset header/footer, like the BPT swap does.
> Stable: self-contained top-level join/exit

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolAmplification.sol
Reduce length of the main file by moving the Amplification factor storage and handling into another contract. I think that's the most separable thing. (Anything that touches immutable storage has a StablePoolStorage dependency.)
Mutually exclusive with #1554 (which splits out both Amp and token rate cache functionality).
> Stable: separate Amp functionality

- pkg/solidity-utils/contracts/openzeppelin/ERC20.sol
We don't yet use this, but once #1566 is merged we'll be able to use the bits left in misc data by it to store total supply.
We could also potentially use this in weighted pools, or any pool that does not use the full misc data.
> Make totalSupply overrideable

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-utils/contracts/BaseGeneralPool.sol
- pkg/pool-utils/contracts/BaseMinimalSwapInfoPool.sol
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/test/MockBasePool.sol
- pkg/pool-utils/test/BasePool.test.ts
This helper doesn't do much for now, but it is a stepping stone towards fixing ComposableStablePools behaving incorrectly during queries, and also preventing these types of mistakes in the future.
It also lets us remove a bunch of lines from the stable pool, which is a nice bonus.
> Add _beforeSwapJoinExit()

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
Instead of storing the target in all of its full precision glory, we downscale them by 1e18 on writes and upscale on reads. This means they'll have no fractional part.
With this change, I was able to reduce the number of bits each target uses to 32 (since the largest target will still be ~4 billion for an 18 decimal token). The extra space in misc data will be used in a follow-up PR to store the total supply.
> Make LinearPool targets use fewer bits

- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/contracts/test/MockStablePoolStorage.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pkg/pool-stable-phantom/test/StablePoolStorage.test.ts
- pvt/helpers/src/models/tokens/Token.ts
This PR pulls out all the contract initialisation tests from `StablePhantomPool.test.ts` to do with the constructor setup in `StablePoolStorage`.
Something to note is that we need to provide an implementation of `_scalingFactors` in `MockStablePoolStorage`. This implementation is different to that in `StablePhantomPool` as we cannot access the token rate caches. We could pull "live" rates from the rate providers but we'd still need to have separate tests for the full implementation anyway so I've simplified to ignore rates for the returned scaling factors.
> Split off tests for StablePoolStorage

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolRates.sol
This caused some mystery issues in testing `StablePoolRates` as we can't properly test non-delegated ownership.
> Move identification of setTokenRateCacheDuration as owner only action to StablePoolRates

- pkg/pool-stable-phantom/contracts/StablePoolRates.sol
Necessary for StablePoolRates tests.
This PR adds `oldRate` to the response from `getTokenRateCache` as well as adding a small optimisation for the happy path of there being a cache for the token in question.
> Expose old rate on getTokenRateCache

- pkg/pool-stable-phantom/contracts/StableMath.sol
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/test/MockStableMath.sol
Calculate the preJoinExitInvariant externally, and pass it into StableMath, avoiding 1) computing it twice or 2) passing it *back* from StableMath.
> Stable: calculate preInvariant only once

- pkg/pool-stable-phantom/contracts/StablePoolRates.sol
- pkg/pool-stable-phantom/contracts/test/MockStablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
Previously we failed on any calls which read the token rate caches. This is incorrect as these values can still be read, they will only become an issue once the cache has expired (and so the pool will query the rate provider for the new rate).
We then move the induced failures to just be around the function which makes this external call to ensure that what we're testing is as close as possible to the real behaviour.
> Restrict induced price rate failures only affect calls which query new rate

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-stable-phantom/contracts/StablePoolRates.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/contracts/test/MockStablePoolStorage.sol
- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pkg/pool-stable-phantom/test/StablePoolStorage.test.ts
The fact that we need to implement this function is one of the sources of confusion re. storage.
Turns out, we don't.
> Remove single token scaling factor access

- pkg/pool-stable-phantom/contracts/StableMath.sol
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/contracts/test/MockStableMath.sol
- pkg/pool-utils/contracts/BasePool.sol
This is very large - I'm not sure how I'd go about reviewing the diff. Perhaps the point is that the diff is hard to review because the original code was hard to follow. Instead, a better strategy might be to simply read the new code, which is (hopefully) much more straightforward.
Some documentation is missing, but the rough shape is there. We now work almost exclusively with BPT-less arrays and indices, and only adjust those at the borders. With these changes in, we can rework the storage layer to better match what we need.
In the process I also addressed the famous issue where upscaleArray would have an extra require check, in what I think is a nice way.
> Refactor swaps, joins and exits in StablePhantom

- pkg/liquidity-mining/contracts/test/TestFeeDistributor.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/solidity-utils/contracts/helpers/EOASignaturesValidator.sol
- pkg/standalone-utils/contracts/relayer/special/DoubleEntrypointFixRelayer.sol
Warnings cause linter CI to fail in TS but not in solidity. This makes it a bit of a pain to find where the TS warnings are if we have solidity warnings creating noise.
I've made solhint ignore those warnings.
> Fix linter warnings in solidity

- pkg/pool-stable-phantom/contracts/StablePoolProtocolFees.sol
This implements what I think is the correct way to charge protocol fees before a join/exit. Notably, we need to compute a third invariant we were not considering before (the total growth one).
If the old amp equals the current one, this invariant is actually the current invariant and could be later reused, but we'd need to add more logic to do this.
> Update pay before join exit

- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/solidity-utils/contracts/test/BalancerErrorsMock.sol
- pkg/solidity-utils/test/BalancerErrors.test.ts
Instead of the error messages always being prefixed with `BAL#`, we allow to pass in the first three characters, so that custom pools can use their own set of error codes without risking any collision.
This replaces #1565.
For more context
> Allow to pass custom prefix for error messages

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
We have lots of "withBpt" and "withoutBpt" names, which while helpful and self-documenting, aren't always consistent. (And are a bit awkward besides.)
Since nearly all "lower level" processing occurs with BPT removed, and generally only the outermost Vault interface functions (to and from hooks) require the full array of registered tokens, we'd like to standardize on the convention that "balances" and "index" refer to "withoutBpt" arrays. The "withBpt" arrays, as passed in, correspond to the registered tokens, so we call them registeredBalances and registeredIndexIn/Out.
scalingFactors normally do include all factors, and are "withBpt", so if we pass around scaling factors with Bpt removed, this is the exception, and we'll call them "scalingFactorsWithoutBpt".
(I tried to drop the BPT …
> Stable: standardize naming conventions

- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
During review, noticed that with library additions, we were checking the array length twice on joins and exits: but not testing for it.
> Stable: Missing tests

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockRecoveryMode.sol
- pkg/pool-utils/contracts/test/MockRecoveryModeStorage.sol
Every join and exit in the system needs to check the Recovery Mode flag, so it will save gas to pack it into miscData, vs loading it from a bool variable every time.
It means we lose a bit off the swap fee percentage, but 63 is more than enough.
Closes #1371
> BasePool: use _miscData for Recovery Mode

- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
- pkg/pool-utils/contracts/BasePool.sol
- pkg/standalone-utils/test/BalancerQueries.test.ts
This adds a call to `_beforeSwapJoinExit()` to the queries, which will make them more correct: they'll revert if the pool is paused, and more importantly do any work that is required before the action, such as updating the rate cache in a stable pool.
Adding tests for BasePool directly would be a bit cumbersome as we don't have a proper mock right now, so I simply added tests to the queries for now.
> Fix BasePool queries

- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
- pkg/pool-stable-phantom/contracts/test/MockStablePoolStorage.sol
- pkg/pool-stable-phantom/test/StablePoolStorage.test.ts
These will let us detect situations in which we can skip some invariants (e.g. the non-exempt invariant or the total growth invariant) since they will equal one of the other two.
Storing them as immutable values uses less bytecode than packing them into the bitmap (and also uses less gas).
> Add global exemption flags

- pkg/pool-stable-phantom/contracts/StablePoolProtocolFees.sol
- pkg/pool-stable-phantom/contracts/test/MockStablePoolProtocolFees.sol
- pkg/pool-stable-phantom/test/StablePoolProtocolFees.test.ts
- pkg/pool-stable-phantom/test/StablePoolStorage.test.ts
This reduces the number of invariants we compute by one when either all tokens are exempt or none are (see #1595), as well as skips an unnecessary balance adjustment. It also begins the introduction of protocol fee tests.
> Optimize invariant calculation for edge cases

- pkg/pool-stable/contracts/ComposableStablePoolProtocolFees.sol
There's some extra safemath we don't need in `_updateInvariantAfterJoinExit` but that's handled in #1603 and I don't want to create merge conflicts for no reason.
> Remove unnecessary overflow check

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-utils/contracts/test/MockVault.sol
I've pulled across the implementation of `getVirtualSupply` from `ComposableStablePool` as it's more efficient, the same optimisation is used in `_isMainBalanceWithinTargets`.
I've also updated some comments as they were saying that the total supply is fixed whereas it's isn't.
> Final touches on LinearPool

- .github/workflows/ci.yml
The Pool tests are massive and take much longer than everything else - this splits them into separate jobs.
> Split pool test jobs

- pkg/pool-stable/contracts/ComposableStablePool.sol
- pkg/pool-stable/contracts/ComposableStablePoolProtocolFees.sol
- pkg/pool-stable/contracts/test/MockComposableStablePool.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolProtocolFees.sol
- pkg/pool-stable/test/ComposableStablePool.test.ts
- pkg/pool-stable/test/ComposableStablePoolProtocolFees.test.ts
We could leave this code in the original functions but imo it's much cleaner to move it out into a `_beforeJoinExit` as it gets rid of the variable declaration juggling while matching what we have in `BaseWeightedPool` (although with return values).
> Avoid recalculation of invariant during joins/exits in constant amp scenario

- pvt/benchmarks/config.ts
- pvt/benchmarks/joinExit.ts
- pvt/benchmarks/misc.ts
There was another usage of 20 as the max number of tokens for weighted pools which was causing benchmarks to blow up.
> Update benchmarks to use new weighted pool limit

- pkg/pool-weighted/contracts/InvariantGrowthProtocolFees.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
In WeightedPool and ManagedPool we bypass some of the fee collection logic if the pool is paused. Due to the introduction of RecoveryMode we don't need to perform this check as all joins and exits are blocked completely while paused so we'll never enter these functions.
I've overridden `_doRecoveryModeExit` in ManagedPool to update the AUM fee collection timestamp to try to recover some of the behaviour we had before however there's a potential manager attack vector that's been opened up, they can just pause the pool to lock funds and extract AUM fees without users being able to exit. This seems fine as they can only do it for the first 90 days of the pool factory existing and so the chances of the EV of attacking outweighing trying to sustain and grow the pool is low.
> Remove unnecessary paused check in fee calculations

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
We don't have an `aumProtocolFeesCollector` anymore and the `protocolFeeProvider` isn't in the struct anymore so we can remove this.
> Remove stale comment in ManagePool

- pkg/pool-weighted/test/ManagedPool.test.ts
Hoo boy. These tests got broken by me causing fee collection to revert when the pool is paused, which I've fixed but that showed a separate issue which has been sitting around for a while.
It looks like we had managed to duplicate half of the tests at some point (I think around the time at which we added token addition/removals) so I've stripped these out. We need to do another pass on this as it's missing tests for when we're adding a token but this gets us nice green checks again.
> Fix ManagedPool AUM tests

- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
Last skipped test (that's not addressed in other PRs). Proportional exits now revert.
> Update test in BaseWeightedPool.behavior

- pkg/pool-weighted/contracts/InvariantGrowthProtocolFees.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
We're going to have to call into two separate contracts once we add yield fees so we can't just call an inherited version of `_beforeJoinExit` anymore.
To avoid duplicated mints I've changed the `_beforeJoinExit` function in `InvariantGrowthProtocolFees` to return the amount of BPT to mint rather than minting it itself.
> Pay protocol fees within WeightedPool rather than InvariantGrowthProtocolFees

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/InvariantGrowthProtocolFees.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolFactory.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/pool-weighted/test/InvariantGrowthProtocolFees.behavior.ts
Since we now have the ProtocolFeeCache providing the protocol fee percentages, we no longer want to use the value passed into joins and exits from the Vault.
I also removed the skipped tests in InvariantGrowthProtocolFees.behavior; since all joins and exits revert, these no longer make sense, at least in that file. They should be tested as part of the regular join/exit suite.
> Use ProtocolFeeCache in WeightedPool

- pkg/pool-stable/contracts/ComposableStablePoolStorage.sol
- pkg/pool-utils/contracts/BasePool.sol
It's a constant, so no danger making _MIN_TOKENS internal. This avoids redeclaring it in derived classes, and ensures consistency with BasePool.
> Reuse _MIN_TOKENS

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
This PR addresses this review comment: https://github.com/balancer-labs/balancer-v2-monorepo/pull/1636#discussion_r952936468
Made as a separate PR to avoid conflicts on that branch.
> Remove `isJoin` argument from _afterJoinExit

- pkg/pool-utils/contracts/InvariantGrowthProtocolSwapFees.sol
We we're dealing with numbers which are less than 1 here, we should divide first and then multiply to keep them as bit as possible.
> Divide before multiplying in calcDueProtocolFees

- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
- pkg/liquidity-mining/contracts/test/MockLiquidityGaugeFactory.sol
- pkg/liquidity-mining/test/BaseGaugeFactory.test.ts
- pkg/liquidity-mining/test/GaugeAdder.test.ts
This PR adds basic tests for `BaseGaugeFactory`.
Some modifications were introduced to the mock gauge / mock factory to be able to reuse them here (namely, `MockLiquidityGauge` is now an `ILiquidityGauge`).
Closes #1641.
> Base gauge factory tests

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Similar to #1639, we can remove fixed point calculations here in favour of regular maths.
> Remove fixed point operations from AUM fees maths

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
We often use the `_beforeJoinExit` to pay any due protocol fees so we'll always know the total supply and the amount of fees being minted. The pool also needs to know the supply after these fees have been paid in order to properly process the join so we  read the total supply again to pass it into the join/exit handlers.
Instead we can just have `_beforeJoinExit` return the supply to be used for the join/exit as we do in ComposableStablePool
> Return `preJoinExitSupply` from `_beforeJoinExit`

- pkg/pool-stable/contracts/StablePoolAmplification.sol
- pkg/pool-stable/contracts/test/MockComposableStablePool.sol
- pkg/pool-stable/test/ComposableStablePool.test.ts
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/BasePoolAuthorization.sol
- pvt/helpers/src/contract.ts
The issue originates in BasePool and Amplification providing the first implementation of `_isOwnerOnlyAction` in their branches of the inheritance tree, and therefore requiring manually calling all parents in the most derived child for correct behavior (which is rather fragile).
I changed things so that we have a default implementation, making all contracts have a parent impl, and allowing to always call `super`, which fixes the issue in a less error-prone way.
This is being merged into the `composable-stable-deployment` branch, which is at the commit where ComposableStablePoolFactory was compiled and deployed, to make it easier to reason about the diff.
> Fix BasePool permissioned function owner only state not being used

- pkg/deployments/tasks/20220609-stable-pool-v2/test/task.fork.ts
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockYieldProtocolFees.sol
- pkg/pool-weighted/test/JoinExitProtocolFees.test.ts
- pkg/pool-weighted/test/WeightedPoolProtocolFees.behavior.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
I've had to make `_lastPostJoinExitInvariant` internal so that the mock contract can expose it but I don't think there's any way around that.
> Make _getJoinExitProtocolFees update _lastPostJoinExitInvariant automatically

- pkg/interfaces/contracts/pool-utils/IControlledManagedPool.sol
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/controllers/ManagedPoolController.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Addressing https://github.com/balancer-labs/balancer-v2-monorepo/pull/1667#issuecomment-1230353575.
Currently we aren't enforcing that Pools implement the interface that the `ManagedPoolController` uses to interact with the pool. which could lead to disastrous consequences in future if the Pool interface changes and we don't update the Controller to match. There's been a little bit of this already as the interface expects a `withdrawCollectedManagementFees` function on the pool (a leftover from the `InvestmentPool` days.)
I've removed how `ManagedPoolController` implements the `IControlledManagedPool` interface for the time being as it doesn't 100% line up with how we're handling management fees currently.
> Enforce controlled pool interface on pools

- pkg/pool-stable/contracts/ComposableStablePoolProtocolFees.sol
- pkg/pool-utils/contracts/InvariantGrowthProtocolSwapFees.sol
- pkg/pool-utils/contracts/protocol-fees/InvariantGrowthProtocolSwapFees.sol
- pkg/pool-utils/contracts/protocol-fees/ProtocolFeeCache.sol
- pkg/pool-utils/contracts/protocol-fees/ProtocolFees.sol
- pkg/pool-utils/contracts/test/MockInvariantGrowthProtocolSwapFees.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockProtocolFees.sol
- pkg/pool-utils/test/ProtocolFees.test.ts
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
This PR started as refactoring the logic in `_calculateAdjustedProtocolFeeAmount ` so that's it's in the `InvariantGrowthProtocolSwapFees` library in a reusable way.
I wasn't a huge fan of this as it results in us using the `InvariantGrowthProtocolSwapFees` library for non-swap fees so I moved this into a generic `ProtocolFees` library, at which point it made sense to make a directory in `pool-utils` specific to protocol fees.
> Move the "bptForPoolPercentage" logic into a library.

- pkg/pool-utils/contracts/protocol-fees/InvariantGrowthProtocolSwapFees.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/pool-weighted/test/PostJoinExitProtocolFees.test.ts
This PR starts trying to improve code reuse by changing the functions in `WeightedPoolProtocolFees` to start returning fractions of the pool rather than raw BPT amounts. This means that we can use these functions directly in `getRate`.
The non-view nature of `_getYieldProtocolFeesPoolPercentage` causes a couple troubles here but I can fix this later.
> Start refactoring weighted `getRate`

- pkg/standalone-utils/contracts/relayer/BaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/IBaseRelayerLibrary.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
Closes #1509.
This PR adds a public `peek` method in `BaseRelayerLibrary` that returns the value of a chained reference without modifying it.
> [Batch Relayer V4] [2] Public 'peek' for chained references

- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/pool-weighted/test/WeightedPoolProtocolFees.behavior.ts
- pkg/pool-weighted/test/YieldProtocolFees.test.ts
- pvt/helpers/src/models/types/TypesConverter.ts
This PR aims to help #1678 by making `_getYieldProtocolFee` a view function. We can then make use of it in the `getRate` function without rewriting the same logic again.
> Switch yield protocol fees to use a view function

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/WeightedPool.test.ts
- pvt/helpers/src/models/pools/base/BasePool.ts
BasePool now has a `_onDisableRecoveryMode()` hook which allows pools to take any actions they need to do to reset their state after recovery mode is disabled. Draft while adding tests.
> Perform cleanup operations after disabling recovery mode

- pkg/pool-stable/contracts/ComposableStablePool.sol
- pkg/pool-stable/test/ComposableStablePool.test.ts
- pkg/pool-stable/test/ComposableStablePoolIntegration.test.ts
- pkg/pool-utils/contracts/ProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/pool-utils/test/ProtocolFeeCache.test.ts
I believe this is what needs to be done to safely update the protocol fee cahce. In its current form the code goes over the bytecode size, but there's some simple refactors that can be introduced (`getRate` and this new hook share a lot of their code). I intend to do that separetly, once all new changes have been introduced.
> Pay protocol fees on cache update

- pkg/pool-stable/contracts/ComposableStablePoolProtocolFees.sol
Not quite sure what we were thinking with the lack of SafeMath here :shrug:
> Prevent invariant overflow

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/optimism/action-ids.json
`npx hardhat save-action-ids --id stable-pool-v2 --network arbitrum --name StablePool --address 0x5ac311fb06c3bd30c87b4e13c079d17c94325ddd`
`npx hardhat save-action-ids --id stable-pool-v2 --network optimism --name StablePool --address 0x373643b17cd80e37675c8c98ef774efe6ca0b4de`
> Add StablePoolV2 action-ids (Arbitrum/Optimism)

- pkg/standalone-utils/contracts/test/MockBaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/test/MockBatchRelayerLibrary.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
Closes #1693.
`peek` already has tests under several conditions (e.g. after a `get`, peeking multiple times, etc). A simple smoke test within a `multicall` should be enough.
> Test: peekChainedReferenceValue multicall

- pkg/distributors/hardhat.config.ts
- pkg/distributors/package.json
- pkg/governance-scripts/hardhat.config.ts
- pkg/governance-scripts/package.json
- pkg/interfaces/hardhat.config.ts
- pkg/interfaces/package.json
- pkg/liquidity-mining/hardhat.config.ts
- pkg/liquidity-mining/package.json
- pkg/pool-linear/hardhat.config.ts
- pkg/pool-linear/package.json
- pkg/pool-stable/contracts/test/MockComposableStablePool.sol
- pkg/pool-stable/hardhat.config.ts
- pkg/pool-stable/package.json
- pkg/pool-utils/hardhat.config.ts
- pkg/pool-utils/package.json
- pkg/solidity-utils/contracts/openzeppelin/EIP712.sol
- pkg/solidity-utils/hardhat.config.ts
- pkg/solidity-utils/package.json
- pkg/standalone-utils/hardhat.config.ts
- pkg/standalone-utils/package.json
- pkg/vault/hardhat.config.ts
- pkg/vault/package.json
- yarn.lock
This uses the [`hardhat-ignore-warnings`](https://github.com/frangio/hardhat-ignore-warnings) plugin to ignore certain solidity warnings we're not interested in, like mocks going above bytecode size.
> Ignore solc warnings

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
This shouldn't be here as it's replaced by `_onDisableRecoveryMode` but probably go resurrected in a merge conflict somewhere.
> Remove unnecessary override of _doRecoveryModeExit

- pkg/liquidity-mining/contracts/test/MockBalancerTokenAdmin.sol
- pkg/liquidity-mining/contracts/test/MockVeDelegation.sol
- pkg/standalone-utils/test/GaugeActions.test.ts
- pvt/helpers/src/test/relativeError.ts
This PR adds unit tests for `GaugeActions`; closes #1148 .
Some notes:
We will only care about token movements between sender, recipient and a staking liquidity gauge; `veBAL` calculations are out of scope. Therefore, we can use actual liquidity gauges and mock the `VeDelegation` when setting up the test. 
The tests call the methods under several conditions, which increases the test complexity a bit:
- Multiple amounts withdraw / deposit (within and outside allowed range).
- Immediate values and chained references.
- Using sender as recipient. and using other as recipient.
Each of those conditions open a new context and go down one level in the call stack, but hopefully it's easy enough to follow.
These are more straightforward, since `GaugeActions` mostly forwards the calls. Again, …
> Gauge Actions test

- pkg/pool-weighted/contracts/lib/GradualValueChange.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolTokenLib.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolTokenLib.sol
- pkg/pool-weighted/test/ManagedPoolTokenLib.test.ts
- pkg/pool-weighted/test/WeightedPool.test.ts
This PR adds `ManagedPoolTokenLib` which handles all data operations to do with the `_tokenState` mapping, i.e. it encapsulates token scaling factors and weights. As the data layout is the same as current, I've modified ManagedPool to make use of this new library.
> Add library for managing information on ManagedPool tokens

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/lib/PoolRegistrationLib.sol
- pkg/pool-utils/contracts/test/MockPoolRegistrationLib.sol
- pkg/pool-utils/test/BasePool.test.ts
- pkg/pool-utils/test/PoolRegistrationLib.test.ts
Another step towards reducing of BasePool code which avoids us having to perform these checks in each pool type once BasePool is gone.
> Move pool registration code into a simple lib

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BaseMinimalSwapInfoPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
- pkg/pool-weighted/contracts/managed/vendor/BaseWeightedPool.sol
This copies `BasePool`, `BaseMinimalSwapInfoPool` and `BaseWeightedPool` into the `managed/vendor` directory so `ManagedPool` has it's own copy for us to tear up.
> Vendor BasePool for ManagedPool

- pkg/pool-utils/contracts/protocol-fees/ProtocolAUMFees.sol
- pkg/pool-utils/contracts/test/MockProtocolAUMFees.sol
- pkg/pool-utils/test/ProtocolAUMFees.test.ts
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
Builds on #1736 
This PR moves the AUM fee calculation into a simple library so that `_collectAUMFeeCalculation` only shows logic relevant for the pool (i.e. updating state and distributing fees).
> Move AUM fee calculation into a library

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
This PR lays some of the groundwork for #1748 as removing the limitations on setting the upper bits is required for that PR.
~~There's an easter egg related to `endSwapFeePercentage` that I noticed while making this PR.~~ Misread stuff so this isn't an issue.
> Remove protections on upper bits of `_miscData` and inline `_setSwapFeePercentage`

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
Draft as I want to be sure of test coverage before we merge this.
This PR does away with `_miscData` and replaces it with `_poolState` which is managed by `ManagedPoolStorageLib`. Any usage of `_miscData` has been replaced with the appropriate getter/setter from `ManagedPoolStorageLib`
`BasePool._setSwapFeePercentage` has been inlined into `ManagedPool._setSwapFeePercentage` but I'll replicate this change on master as well.
> ManagedPoolStorageLib integration

- .github/workflows/benchmarks.yml
- pkg/standalone-utils/contracts/test/MockBaseRelayerLibrary.sol
- pvt/benchmarks/package.json
- pvt/benchmarks/relayer.ts
Closes #936.
Gas usage depends on the amount of bytes returned by the delegate call. Some measurements below:
- Gas for input size 0: 30.3k
- Gas for input size 256: 36.3k
- Average gas per call (inputs from length 0 to length 256): 33.5k
For this test, relayer's `multicall` was compiled without considering return values:
```
function multicall(bytes[] calldata data) external payable override nonReentrant {
for (uint256 i = 0; i < data.length; i++) {
_library.functionDelegateCall(data[i]);
}
_refundETH();
}
```
The results were:
- Gas for input size 0: 29.5k
- Gas for input size 256: 34.9k
- Average gas per call (inputs from length 0 to length 256): 32.3k
Removing the return values saves at least ~800 gas for a call; the amount grows larger with the size of the returned data. Probably not …
> Adding benchmark for relayer multicall

- pkg/standalone-utils/contracts/relayer/BaseRelayerLibrary.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
> [Batch Relayer V4] Using same storage slot for read-only and chained refs

- pkg/pool-weighted/contracts/lib/GradualValueChange.sol
Noticed this while mucking around with fuzz tests on the foundry branch. Drops gas cost by 23.
> Avoid double zero duration check in `calculateValueChangeProgress`

- pvt/helpers/src/constants.ts
We can't import hardhat at the top level for this module, because we use it in places were hardhat hasn't loaded yet.
> Fix deployments package

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
It makes no sense for `_poolState` to live in `BasePool` as it's so strongly intertwined with ManagedPool. This results in us needing fudges like `_getPoolState` and `_setPoolState`.
This PR pulls `_poolState` up into `ManagedPool` so we can get rid of `_getPoolState` and `_setPoolState`. BasePool then just defines virtual getters for the fields it needs.
> Pull _poolState up into ManagedPool

- .github/workflows/ci.yml
- README.md
This should fix Forge tests issues in CI.
> Recursive submodules ci

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
The ordering of functions in ManagedPool is bit all over the place. I've rearranged them so functions on a theme sit together which will make it easier to break things off.
> Rearrange functions in ManagedPool

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
We've got a couple of stragglers which should have been gotten rid of when we added `ManagedPoolSwapFeesLib`
> Remove unused constants from ManagedPool

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
In these cases we need `_poolState` anyway so we can save a read by inlining.
> Inline `getSwapEnabled()` inside swap hooks

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
This avoids the issue we identified a while back where a Pool owner can manipulate `_denormWeightSum` by manipulating the weights in combination with adding or removing tokens
> Automatically renormalize on gradual weight changes

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
`_startGradualSwapFeeChange` returns the updated pool state whereas `_startGradualWeightChange` writes it to storage directly. If we are to create another library (`ManagedPoolWeightsLib.sol`) then we need to make this change.
> Update `_startGradualWeightChange` to return updated pool state

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
There's a number of orphaned imports due to us packaging various functionality away.
> Remove unused imports

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
We actually do length checking of the `balances` array when upscaling so this check is unnecessary.
> Remove `_getTotalTokens` internal getter

- pkg/pool-weighted/contracts/lib/ValueCompression.sol
- pkg/pool-weighted/test/foundry/ValueCompression.t.sol
I'm intending this to be used in cases where we're testing libraries which store and read compressed values such as `ManagedPoolTokenLib` or `ManagedPoolCircuitBreakerLib.sol`.
> Expose getter for expected compression error on ValueCompression.sol

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/pool-weighted/WeightedPoolUserData.sol
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/managed/AddRemove.test.ts
- pkg/pool-weighted/test/managed/ownerOnlyActions.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/vault/Vault.ts
The refactor is relatively simply, since we're just removing stuff. I also adjusted the tests (best reviewed ignoring whitespace changes).
I ended up disallowing add/remove while uninitialized for simplicity. Am considering also disallowing burning from the zero address, so that the no re-init invariant is kept.
I had to remove a test about remove token collecting fees (which I imagine it did because it used to be an exit?). At any rate, we can review add/remove and fee interations later.
> Refactor remove token

- pkg/pool-weighted/contracts/WeightedMath.sol
This line bakes in an assumption that the sum of all the normalized weights sums to exactly `FixedPoint.ONE` (as this enforces that `invariantRatioWithFees >=FixedPoint.ONE`).
When handling renormalized weights, this is no longer a given so we should gracefully handle this case.
> Don't assume that invariantRatioWithFees >= FixedPoint.ONE

- pkg/pool-weighted/contracts/WeightedMath.sol
The underflow is prevented by the previous line.
> Remove unnecessary safemath

- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
Includes changes in #1820, #1819, #1818
> Add single token version of `_calcBptOutGivenExactTokensIn`

- pkg/balancer-js/src/types.ts
- pkg/pool-weighted/contracts/test/MockBasePool.sol
- pkg/pool-weighted/test/managed/BasePool.test.ts
- pvt/helpers/src/test/relativeError.ts
Summary of differences with respect to weighted base pool:
- Swap fee tests removed.
- Recovery mode enable / disable tests removed.
- Joins and exits in recovery mode are preserved.
- Small tweaks to join / exit tests to consider relevant parameters instead of protocol fee.
- Using sender / recipient abstractions.
- `beforeSwapJoinExit` tests removed.
- misc data tests removed.
> (Managed) Base pool test

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
- pkg/pool-weighted/contracts/test/MockBasePool.sol
We don't use any of these values (nor will we), so there's no point in passing them around.
> Remove unused BasePool args

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
In preparation for making ManagedPool composable, we now wrap the `vault.getPoolTokens` function call in something which we can override to implement composable logic while `ManagedPoolSettings` remains unaware of it.
> Wrap Vault.getPoolToken in a virtual internal function

- pkg/pool-weighted/contracts/lib/GradualValueChange.sol
I've flipped the order of early returns in `interpolateValue` as the most common situation is that the current weight change will be completed rather than scheduled for the future.
```
-if (pctProgress == 0 || startValue == endValue) return startValue;
-if (pctProgress >= FixedPoint.ONE) return endValue;
+if (pctProgress >= FixedPoint.ONE || startValue == endValue) return endValue;
+if (pctProgress == 0) return startValue;
```
I've also inlined all the usages of `currentTime`.
> Small optimisations in GradualValueChange

- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/test/BasePool.test.ts
Ensure the pool is in the opposite state before enabling or disabling Recovery Mode.
Done both ways, for consistency and future-proofing, though enabling it twice shouldn't hurt anything.
> Recovery Mode consistency

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
- pkg/pool-weighted/contracts/test/MockBasePool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/managed/BasePool.test.ts
This allows us to modify how we register the pool (e.g. depending on whether the pool is composable or not) without BasePool having to know anything about this.
> Refactor pool registration so that it happens on outermost layer

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
`_onSwapMinimal` is now the dispatch function for whether we're performing a "joinSwap", "exitSwap" or a "tokenSwap". As BPT doesn't have a scaling factor the responsibility for upscaling tokens appropriately has been pushed into the `_onJoinSwap`, `_onExitSwap` and `_onTokenSwap` functions.
> Add groundwork for composable swaps

- pkg/pool-weighted/contracts/managed/BaseManagedPoolFactory.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/BaseManagedPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
Leaving it alone in contracts that are literally called PoolController, but deprecate the term in the main ManagedPool docs, in favor of "owner".
> Rename controller to owner in ManagedPool

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolTokenLib.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolTokenLib.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/foundry/ManagedPoolStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolTokenLib.t.sol
- pkg/pool-weighted/test/managed/AddRemove.test.ts
This is a bit of a big change - I didn't find a way to perform this in simpler stages.
All notion of normalization is removed - all tokens are instead always normalized. We drop the normalized sum and compression entirely. This also results in less rounding errors.
There's a few things missing, namely:
- tests for aum fee collection
- forbid adding self
- forbid removing self
- make tests on new weights more strict (I think we potentially reduce the expected relative error)
> Make weights normalized

- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
We no longer have a management swap fee and DELEGATE_OWNER lives in constants
> Update some stale helpers in tests

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
When ManagedPool is composable then we'll need to pass in the virtual supply rather than calling `totalSupply()`. To smooth this transition we can pass in the total supply prior to the switch.
> Pass `virtualSupply` to `_beforeJoinExit`

- pkg/pool-utils/contracts/lib/PoolRegistrationLib.sol
- pkg/pool-utils/contracts/test/MockPoolRegistrationLib.sol
- pkg/pool-utils/test/PoolRegistrationLib.test.ts
- pkg/pool-utils/test/foundry/PoolRegistrationLib.t.sol
We ensure that the BPT is placed in the first position to ensure that it remains at a constant index.
> Add composable pool registration to PoolRegistrationLib

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
This PR adds a basic implementation of `getActualSupply` for ManagedPool and the associated tests to make it easier to make ManagedPool composable in future.
> Add getters for the ManagedPool's actualSupply

- pkg/pool-weighted/test/managed/AddRemove.test.ts
- pvt/helpers/src/models/pools/stable/StablePool.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
This PR updates the ManagedPool tests so that they're more friendly to making ManagedPool composable. Essentially we're making the WeightedPool model query the pool's tokens before joins/exits and testing transitions rather than expected final states (as we should anyway) so we can hook in the composable logic more easily.
> Add some groundwork for composable tests

- pkg/pool-weighted/test/foundry/DropBptFromArray.t.sol
This PR adds fuzz tests for the inplace array shortening trick with assembly. We're likely going to be inlining this assembly block where necessary so I haven't broken it out into a library for now.
> Add fuzz tests for in place array BPT dropping

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
We don't have a management swap fee anymore so this should have been removed.
> Remove obsolete constant

- pkg/pool-weighted/contracts/test/MockManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pvt/helpers/src/models/pools/base/BasePool.ts
To make the `ManagedPool/ManagedPoolSettings` tests agnostic to whether the pool is composable or not we should replace any references to the total supply in the tests with virtual supply.
> Replace references to total supply in tests with virtual supply

- pkg/pool-utils/contracts/lib/ComposablePoolLib.sol
- pkg/pool-utils/test/foundry/ComposablePoolLib.t.sol
This PR encapsulates some of the standard array manipulation needed for composable pools in a library.
> Add ComposablePoolLib

- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
Builds on #1834
I've made a few changes to how we lay out the tests.
- Flattened the test structure so we're not testing the calculation of BPT prices inside a `when the sender is the owner` context, etc.
- Added testing for setting circuit breakers in a delegated ownership context (granted I don't expect any delegated ownership Managed Pools)
- Moved the tests out of the `permissioned actions` block as this is extremely broad and shouldn't exist at all imo.
> Circuit breaker tests refactor

- pkg/pool-weighted/contracts/lib/WeightedExitsLib.sol
- pkg/pool-weighted/contracts/lib/WeightedJoinsLib.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolTokenLib.sol
Builds on #1883 
```
yarn hardhat compile && cat artifacts/contracts/managed/ManagedPool.sol/ManagedPool.json | jq -r '.deployedBytecode' | wc --chars | awk '{print (($1-2)/2)}'
```
goes from `29397.5` to `29351.5`
> Reduce bytecode through solidity silliness

- pkg/pool-weighted/test/foundry/CircuitBreakerLib.t.sol
This fixes a flaky fuzz tests (which will likely be picked up by https://github.com/balancer-labs/balancer-v2-monorepo/pull/1878).
The origin of the issue is that `assertApproxEqRel` expects exact equality when the maximum relative error is less than one (i.e. cannot be represented as an integer), and due to strict rounding we end up having off-by-one error. By changing how this assertion works, I managed to actually _reduce_ the maximum relative error, which was unnecessarily high to catch these off-by-ones.
I'm not sure where the overridden version should live, so for now I just left it next to the test.
> Fix circuit breaker lib failing test

- pkg/pool-utils/contracts/external-fees/ProtocolFeeCache.sol
- pkg/pool-utils/test/ProtocolFeeCache.test.ts
This PR replaces structs with bytes32 + word codec in protocol fee cache.
`yarn hardhat compile && cat artifacts/contracts/managed/ManagedPool.sol/ManagedPool.json | jq -r '.deployedBytecode' | wc --chars | awk '{print (($1-2)/2)}'` prints 29262,5 in master and 28815,5 with this change.
Savings: 447.
> Bytecode improvement: ProtocolFeeCache structs

- pkg/pool-weighted/test/foundry/WeightedMathRounding.t.sol
These tests check that there's no profit in reversing a swap, regardless of the combination of given in and given out functions. Note that this does not include any swap fees: it's all due to choosing the correct rounding direction.
> Add swap rounding fuzz tests

- pkg/pool-utils/test/ManagedPoolController.test.ts
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolAumStorageLib.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolSettings.sol
- pkg/pool-weighted/test/BaseManagedPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/foundry/ManagedPoolAumStorageLib.t.sol
- pkg/pool-weighted/test/managed/AddRemove.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
Builds on #1890 
This PR merges the getters for the AUM fee percentage and timestamp while packing the two values in storage. For bytecode reasons I've introduced (another!) library for managing this state vs using a struct.
> Merge AUM fee getters

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
A manager might conceivably want to edit the set of LPs while it is disabled. It seems like an arbitrary restriction to not allow this.
Unaddressed list: "make allowlist api more flex"
> Make ManagedPool LP allowlist more flexible

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
Technically a noop change but we now use the actual token initialisation function in the `ManagedPoolSettings` constructor.
> Use `initializeTokenState` method in constructor

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolSettings.sol
Make virtual supply and token/balance getters pure virtual in ManagedPoolSettings; dangerous if not overridden.
Unaddressed things: "no default impls (virt supp)" and "get pool tokens no impl"
> Pure virtuals in ManagedPoolSettings

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
This reduces bytecode by ~100 bytes as we only compute the hash once
> Reduce storage accesses

- pvt/helpers/src/models/types/TypesConverter.ts
The varyDecimals flag creates a TokenList where each token has a different value for decimals, which helps catch bugs related to assuming 18-decimals (e.g., scaling issues). It starts at 18, then goes to 17, 16, 15, ...
Starting at 18 is actually not ideal, since tests often look at the first token, which will be 18, defeating the purpose of varyDecimals. Since simply reverse it so that it starts at 0 and goes up.
> Reverse varyDecimals

- pkg/pool-utils/contracts/test/MockVault.sol
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
Small fix so that `protocolFeeAmounts` can be used with both mock and regular vaults in testing.
> Fix: match MockVault `PoolBalanceChanged` event with `IVault` event.

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/managed/AddRemove.test.ts
- pvt/benchmarks/config.ts
- pvt/benchmarks/multihop.ts
- pvt/benchmarks/singlePair.ts
One thing I realized giving this a last once-over is that the max token value (38) is completely arbitrary. It arose from gas limits on joins/exits in a very old version, and we just never changed it. It used to be 50 (got reduced because of the aforementioned gas issues). Looks like it once again works with 50.
> Increase max tokens

- pkg/deployments/CHANGELOG.md
- pkg/deployments/package.json
- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/package.json
These don't have any dependencies, so they are the easiest to release.
> Update npm packages

- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
See #1931.
This PR adds a recovery mode context for each regular operation, and one extra section to check the actual recovery mode exit.
Closes #1931
> Add recovery mode tests for `BaseWeightedPool`

- README.md
I noticed this is missing, we only mention the bounty program.
> Add security email to readme

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
Drop UNHANDLED_BY_ errors messages (currently only used in LinearPool) in favor of using UNIMPLEMENTED everywhere.
> Deprecate UNHANDLED_BY_ errors

- pkg/interfaces/contracts/liquidity-mining/IGaugeAdder.sol
- pkg/liquidity-mining/contracts/admin/ChildChainGaugeTokenAdder.sol
- pkg/liquidity-mining/contracts/admin/GaugeAdder.sol
- pkg/liquidity-mining/contracts/gauges/L2GaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/test/MockAuthorizerAdaptorEntrypoint.sol
- pkg/liquidity-mining/test/ChildChainGaugeTokenAdder.test.ts
- pkg/liquidity-mining/test/GaugeAdder.test.ts
- pkg/liquidity-mining/test/L2GaugeCheckpointer.test.ts
On top of #1981, this PR fixes tests and code for `L2GaugeCheckpointer`, `GaugeAdder` and `ChildChainGaugeTokenAdder`.
Calls to `performAction` now use the entrypoint, and contracts that relied on the adaptor to make such calls were modified to use the entrypoint instead.
This should be reviewed and merged into `entrypoint-helpers` before it goes to `master` as part of the adaptor entrypoint revamp.
> Entrypoint helpers: liquidity mining partial fixes

- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPool.sol
We're using raw literals here rather than the named constants which is quite risky. This PR fixes this to always use the constants.
> Use constants rather than literals in poolState decoding

- pvt/helpers/src/models/vault/VaultDeployer.ts
Small refactor on top of `entrypoint-helpers`, to be included before it's merged.
Reference: https://github.com/balancer-labs/balancer-v2-monorepo/pull/1981#discussion_r1014194876.
> Change `VaultDeployer` to use alternative authorizer sequence.

- pkg/deployments/tasks/20220527-child-chain-gauge-token-adder/input.ts
- pkg/deployments/tasks/20220530-preseeded-voting-escrow-delegation/input.ts
Small fix for `check-addresses`: using incomplete task names may cause collisions with future deployment tasks (e.g. `authorizer-adaptor` collides with the new `20221111-authorizer-adaptor-entrypoint`). 
These collisions make `check-addresses` fail: https://github.com/balancer-labs/balancer-v2-monorepo/actions/runs/3423708703/jobs/5702610820
N/A, but needed for CI to pass in #1991.
> Use complete task names in deployment scripts to avoid collisions.

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/liquidity-mining/contracts/admin/AuthorizerAdaptor.sol
- pkg/liquidity-mining/contracts/admin/AuthorizerAdaptorEntrypoint.sol
- pkg/liquidity-mining/test/AuthorizerAdaptorEntrypoint.test.ts
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
This goes into much more detail as to what the issue is and how the fix works in all components involved, so that a reader that stumbles on any of them will get sufficient context to understand the full picture.
> Improve AuthorizerAdaptorEntrypoint docs

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-linear/contracts/aave/AaveLinearPool.sol
- pkg/pool-linear/contracts/test/MockAaveLendingPool.sol
- pkg/pool-linear/contracts/test/MockStaticAToken.sol
- pkg/pool-linear/test/AaveLinearPool.test.ts
- pkg/pool-linear/test/AaveLinearPoolFactory.test.ts
- pkg/pool-utils/contracts/lib/ExternalCallLib.sol
- pkg/pool-utils/contracts/test/MaliciousQueryReverter.sol
- pkg/pool-utils/contracts/test/MockExternalCaller.sol
- pkg/pool-utils/test/ExternalCallLib.test.ts
This PR introduces the `ExternalCallLib` which exposes a function to check if revert data from external calls will be picked up by BasePool's `_queryAction` function.
~~Note that this currently doesn't fix the issue described in #1973. We must also protect the error signature used by `queryBatchSwap` as well do to this. Currently we only protect joins and exits but not swaps.~~ Fixed now.
We should also include a test of this protection when used within a pool.
closes #1973
> Add ExternalCallLib which checks revert data for malicious data

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/contracts/pool-utils/IRateProviderPool.sol
- pkg/pool-stable/contracts/ComposableStablePoolStorage.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
I pulled `getRateProviders()` into an interface to standardize how this value is returned. This is a requirement for the automatic recovery mode project.
> Add IRateProviderPool

- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPool.sol
- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPoolSettings.sol
This PR reduces the number of warm reads + redundant computation we perform in LBP swaps by passing around explicit state similar to how we do in ManagedPool
Builds on #2015 
N/A
> LBP explicit state refactor

- pkg/deployments/tasks/20221123-pool-recovery-helper/test/test.fork.ts
`vault` is unused and this makes the linter mad.
> Remove unnecessary variable

- pkg/interfaces/contracts/pool-utils/IPoolVersion.sol
- pkg/interfaces/contracts/pool-utils/IVersion.sol
- pkg/interfaces/contracts/pool-utils/IVersionProvider.sol
- pkg/pool-linear/contracts/aave/AaveLinearPool.sol
- pkg/pool-linear/contracts/aave/AaveLinearPoolFactory.sol
- pkg/pool-linear/test/AaveLinearPool.test.ts
- pkg/pool-linear/test/AaveLinearPoolFactory.test.ts
- pkg/pool-utils/contracts/Version.sol
This PR adds an `version` getter for `AaveLinearPool` and `AaveLinearPoolFactory` (factory provides created pools with the actual version string).
Eventually the interface will apply to `BasePoolFactory` and `Version` to `BasePool` and `NewBasePool`. Since that change would require some refactoring across the codebase we're starting with this one since it's more urgent.
See #2026 (this one shall be closed when this feature is implemented in every pool).
> Aave linear pool versioning

- pkg/deployments/CHANGELOG.md
- pkg/deployments/README.md
- pkg/deployments/index.ts
- pkg/deployments/src/network.ts
- pkg/deployments/src/task.ts
We've got a number of helper functions in the `v2-deployments` package as async whereas the implementations are sync. We can then simplify usage of these functions by marking them as sync.
> Make unnecessarily async functions sync

- pkg/deployments/index.ts
We no longer support the listed networks so I've replaced them with networks we do support.
> Remove deprecated networks from jsdoc

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/contracts/pool-utils/IFactoryCreatedPoolVersion.sol
- pkg/pool-linear/contracts/aave/AaveLinearPoolFactory.sol
Interface rename and changelog update.
N/A
> Rename IPoolVersion --> IFactoryCreatedPoolVersion.

- pkg/liquidity-mining/contracts/admin/AuthorizerAdaptorEntrypoint.sol
- pkg/liquidity-mining/test/AuthorizerAdaptorEntrypoint.test.ts
Add event to `performAction` in adaptor entrypoint.
Closes #1809.
> Adaptor entrypoint events

- pkg/deployments/action-ids/goerli/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
This doesn't add all missing action ids. Some networks only have the factory deployed and no pools have been created.
> Add missing action-ids

- pkg/standalone-utils/contracts/relayer/BaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/IBaseRelayerLibrary.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
Makes `approveVault` payable in `BaseRelayerLibrary`.
I've inspected the remaining public / external non-view functions in `BatchRelayerLibrary` and they are all payable.
Since we don't have slither yet, we could add tests that check that sending value to those functions doesn't revert, although it's not always straightforward when there are permissions involved. Feedback on this point is welcome; adding a simple test as reference.
Closes #1940.
> Make `approveVault` payable

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/contracts/pool-utils/IRecoveryModeHelper.sol
- pkg/pool-utils/contracts/RecoveryModeHelper.sol
- pkg/pool-utils/test/RecoveryModeHelper.test.ts
- pvt/helpers/src/models/vault/Vault.ts
This introduces an external helper contract that can be used to compute recovery mode exits. Unlike all exits we've had so far, it uses the 'cash' balance of the Pool exclusively. By placing this code outside of the Pool, we can reduce its bytecode size.
This initial version only works with Composable Pools, but it's easily extendable to also work with regular Pools. On a later PR I'll modify ManagedPool so that it uses this helper.
Part of #2042
> Introduce RecoveryModeHelper

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/pool-utils/IManagedPool.sol
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-utils/contracts/controllers/ManagedPoolController.sol
- pkg/pool-utils/test/ManagedPoolController.test.ts
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolStorageLib.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/foundry/ManagedPoolStorageLib.t.sol
- pkg/pool-weighted/test/managed/AddRemove.test.ts
- pkg/pool-weighted/test/managed/ownerOnlyActions.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/pools/weighted/types.ts
Adds a flag analogous to the swap enabled flag, but for joins and exits.
Recovery mode exits cannot be disabled with this feature.
Tests pending; opening PR for early feedback.
Closes #2043.
> Add flag to enable / disable joins and exits in `ManagedPool`.

- pkg/pool-weighted/contracts/managed/ControlledManagedPoolFactory.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolFactory.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/test/MockManagedPool.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolSettings.sol
- pkg/pool-weighted/test/ControlledManagedPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/managed/ownerOnlyActions.test.ts
- pvt/benchmarks/misc.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
- pvt/helpers/src/models/pools/weighted/types.ts
This modifies the constructor of ManagedPool and ManagedPoolSettings so that there's more structs and fewer variables, reducing stack pressure and allowing us to add more constructor parameters.
We now have three structs:
- one for Settings params
- one for factory-provided params (e.g. the Vault, the WeightedMath contract, the pause durations, etc)
- one for non-settings user-provided params (e.g. name)
This means the factory can create its params while the user provides the other two structs. The owner is standalone since the factory will likely create the owner, so we don't want to put it in the structs.
We could alternatively have the factory have its own structs, decoupled from the Pool's (which makes a lot of sense), but that was a bigger change.
----
This was much more painful than …
> Refactor ManagedPool constructor arguments

- pkg/deployments/index.ts
- pkg/deployments/package.json
I'm not sure why we were using the ethers object provided by hardhat here. I've changed it to use vanilla ethers and changed the peer dependency to just be for `ethersproject/contracts`. I've set it to be anything from v5 to be permissive to whatever the user has installed.
> Remove usage of hardhat in deployments package to create a contract object

- pkg/deployments/tasks/deprecated/20221021-managed-pool/test/task.fork.ts
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolStorageLib.sol
- pkg/pool-weighted/test/LiquidityBootstrappingPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pkg/pool-weighted/test/foundry/LiquidityBootstrappingPoolStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolStorageLib.t.sol
This is just a readability improvement for consistency between `ManagedPoolSettings` and `ManagedPoolStorageLib` function names.
Closes #2071.
> Refactor flag getters / setters in managed pool contracts

- pkg/deployments/package.json
This PR updates the config so that the `dist/src` directory is not included in `package.tgz`
I'd recommend testing this by running `yarn build` and then `yarn pack` in the deployments package. You can then open up the tar to check that everything that we would expect to be in the package is in there.
> Remove `src` directory from being included in `deployments` NPM package

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
We now use the authorizer adaptor as the admin for the gauges rather than querying the factory. We also expose a getter for the authorizer adaptor.
> Replace gauge manager with authorizer adaptor

- pkg/liquidity-mining/contracts/BoostV2.vy
- pkg/liquidity-mining/test/BoostV2.test.ts
Needing to know the blockhash for the block prior to when we deployed the veboost contract is a bit crazy so I've removed it. I've also exposed a getter for the version field so we can pull this from onchain.
> Remove salt from veboost domain separator and expose version

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/goerli/action-ids.json
- pkg/deployments/action-ids/optimism/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
It seems we forgot to create these when the factories were deployed, and we now need them to disable them.
> Add missing managed factory action IDs

- pkg/pool-utils/test/foundry/BasePoolMath.t.sol
- pkg/pool-utils/test/foundry/ComposablePoolLib.t.sol
- pkg/pool-utils/test/foundry/ExternalFees.t.sol
- pkg/pool-utils/test/foundry/PoolRegistrationLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolAumStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolTokenStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ValueCompression.t.sol
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
- pkg/pool-weighted/test/foundry/WeightedMathJoinExitRounding.t.sol
- pkg/pool-weighted/test/foundry/WeightedMathSwapRounding.t.sol
- pkg/solidity-utils/test/foundry/FixedPoint.t.sol
- pkg/solidity-utils/test/foundry/InputHelpers.t.sol
- pkg/solidity-utils/test/foundry/Math.t.sol
- pkg/solidity-utils/test/foundry/WordCodec.t.sol
Pulling out the first commit from #2010 as we shouldn't be using the v1 abi encoder and this should hopefully ensure that we don't going forwards.
> Always use abi encoder v2 in fuzz tests

- pkg/pool-weighted/test/foundry/ValueCompression.t.sol
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
Cherrypick [b9fa955](https://github.com/balancer-labs/balancer-v2-monorepo/pull/2010/commits/b9fa9550734e99a91c42cded050d13eb095cd972) and [75fa541](https://github.com/balancer-labs/balancer-v2-monorepo/pull/2010/commits/75fa541d043460ccc7e34ae7f25d779139caeb66) from #2010 so we're fully compatible with `forge-std v1.0.0` for once the issue is fixed on their end.
> Increase usage of bound over vm.assume

- pkg/pool-linear/contracts/aave/AaveLinearPoolFactory.sol
This should make it easier to find pools for a given protocol.
> Make Aave factory protocol id argument indexed

- pkg/interfaces/contracts/standalone-utils/IProtocolFeeSplitter.sol
- pkg/standalone-utils/contracts/ProtocolFeeSplitter.sol
- pkg/standalone-utils/test/ProtocolFeeSplitter.test.ts
Treasury was already mutable (must have been changed in an earlier iteration); this PR renames everything called treasury, and additionally fixes a handful of inconsistencies and mismatches (e.g., "swapFee" references that were probably cut/paste errors).
There was already NatSpec in the interface; this also adds @inheritdoc tags in the main contract.
Resolves #2047
> ProtocolFeeSplitter rename treasury

- pkg/deployments/src/task.ts
#2093 means that we currently only write contract addresses to disk when in `LIVE` mode. This doesn't account for the fact that in `TEST` mode we write the contract addresses to `test.json`. 
This PR loosens the `else-if` condition in `save` to also restore this behaviour to `TEST` mode.
> Fix fork tests

- pkg/governance-scripts/contracts/TimelockAuthorizerTransitionMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerTransitionMigrator.test.ts
- pkg/vault/contracts/test/MockBasicAuthorizer.sol
When the `TimelockAuthorizer` was deployed, existing permissions in the old authorizer were migrated as part of the deployment.
The new authorizer is still not connected to the vault because of the migration period, and some other permissions were granted in the old authorizer during this time.
This PR introduces a script to migrate the remaining permissions from the old authorizer to the new one when the time comes.
Some considerations:
- The permissions to migrate will be stored in the migration contract upon deployment.
- The permissions to migrate must exist in the old authorizer.
- The contract needs to be made a general granter by governance (when `TimelockAuthorizer`'s root migration is finished), and then anyone can trigger the migration.
- The migration can only be done once; …
> Timelock authorizer transition migrator

- pkg/interfaces/contracts/liquidity-mining/IGaugeAdder.sol
- pkg/liquidity-mining/contracts/admin/GaugeAdder.sol
- pkg/liquidity-mining/test/GaugeAdder.test.ts
- pkg/liquidity-mining/test/L2GaugeCheckpointer.test.ts
This PR removes the mapping from pool to gauge addresses in the gauge adder. This allows multiple gauges to be added for the same pool (useful for gauge migrations, etc.)
> Remove concept of "canonical gauges" from gaugeadder

- pkg/deployments/README.md
From the changelog:
> The `20221115-aave-rebalanced-linear-pool` task was deleted and replaced with `20221207-aave-rebalanced-linear-pool-v3`. The old task had not been used by anyone.
There still exists a link to this deployment in the readme. As this doesn't go anywhere, let's remove it.
> Delete dangling link in deployments readme

- pkg/governance-scripts/contracts/TimelockAuthorizerTransitionMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerTransitionMigrator.test.ts
Just for cleanup purposes, renounce to granter role after finishing migration.
See conversation: https://github.com/balancer-labs/balancer-v2-monorepo/pull/2151#discussion_r1066956157.
> TA Authorizer migrator: Renounce granter permissions after finishing.

- .github/pull_request_template.md
This PR restores the default template, with an extra paragraph at the top with quick links to deployment templates.
See PR preview with this setup [here](https://github.com/jubeira/balancer-v2-monorepo/compare/master...jubeira:balancer-v2-monorepo:jubeira/deployment-preparation-test?expand=1).
> Restore default template, with sub-template links

- .github/PULL_REQUEST_TEMPLATE/deployment-preparation-template.md
- .github/PULL_REQUEST_TEMPLATE/deployment-template.md
When writing ancillary documentation on the deployment process, and looking at the usual comments in the changelog (e.g., "Deployed <thing> to all networks"), it seems like that should go in the deployment PR template, not the preparation one.
> Move CHANGELOG update until after deployment

- pkg/governance-scripts/contracts/TimelockAuthorizerTransitionMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerTransitionMigrator.test.ts
This PR adds the capability of handling delayed permissions to `TimelockAuthorizerMigrator`.
The migrator will check whether permissions to be granted have delays set in the authorizer, scheduling the grant permission for later if that's the case and storing the schedule ID.
Then, a second added method executes all the scheduled permissions at once, skipping those that may fail for any reason. Anyone can execute the delayed actions; the `TimelockAuthorizer` should only revert if the delay is not due, if the permission was canceled, or if it was already executed.
As of today, the only expected scheduled permission is `add_gauge` in `GaugeController` (see https://github.com/balancer-labs/balancer-v2-monorepo/pull/2173#issuecomment-1397500695).
Closes #2177.
> Handle delayed permissions in `TimelockAuthorizerTransitionMigrator`

- pkg/deployments/tasks/deprecated/20210418-weighted-pool/readme.md
- pkg/deployments/tasks/deprecated/20210624-stable-pool/readme.md
- pkg/deployments/tasks/deprecated/20210812-lido-relayer/readme.md
- pkg/deployments/tasks/deprecated/20211203-batch-relayer/readme.md
- pkg/deployments/tasks/deprecated/20211208-aave-linear-pool/readme.md
- pkg/deployments/tasks/deprecated/20211208-stable-phantom-pool/readme.md
- pkg/deployments/tasks/deprecated/20220304-erc4626-linear-pool/readme.md
- pkg/deployments/tasks/deprecated/20220318-batch-relayer-v2/readme.md
- pkg/deployments/tasks/deprecated/20220404-erc4626-linear-pool-v2/readme.md
- pkg/deployments/tasks/deprecated/20220817-aave-rebalanced-linear-pool/readme.md
- pkg/deployments/tasks/deprecated/20220906-composable-stable-pool/readme.md
Noticed the weighted pool readme pointed to stable... so looked over the whole directory: 1) links should all work; 2) original reasons for deprecation should be preserved; 3) it shouldn't say use the new version if it's also been deprecated.
We will want to update all these again to point to the current ones, once deployed. 
> Deprecation cleanup: broken links and references

- pkg/deployments/hardhat.config.ts
- pkg/deployments/package.json
- yarn.lock
Enable adding auxiliary contracts inside deployment tasks, compiling them before running the `test` task.
This is useful when fork tests require contracts just for specific testing purposes, and that don't belong into any of the workspaces.
For example, contracts can be placed inside `<task>/test/contracts`, and then they can be used within the fork test just like we do in unit tests (i.e. using `deploy`).
N/A
> Enable contract compilation in deployments

- pkg/deployments/tasks/deprecated/20220817-aave-rebalanced-linear-pool/index.ts
Not sure how we missed it, but there is still one deprecated task with incorrect import links.
> Fix import links in deprecated task

- pkg/pool-stable/contracts/ComposableStablePool.sol
- pkg/pool-stable/contracts/ComposableStablePoolRates.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolRates.sol
- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/contracts/protocol-fees/ProtocolFeeCache.sol
- pvt/common/hardhat-base-config.ts
This PR protects composable stable pool functions from read-only reentrancy, and improves docs.
Based on `composable-stable-pool-v3` branch. Note that the base commit of this branch should generate the build info for `composable-stable-pool-v2`: https://github.com/balancer-labs/balancer-v2-monorepo/commit/8239faf8cb394b78450dae497f79d8abe694a7c6.
Not to be merged to master. This patch should be enough to generate the build info for `composable-stable-pool-v3`.
See https://forum.balancer.fi/t/reentrancy-vulnerability-scope-expanded/4345/1 for reference.
N/A
> [Reentrancy patch] Composable Stable Pool V3

- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/contracts/protocol-fees/ProtocolFeeCache.sol
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/test/WeightedPool.test.ts
- pvt/common/hardhat-base-config.ts
This PR protects weighted pool functions from read-only reentrancy, and improves docs.
Based on `weighted-pool-v3` branch. Note that the base commit of this branch should generate the build info for `weighted-pool-v2`: https://github.com/balancer-labs/balancer-v2-monorepo/commit/72f3682b133335b75195124f44c9f5eaa54860b0.
Not to be merged to master. This patch should be enough to generate the build info for `weighted-pool-v3`.
See https://forum.balancer.fi/t/reentrancy-vulnerability-scope-expanded/4345/1 for reference.
N/A
> [Reentrancy patch] Weighted Pool V3

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/NewBasePool.sol
- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/contracts/test/MockBasePool.sol
- pkg/pool-utils/contracts/test/MockNewBasePool.sol
- pkg/pool-utils/contracts/test/MockProtocolFeeCache.sol
- pkg/pool-utils/contracts/test/MockRecoveryModeStorage.sol
- pkg/pool-utils/test/BasePool.test.ts
- pkg/pool-utils/test/NewBasePool.test.ts
- pkg/pool-utils/test/ProtocolFeeCache.test.ts
- pkg/standalone-utils/contracts/test/MockRecoveryRateProviderPool.sol
The complete fix for the read-only reentrancy issue going forward (see this [forum post](https://forum.balancer.fi/t/reentrancy-vulnerability-scope-expanded/4345) for context), we need to protect external functions in base contracts (specifically, `RecoveryMode` and  `ProtocolFeeCache`) that do not currently reference the Vault: yet the Vault is required for the library call.
Since `ProtocolFeeCache` is derived from `RecoveryMode`, it is sufficient to store a Vault reference in RecoveryMode, and make it available internally for calls to the VaultReentrancyLib.
> Reentrancy Preparation: store Vault reference

- pkg/deployments/tasks/20230206-composable-stable-pool-v3/test/test.fork.ts
- pkg/interfaces/contracts/pool-stable/IComposableStablePoolRates.sol
- pkg/interfaces/contracts/pool-utils/IProtocolFeeCache.sol
- pkg/pool-stable/contracts/ComposableStablePoolRates.sol
- pkg/pool-utils/contracts/external-fees/ProtocolFeeCache.sol
Minor changes:
- Use USDC instead of USDT in Composable Stable Pool (CSP) fork test. The reentrancy attacker contract needs to call `approve`, and using USDT means we'd need to add a dependency to the safe ERC20 library (or copy the code). We can just use USDC instead; it even has the same decimals and just works for the fork test.
- Add methods that we'll be testing to interfaces, so that we only need to add a dependency between `deployments` and `interfaces`.
N/A
> Pre-deployment preparation adjustments: interfaces & CSP fork test

- .yarn/versions/b5bdb9d0.yml
- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/package.json
- pkg/pool-linear/CHANGELOG.md
- pkg/pool-linear/package.json
- pkg/pool-utils/CHANGELOG.md
- pkg/pool-utils/package.json
- pkg/solidity-utils/CHANGELOG.md
- pkg/solidity-utils/package.json
Moving on, we'll want to use peer-deps, version ranges and proper use of semver to avoid accidental errors.
> Bump npm packages up to pool-linear

- pkg/interfaces/contracts/pool-utils/IRecoveryModeHelper.sol
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-utils/contracts/RecoveryModeHelper.sol
Add reentrancy warning to `RecoveryModeHelper` + some nits.
This seems to be the only read-only function outside pools that reads vault balances; it doesn't seem very dangerous, but the warning might still be a good idea.
N/A
> Doc improvement - `RecoveryModeHelper`

- pkg/deployments/tasks/20230206-aave-rebalanced-linear-pool-v4/test/contracts/ReadOnlyReentrancyAttackerAaveLP.sol
- pkg/deployments/tasks/20230206-aave-rebalanced-linear-pool-v4/test/test.fork.ts
Restore the attacker contract needed for the current fork test in https://github.com/balancer-labs/balancer-v2-monorepo/pull/2226 to work.
The one in ERC4626 relies on a pool with `WETH`. For AAVE wrapped pools we would need `WETH` and `waWETH`, which doesn't seem to be working.
N/A
> Fix: Restore Aave LP attacker in fork test

- pkg/pool-utils/CHANGELOG.md
- pkg/pool-utils/contracts/lib/VaultReentrancyLib.sol
Make `VaultReentrancyLib` compatible with solc [0.7.0, 0.9.0).
I've tested this locally by making `MockReentrancyPool` compatible with the same range, and compiling both contracts with 0.8.x (with some adjustments so as not to propagate the changes to all dependencies). I could call `ensureNotInVaultContext` in a test and it did not revert.
N/A
> VaultReentrancyLib: use Solidity >=0.7.0 <0.9.0.

- pkg/pool-utils/CHANGELOG.md
- pkg/pool-utils/package.json
This is a patch release for `pool-utils`, featuring https://github.com/balancer-labs/balancer-v2-monorepo/pull/2253.
> pool-utils v3.1.2

- pkg/interfaces/contracts/standalone-utils/IProtocolIdRegistry.sol
- pkg/standalone-utils/contracts/ProtocolIdRegistry.sol
- pkg/standalone-utils/test/ProtocolIdRegistry.test.ts
* [Deployment preparation template](?expand=1&template=deployment-preparation-template.md)
* [Deployment template](?expand=1&template=deployment-template.md)
This PR adds renaming functionality to the ProtocolIdRegistry contract.
- ```function renameProtocolId(uint256 protocolId, string memory newName) external;```
- ```event ProtocolIdRenamed(uint256 indexed protocolId, string name);```
- Rename any registered protocol ID in the case of a mistake during the registration process
- Only authorized users can call this function
- Updated unit tests
> renameProtocolId fn added

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
This extracts executor permissions into their own mapping, which means that it is now clear that the list of executors for a given scheduled execution id is immutable, and only set when scheduling. I also added an event to clearly identify these.
The tests could be improved (e.g. by testing that all executors work), but I didn't want to introduce too many changes there.
Closes #2240
> Extract executor role

- pkg/deployments/tasks/20230215-single-recipient-gauge-factory-v2/index.ts
- pkg/deployments/tasks/20230215-single-recipient-gauge-factory-v2/input.ts
- pkg/deployments/tasks/20230215-single-recipient-gauge-factory-v2/test/task.fork.ts
- pkg/liquidity-mining/contracts/gauges/ethereum/SingleRecipientGauge.sol
- pkg/liquidity-mining/contracts/gauges/ethereum/SingleRecipientGaugeFactory.sol
- pkg/liquidity-mining/test/GaugeRelativeWeightCap.test.ts
- pkg/pool-utils/contracts/Version.sol
Adds version to single recipient gauge and factory (similar to Pool versions)
Fork test adapted, but skipping for now so as to update binaries in a separate deployment preparation PR.
I think we might eventually want to refactor `Version`, since the internal setter is only needed in case the contract is a proxy.
N/A
> Add version to `SingleRecipientGauge`

- pkg/deployments/src/task.ts
Restores `--name` flag in `extract-artifacts`, used to extract artifacts when the name of a contract does not match the build info file name.
E.g. `hh extract-artifacts --id 20230215-single-recipient-gauge-factory-v2 --name SingleRecipientGauge`
Without this change, the script looks for `build-info/<contract-name>` instead of using the correct build info file.
N/A
> Fix `--name` flag for `extract-artifacts` task

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockExecutor.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockExecutor.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This adds dedicated revert reasons for each failure type. On top of improving UX, it also increases confidence in the test suite as each failure mode now gets a different error message. This helped me realize that some of the test removals in https://github.com/balancer-labs/balancer-v2-monorepo/pull/2250 might have not been correct (i.e. we deleted too much).
> Improve Timelock revert reasons

- pkg/governance-scripts/contracts/TimelockAuthorizerMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerRoot.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This is a first attempt at #2242 - likely ~30% of the work required for that. #2238 will likely look very similar to this, as will a future revoker overhaul.
It changes `addGranter` so that granter permissions are stored in a separate data structure, and are not regular permissions (i.e. they don't use the 'base permission' and 'specifier' scheme). This makes analyzing the rules for granting and revoking permissions much simpler. Similarly, granting now also has dedicated delays.
The API is the following:
- addGranter
- removeGranter
- isGranter
- canGrant (the name is terrible, but I don't want to change it yet. This is basically isGranter + delay semantics)
- scheduleGrantDelayChange (not yet implemented)
- getGrantDelay
I introduced two changes to the behavior of the code. First, root …
> Begin granter overhaul

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
Currently only executors can cancel scheduled actions. We want to be able to create a canceler role, which would let accounts with it cancel actions scheduled by other parties (to be wielded by e.g. the emergency subDAO).
Specs:
* only root can create and destroy cancelers
* destruction and creation are immediate
* cancelling is also immediate
* granular: can cancel either a specific execution id, or can globally cancel anything. 
* the scheduler is granted permission to cancel the action it is creating.
Closes issue https://github.com/balancer-labs/balancer-v2-monorepo/issues/2238
> Auth canceler

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
The tests introduced in #2300 had a poor naming convention
> Rename grantee and revokee in tests

- pkg/governance-scripts/contracts/TimelockAuthorizerMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerRoot.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This PR removes the actionId parameter from the addRevoker, removeRevoker, and isRevoker functions because we don’t need that level of granularity. Revokers will now have the power to revoke from either a specific contract or from all contracts, but in both cases, for any actionId. Previously, specific revokers were limited to a combination of actionId and where (contract address). The rationale behind this change is that there are no use cases that require revoking powers for a specific combination of a contract and an actionId.
The PR is a continuation of work on `TimelockAuthorizer` milestone https://github.com/balancer/balancer-v2-monorepo/milestone/20.
> Remove `actionId` from Revoker

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/contracts/liquidity-mining/IChildChainGauge.sol
- pkg/liquidity-mining/contracts/BalancerMinter.sol
- pkg/liquidity-mining/contracts/L2BalancerPseudoMinter.sol
- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
- pkg/liquidity-mining/contracts/test/MockChildChainGauge.sol
- pkg/liquidity-mining/test/L2BalancerPseudoMinter.test.ts
L2 pseudo minter implementation.
This contract is analogous to the `MainnetBalancerMinter`, but for L2s. It works together with child chain gauges to distribute BAL to users by transferring bridged tokens. It replaces the functionality present in Curve's `ChildChainGaugeFactory`.
Last but not least, it has a mechanism to validate that the gauges are correct (similar to the `GaugeAdder` in some sense) which is compatible with our permission system.
In short, at creation time the factory will mark the gauge as valid, and the gauge will store a reference to the factory. The pseudo minter can then retrieve the reference to the factory, and ask the factory whether the gauge was actually created the factory or not. A malicious gauge can pretend to be created from a valid factory, but a valid …
> Add `L2BalancerPseudoMinter`

- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPool.sol
- pkg/pool-weighted/test/BaseWeightedPool.behavior.ts
- pkg/pool-weighted/test/BaseWeightedPool.test.ts
- pkg/pool-weighted/test/LiquidityBootstrappingPool.test.ts
Fee calculation was inverted for swaps given in. Tests that would have caught this were in BaseWeightedPool.behavior.ts. However, the pool type defaulted to WeightedPool: and we didn't override it. So it was never actually running those tests against the LBP.
Now it does: and I removed the defaulted parameter so that this doesn't happen again (e.g., with Managed or a future derived kind of Weighted Pool).
> Liquidity Bootstrapping Pool: fee fix

- pkg/liquidity-mining/contracts/test/MockBalancerMinter.sol
- pkg/liquidity-mining/test/BalancerMinter.test.ts
Add tests for the base `BalancerMinter` layer, which is now common to the mainnet minter (already deployed) and the L2 pseudo minter (not yet deployed).
No changes in functionality, just tests.
N/A
> `BalancerMinter` tests

- pkg/standalone-utils/contracts/relayer/CompoundV2Wrapping.sol
- pkg/standalone-utils/contracts/relayer/ERC4626Wrapping.sol
- pkg/standalone-utils/contracts/relayer/EulerWrapping.sol
- pkg/standalone-utils/contracts/relayer/GaugeActions.sol
- pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
- pkg/standalone-utils/contracts/relayer/IBaseRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/LidoWrapping.sol
- pkg/standalone-utils/contracts/relayer/ReaperWrapping.sol
- pkg/standalone-utils/contracts/relayer/SiloWrapping.sol
- pkg/standalone-utils/contracts/relayer/TetuWrapping.sol
- pkg/standalone-utils/contracts/relayer/UnbuttonWrapping.sol
- pkg/standalone-utils/contracts/relayer/YearnWrapping.sol
Turns out that adding 12 new protocols to the BatchRelayer took up a little bytecode: over 26k!
Luckily they are all very similar - and even already had a common base contract - so a lot of the code could be factored out.
> Batch Relayer: make deployable

- pkg/solidity-utils/test/WordCodec.test.ts
This fixes the test failure uncovered in https://github.com/balancer/balancer-v2-monorepo/pull/2347, which was due to a `bytes32` string not having sufficient leading zeroes if we were unlucky, leading to an encode error. We now properly pad the string to make it a valid `bytes32` value.
> Fix flaky test

- pkg/pool-linear/contracts/LinearPool.sol
LinearPool doesn't use a price rate cache, so it doesn't need to import this library. It was getting `WordCodec` indirectly from it though, so we now explicitly.
> Fix Linear import

- pvt/common/setupTests.ts
This PR fixes `almostEqual` definition for arrays.
`expect(actualArray).to.be.almostEqual(expectedArray)` does not fail when it should without these changes.
Apparently we haven't used this feature in the codebase, but I found it useful for #2325.
N/A
> Remove `async` for `almostEqual` (array case).

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
- pkg/liquidity-mining/test/ChildChainGauge.test.ts
BAL gets a special treatment in `ChildChainGauge`: it is transferred to the pseudo minter during checkpoints, so it cannot be distributed as a regular reward.
This PR enforces this condition by rejecting BAL when adding a new reward. It also adds a BAL getter.
Built on top of #2325 to make use of the tests introduced there. First review #2325, then this one.
Closes #2329.
> Prevent setting BAL as a reward token in `ChildChainGauge`.

- pkg/pool-stable/contracts/ComposableStablePoolFactory.sol
- pkg/pool-stable/test/ComposableStablePoolFactory.test.ts
- pkg/pool-utils/contracts/factories/BasePoolFactory.sol
- pkg/pool-utils/contracts/test/MockPoolFactory.sol
- pkg/pool-weighted/contracts/WeightedPoolFactory.sol
- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPoolFactory.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolFactory.sol
- pkg/pool-weighted/test/LiquidityBootstrappingPoolFactory.test.ts
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pkg/pool-weighted/test/WeightedPoolFactory.test.ts
- pkg/solidity-utils/contracts/helpers/BaseSplitCodeFactory.sol
- pkg/solidity-utils/contracts/test/MockSplitCodeFactory.sol
- pkg/solidity-utils/test/BaseSplitCodeFactory.test.ts
- pkg/standalone-utils/contracts/test/MockRecoveryRateProviderPoolFactory.sol
- pkg/standalone-utils/test/PoolRecoveryHelper.test.ts
- pvt/benchmarks/misc.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Use create2 instead of create for pool factories. This eliminates dependence on the nonce, as the salt value can be chosen arbitrarily.
For reference:
The create opcode calculates the address based on the sender's address and transaction nonce:
`address = keccak256(rlp([sender_address,sender_nonce]))[12:]`
The create2 opcode calculates the address based on the sender's address, the initialization code of the contract (e.g., bytecode + construction arguments), and a salt:
`address = keccak256(0xff + sender_address + salt + keccak256(initialisation_code))[12:]`
> Use create2 for pool factories

- pkg/deployments/.gitignore
Follow-up to https://github.com/balancer/balancer-v2-monorepo/pull/2359. Keeping the old ignore rule in case someone still has these files in their filesystem.
> Add new expected collisions to .gitignore

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerManagement.sol
This PR removes ReentrancyGuard from the TimelockAuthorizer's `execute` function because it is secured by check-effects-interactions pattern. Other functions of TimelockAuthrorizer do not make external calls.
~~- [ ] Tests are included for all code paths (Does not apply)~~
Closes #2381
> Remove reentrancy guard on TimelockAuthorizer

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizerExecute.test.ts
This PR adds additional validation for the `data` parameter of the `schedule` method.  If `data` is less than 4 bytes we revert with 'DATA_TOO_SHORT' too short error.
Closes #2380
> Revert on bad schedule data

- pkg/pool-stable/contracts/StableMath.sol
Somehow the StableMath equation comments for `_calcOutGivenIn` and `_calcInGivenOut` have been (ever so slightly) wrong since the V2 launch.
For reference, here is the [external documentation](https://docs.balancer.fi/reference/math/stable-math.html#trade-equations).
Closes #2390
> StableMath equation comments

- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
Temporarily stop running two inexplicably failing Foundry fuzz tests, until we can fix them. These failures greatly increase the run time, and are surely spurious (likely something to do with versioning)
Addresses #2408
> Skip failing foundry tests

- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
- pvt/helpers/src/models/pools/weighted/types.ts
- pvt/helpers/src/models/types/TypesConverter.ts
Reviewing all the deployment parameters for the Managed Pool, I realized we still had the AUM Protocol Fee Collector, from a time before we unifed all the protocol fee handling, and still had a separate contract for AUM. Just removing that, for clarity.
> Cleanup obsolete AUM parameter

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolAmmLib.sol
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
- pkg/pool-weighted/test/managed/ownerOnlyActions.test.ts
- pvt/benchmarks/misc.ts
- pvt/common/hardhat-base-config.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Move the AMM logic out to an external library to reduce the bytecode. (It would have to be linked in, like AddRemove and ExternalMath.)
Draft because the tests still need work. The linking is there now.
I also tested making the VaultReentrancyLib function view (using code from Midas), which saves about 35 bytes. (But didn't check it in, as I considered it extraneous for this PR, though we might still want to do it.)
- [~] The diff is legible and has no extraneous changes
> Managed Pool bytecode (V1)

- pkg/deployments/README.md
Found while merging the new Linear Pool factories. (Somehow still works, but shows an extraneous tick in the name.)
- [NA] Tests are included for all code paths
> Readme entry typo in Bridge Forwarder

- pkg/pool-weighted/contracts/managed/ManagedPoolFactory.sol
- pkg/pool-weighted/test/ManagedPoolFactory.test.ts
- pvt/benchmarks/misc.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Thwarted by [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860) after the Shapella hard fork, making it undeployable on mainnet, goerli, and polygon (despite squeezing under the bytecode limit by 6 bytes).
> Shorten Managed Pool initialization code

- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
Not sure how this happened, but the factoryOutput entries in the ERC4626LinearPool actionIds: only for mainnet and polygon.
> ERC4626LinearPool missing factory reference

- pkg/pool-utils/test/foundry/PoolRegistrationLib.t.sol
- pkg/pool-weighted/test/foundry/ManagedPoolTokenStorageLib.t.sol
- pkg/pool-weighted/test/foundry/ValueCompression.t.sol
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
Updates `forge` and `ds-test` submodules to the current master.
Fuzz tests require Foundry, and in CI the only version available is apparently `nightly`. 
In this repo, `forge` and `ds-test` are fixed to the versions available when the submodules were originally added. At some point, the nightly version of Foundry became incompatible. The easiest fix is upgrading `forge` and `ds-test`.
To do this, I went into the submodules, pulled the latest master, and committed the changes. After that, I just fixed a few minor incompatibilities that can be seen in this diff.
JKB: I had to do this locally as well. `git checkout master` in pvt/lib/forge-std, and pvt/lib/forge-std/lib/ds-test.
- [N/A] Tests are included for all code …
> Forge update - master.

- pkg/interfaces/contracts/liquidity-mining/IL2LayerZeroDelegation.sol
- pkg/liquidity-mining/contracts/gauges/ChildChainGaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/gauges/ChildChainGaugeRegistry.sol
- pkg/liquidity-mining/contracts/test/MockChildChainGaugeFactory.sol
- pkg/liquidity-mining/test/ChildChainGaugeCheckpointer.test.ts
- pkg/liquidity-mining/test/ChildChainGaugeRegistry.test.ts
- pvt/helpers/src/test/expectEvent.ts
* We need to have an enumerable list of gauges on the L2s.
* Store this list and provide functionality for querying it (e.g., return the total number of elements and a function to return a slice of the array from element N to element M).
* Allow someone to update the list by adding new entries.
* The second function should be permissioned.
* Additionally, we want to check that the gauges are valid.
* This validation is similar to the check from L2BalancerPseudoMinter:
* require(isValidGaugeFactory(factory), "INVALID_GAUGE_FACTORY");
* require(factory.isGaugeFromFactory(gauge), "INVALID_GAUGE");
* (You'd want to call l2BalancerPseudoMiner.isValidGaugeFactory().)
* With the list of gauges, we can then mass-update them when the veBAL balance gets bridged.
* Duplication is not allowed
* …
> Add ChildChainGaugeRegistry

- pkg/deployments/action-ids/polygon/action-ids.json
Didn't notice, the factoryOutput was actually in the wrong block.
> Fix for YearnLinearPool actionIds

- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
- pkg/solidity-utils/contracts/test/MockBasicAuthorizer.sol
- pkg/vault/test/authorizer/AuthorizerWithAdaptorValidation.test.ts
- pvt/helpers/src/models/tokens/Token.ts
- pvt/helpers/src/models/tokens/TokensDeployer.ts
- pvt/helpers/src/models/vault/VaultDeployer.ts
Changes after Vault deployment introduced a dependency on the Vault in solidity-utils tests (the BasicAuthorizer artifact was needed). Move the BasicAuthorizerMock up to solidity-utils to resolve this.
Also, TokensDeployer was looking in standalone-utils for TestToken, instead of where it actually is (solidity-utils). Not sure how that even worked.
> Vault dependency issues

- .github/actions/setup/action.yml
- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/deployment-checks.yml
We are having a few warnings in CI such as this one: 
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v1, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.Show less
```
And also issues with `save-state` and `save-output` in fork tests (which are probably coming from our 'save always' cache dependency; see [here](https://github.com/pat-s/always-upload-cache/tags) for reference):
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and- …
```
> Update dependencies in GH actions

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
This removes an incorrect comment. We _do_ indirectly check that `where` is a contract because we call `getActionId` on it.
> Remove misleading comment

- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
- pkg/interfaces/contracts/vault/ITimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerManagement.sol
- pkg/vault/contracts/authorizer/TimelockExecutionHelper.sol
- pkg/vault/test/authorizer/TimelockAuthorizerActors.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerDelays.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerExecute.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerPermissions.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerRoot.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
This makes the spelling of 'canceling' consistent, as well as changes all instances of 'scheduled actions' to 'scheduled executions' (to avoid confusion between an execution and an action with an action id).
> Timelock spelling and naming improvements

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerManagement.sol
- pkg/vault/test/authorizer/TimelockAuthorizerPermissions.test.ts
Grant and revoke can be made globally by passing the EVERYWHERE sentinel value. This is the same as granters and cancelers. However, we were not considering the special case when mixing specific and global permissions. In particular, we shouldn't allow specific granting if the user is already global, and we should disawllow specific revoking for global users.
This PR brings the behavior of grant and revoke in line with that of granters, revokers and cancelers, fixes existing tests, and adds a couple new ones. The test style of grant and revoke is not ideal (and inferior to that of granter/revoker/canceler), but I followed it nonetheless to avoid causing too much disruption.
> Make Timelock grant and revoke consistent

- pkg/standalone-utils/contracts/relayer/VaultActions.sol
- pkg/standalone-utils/test/VaultActions.test.ts
- pkg/standalone-utils/test/VaultActionsRelayer.setup.ts
The Batch Relayer has always supported internal balance operations - but not with chained references. (And, somehow, there were no tests for it at all!)
Extending it to support chaining would allow more efficient operation; e.g., you could deposit a bunch of tokens into internal balance, then do a big batch swap, all in the same transaction.
It also facilitates certain kinds of "rescue" operations. For example, if a given token got "bricked," such that all transfers failed. This would defeat even a Recovery Mode exit (to an external wallet). Now you could exit to internal balance and, e.g., internal transfer to some sort of helper contract empowered to assist in mitigation, or swap into another token that could be withdrawn, etc.
Closes #2351
> Relayer: Chain internal balance operations

- pkg/pool-linear/README.md
- pkg/pool-utils/README.md
- pkg/vault/README.md
The docs have changed, breaking a few links and causing the markdown link checks to fail (legitimately this time).
> Broken documentation links

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
`BalancerErrors` doesn't actually compile with 0.7.0.
We need the first feature listed in the [release notes for 0.7.1](https://blog.soliditylang.org/2020/09/02/solidity-0.7.1-release-announcement/).
Another option would be not using "free functions", but at this point I think it's just not worth it.
N/A
> Fix `BalancerErrors` compiler range

- pkg/standalone-utils/test/VaultActions.test.ts
- pvt/helpers/src/test/expectEvent.ts
Improve `expectEvent.inIndirectReceipt` when the amount of events are specified.
Without this change, as long as one event matched the given arguments it would pass, even if the expected amount was larger than one. With this change, if the amount is specified we expect all the matches to contain the given arguments.
The return type also changes: it returns a single event for the regular use-case (i.e. when no amount is specified), but returns all of the matches when the amount is specified.
This should be backwards compatible, equally intuitive to use in general when (at least) one event is expected, but more flexible and powerful when analyzing multiple logs in a single receipt.
N/A
> Improve expect event

- README.md
balancer.finance is being phased out. We should direct everyone to the docs page where we reference the official communication channels (for now, Immunefi for smart contract issues; email for UI etc)
> deprecate security@balancer.finance email

- pkg/interfaces/contracts/liquidity-mining/IStakelessGaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/gauges/StakelessGaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/test/MockStakelessGauge.sol
- pkg/liquidity-mining/test/StakelessGaugeCheckpointer.test.ts
This PR adds the capability to checkpoint multiple specific gauges in the same call.
The effect would be the same as calling `checkpointSingleGauge` multiple times, but it should be much cheaper to do so in one call because the storage reads are cheaper after the first time they are performed in the same tx.
Built on top of #2533; merge that one first.
N/A
> Stakeless gauge checkpointer: multi gauge checkpoint

- pkg/standalone-utils/contracts/relayer/VaultActions.sol
- pkg/standalone-utils/test/VaultActions.test.ts
- pkg/standalone-utils/test/VaultActionsRelayer.setup.ts
- pkg/standalone-utils/test/VaultActionsStableJoinExit.test.ts
Recovery mode exits currently revert on both Weighted and Stable pools. This adds support for them.
Closes #2458
> Relayer: support recovery mode exit

- pkg/liquidity-mining/contracts/test/MockAvalancheRootGauge.sol
- pkg/liquidity-mining/contracts/test/MockBaseRootGauge.sol
Root Gauge Mocks are required for the fork tests of *some* root gauges (e.g., Avalanche). They are not used in the monorepo, but need to be in the build-info for the deployment fork tests to work.
There is a way to import them into the deployments repo (e.g., src/contracts/helpers), but this is undesirable, as the mock contracts are directly dependent on the root gauges themselves, and we do not want to introduce a dependency on liquidity-mining in the deployments repo.
So, the compromise is to leave them in the monorepo, and document in both places where the files are coming from.
> Restore Root Gauge Mocks

- pkg/interfaces/contracts/liquidity-mining/IStakelessGaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/gauges/StakelessGaugeCheckpointer.sol
- pkg/liquidity-mining/contracts/test/MockGaugeController.sol
- pkg/liquidity-mining/test/StakelessGaugeCheckpointer.test.ts
This PR makes the stakeless gauge checkpointer more future proof and flexible, while making it compatible with the new avax gauges.
Summary of the changes:
- Introduce the notion of gauge costs for any gauge type (not only Arbitrum). The checkpointer is prepared in case legacy (mostly all existing non-arbitrum gauges) not implementing the interface to retrieve the cost, and defaulting to 0 in that case.
- Add more methods to checkpoint in a flexible manner: by a given list of types (which supersedes the function to checkpoint a single type).
- Moved the argument checks to the external / public functions. Before this change some checks were implicit (mostly for single gauge checkpoints); now all the functions are protected at the entry level, and internal functions just work with validated …
> Stakeless gauge checkpointer: generic cost gauges

- pkg/solidity-utils/contracts/helpers/BaseSplitCodeFactory.sol
- pkg/solidity-utils/contracts/helpers/CodeDeployer.sol
- pkg/solidity-utils/contracts/test/CodeDeployerFactory.sol
- pkg/solidity-utils/test/BaseSplitCodeFactory.test.ts
- pkg/solidity-utils/test/CodeDeployer.test.ts
We received an interesting report from [Czar102](https://github.com/Czar102) about the CodeDeployer library. Since it only happens on factory deployment, it's not a vulnerability, and the likelihood of this actually happening is low. Nevertheless, it is a valid issue with a non-zero probability of happening, so we will fix it.
CodeDeployer is a library which "deploys" arbitrary code to an address; it need not be a valid contract. We use this in the BaseSplitCodeFactory, which underlies all our pool factories, so that we are able to deploy contracts with very large creationCode: up to 48k, twice the contract size limit. This is needed for some contracts with very tight bytecode constraints, and also a large amount of initialization code (e.g., filling in immutables).
Essentially, it splits …
> Ensure CodeDeployer pseudo-contracts are not executable

- pkg/interfaces/contracts/standalone-utils/IBalancerRelayer.sol
- pkg/standalone-utils/contracts/relayer/BalancerRelayer.sol
- pkg/standalone-utils/test/BaseRelayerLibrary.test.ts
Discovered during deployment preparation that the relayer now deploys *two* contracts: BalancerRelayer, and the new query library contract. In order to verify the query library (and the BalancerRelayer, which takes it as an argument), we need to expose the address of the query library.
> Missing function Batch Relayer V6

- audits/README.md
Addressing a DefiSafety report item.
> Add audit applicability matrix

- pkg/liquidity-mining/contracts/gauges/optimistic/OptimisticRootGauge.sol
- pkg/liquidity-mining/contracts/gauges/optimistic/OptimisticRootGaugeFactory.sol
In response to https://github.com/balancer/balancer-deployments/pull/117#discussion_r1619323348; it might get confusing if we keep adding L2s that are OP-stack compatible.
This minor refactor changes the contract name and adds a public tag to identify the target L2 in the gauge and the factory.
N/A
> Refactor: Optimism --> Optimistic gauges, with public network tag.

- audits/README.md
Replaced the broken Balancer logo (404 error) in audits/README.md with a working version used elsewhere in the repo. Screenshots attached for comparison. Small UX fix to improve docs.
Thanks!
Old:
New:
> Fix broken logo in audits/README.md

- pkg/interfaces/contracts/liquidity-mining/IVotingEscrowRemapper.sol
This PR corrects the license header in IVotingEscrowRemapper.sol by replacing incorrect wording with the proper "GNU General Public License" phrasing.
These changes are purely textual and do not affect the logic or functionality of the contract.
> Fix license header text in IVotingEscrowRemapper.sol

- .github/workflows/benchmarks.yml
Updates actions/checkout@v4 to actions/checkout@v5 across CI workflows.
Upgrade to actions/checkout@v5 for improved performance and stability.
Reference:
Latest version: https://github.com/actions/checkout/releases/tag/v5.0.0
> chore: update GitHub actions in CI workflows

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-stable/test/ComposableStablePoolProtocolFees.test.ts
Changes
LinearPool.sol:
care must be take → care must be taken (grammar fix).
LinearPool.test.ts:
it('adapt …') → it('adapts …') (subject–verb agreement).
ComposableStablePoolProtocolFees.test.ts:
balaced → balanced (spelling).
there balance change → their balance change (possessive pronoun).
> Fix typos in comments

- pkg/pool-linear/test/math.ts
- pkg/pool-stable/test/ComposableStablePoolRates.test.ts
Typo in variable name
File: pkg/pool-linear/test/math.ts
Old -> New: mainNomimalBalance -> mainNominalBalance (in function signature and return line)
Why: Corrects the spelling of nominal. Aligns with terminology used elsewhere and avoids confusion / IDE autocomplete mismatches.
Grammar in test description
File: pkg/pool-stable/test/ComposableStablePoolRates.test.ts
Old -> New: belows -> below
Why: Fixes an English grammar error in a test context string.
> Fix typos in tests

- pkg/pool-utils/test/foundry/ComposablePoolLib.t.sol
Fix incorrect address casting in dropBptFromBalances test. The test was trying to compare uint256 balance values as addresses, which would cause compilation errors. Now correctly compares balance values directly.
> fix: correct balance comparison in ComposablePoolLib test

- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPoolSettings.sol
- pkg/pool-weighted/contracts/managed/CircuitBreakerStorageLib.sol
pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPoolSettings.sol
Old: enableRecoveryMode" or "disabledRecoveryMode
New: enableRecoveryMode" or "disableRecoveryMode
Why: Corrects the function name in the reference; “disableRecoveryMode” is the actual identifier and the grammatically correct form (not past tense).
pkg/pool-weighted/contracts/managed/CircuitBreakerStorageLib.sol
Old: arbers
New: arbitrageurs
Why: Spelling fix for the standard term in AMM/MEV contexts.
Old: wny
New: why
Why: Typo fix for readability.
> fix typos in LBP contracts

- pkg/pool-weighted/test/CircuitBreakerLib.test.ts
The file contained two identical tests for "should support single sided bounds".
Removed the duplicate to keep the test suite clean and avoid redundancy.
> test: remove duplicate "should support single sided bounds" test 

- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/solidity-utils/contracts/helpers/BaseSplitCodeFactory.sol
- pkg/solidity-utils/contracts/helpers/WordCodec.sol
Changes
ManagedPool.test.ts
“so is represented” → “are/is represented” (grammar fix in test comments).
BaseSplitCodeFactory.sol
“crated” → “created” (typo in NatSpec).
WordCodec.sol
“accesing” → “accessing” (typo in comment).
> Fix typos in comments & docs

- pkg/pool-stable/test/ComposableStablePoolStorage.test.ts
fixed `probablity` - `probability` in pkg/pool-stable/test/ComposableStablePoolStorage.test.ts
> chore: fix grammatical errors

- pkg/liquidity-mining/contracts/PreseededVotingEscrowDelegation.vy
- pkg/liquidity-mining/contracts/VotingEscrow.vy
This PR corrects several minor typos in comments and documentation across the codebase. The changes are non-functional and purely textual to improve clarity and maintain a clean, professional codebase:
- `transfering` → `transferring`
- `deactive` → `deactivate`
- `Pevious` → `Previous`
> Fix spellings issues
