- contracts/pools/oracle/PoolPriceOracle.sol
- contracts/pools/weighted/WeightedPool2Tokens.sol
- contracts/test/PoolPriceOracleMock.sol
Lowers it to 23.3k, swaps with buffer re-usage are lowered to 109.7k
> Weighted: Reduce factory bytecode size

- pkg/deployments/hardhat.config.ts
- pkg/deployments/migrations/002_vault.ts
Note: The Polygon RPC connection needs to be activated in the Infura dashboard.
> Add deployment config for Polygon

- pkg/asset-manager-utils/contracts/AssetManager.sol
- pkg/asset-manager-utils/contracts/SinglePoolAssetManager.sol
Replaced all instances of an explicit `mul(x).divDown(ONE)` with an equivalent call to `FixedPoint.mulDown`
> use FixedPoint library in Asset Managers

- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
We have multiple styles of tests currently for asset managers, I've converted all of them to the most up to date format.
Waiting on #606 to be merged for a rebase.
> Consolidate asset manager tests styles

- pkg/pool-stable/contracts/StableMath.sol
- pkg/solidity-utils/contracts/helpers/BalancerErrors.sol
> Stable: Add converge assertions

- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
I've changed `rebalanceAndSwap` to take a `BatchSwap` struct as converting only `swaps` to being in memory led to stack errors.
> Add rebalanceAndSwap testcases

- pkg/pool-stable/contracts/StableMath.sol
This PR introduces a few optimizations we can apply to the stable math to reduce a little bit the gas costs
> Stable: Optimize math gas costs

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
- pkg/asset-manager-utils/test/helpers/rebalance.ts
Supersedes #632 to account for changes to tests.
_Note to future people: if you do revive this, don't forget to also revive #623!_
> Remove AM rewards

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/contracts/test/MockRewardsAssetManager.sol
- pkg/asset-manager-utils/test/AaveATokenAssetManager.test.ts
For consistency with the rest of the codebase.
> style: standardise on american spelling of initialise

- pkg/pool-utils/contracts/BasePool.sol
Part of https://github.com/balancer-labs/balancer-v2-monorepo/issues/655
> Make Pool scaling factors fixed-point

- pkg/deployments/package.json
- pkg/deployments/src/contracts.ts
- pkg/deployments/src/logger.ts
- pkg/deployments/src/task.ts
- pkg/deployments/src/types.ts
- yarn.lock
> Deployments: Implement tasks model

- pkg/asset-manager-utils/contracts/IAssetManager.sol
- pkg/asset-manager-utils/contracts/RewardsAssetManager.sol
- pkg/asset-manager-utils/contracts/test/MockAssetManager.sol
- pkg/asset-manager-utils/test/RewardsAssetManager.test.ts
@facuspagnuolo here's a quick mockup of what the `shouldRebalance` function would roughly look like. Happy to update the interface if there's something else you'd prefer.
> Expose a function to calculate whether AMs should rebalance after a join/exit

- pkg/pool-weighted/README.md
Tripped up somebody in the hackathon
> README typo

- pkg/deployments/hardhat.config.ts
- pkg/deployments/tasks/20210418-vault/input.ts
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/index.ts
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/input.ts
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/output/kovan.json
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/output/rinkeby.json
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/readme.md
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/test/task.deploy.ts
- pkg/deployments/tasks/20210701-liquidity-bootstrapping-pool/test/task.fork.ts
Deployment scripts plus kovan and rinkeby deployment outputs.
(opening a PR for archival and tidyness reasons, developed live with @EndymionJkb and merging immediately)
> Add LBP deployment

- pkg/distributors/contracts/MultiRewards.sol
(rather than requiring them to whitelist themselves)
> Multirewards - allow anyone to whitelist an asset manager

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/MultiRewards.test.ts
(also use sharedBeforeEach to notify staking contract of reward)
> Multirewards: Use standard math library for duration calculations

- pkg/pool-stable/contracts/meta/StableOracleMath.sol
- pkg/pool-stable/contracts/test/meta/MockStableOracleMath.sol
- pkg/pool-stable/test/meta/StableOracleMath.test.ts
- pvt/helpers/src/models/pools/stable/math.ts
We still need to polish the math rounding
> Stable: Implement meta stable pool math

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/standalone-utils/contracts/BatchRelayer.sol
- pkg/standalone-utils/test/BatchRelayer.test.ts
Joins a pool and stakes the bpt to the LP in the `MultiRewards` contract
> MultiRewards: joinAndStake with batch relayer

- pkg/deployments/tasks/20210720-ldo-merkle/abi/MerkleRedeem.json
- pkg/deployments/tasks/20210720-ldo-merkle/index.ts
- pkg/deployments/tasks/20210720-ldo-merkle/input.ts
- pkg/deployments/tasks/20210720-ldo-merkle/output/mainnet.json
- pkg/deployments/tasks/20210720-ldo-merkle/readme.md
- pkg/deployments/tasks/20210720-ldo-merkle/test/task.deploy.ts
- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/package.json
Opening and merging immediately, developed alongside @gtaschuk
> Add LDO Merkle deployment

- pkg/pool-linear/contracts/LinearMath.sol
Add initial rounding to linear pool math. It is possible that we may also want to round up and down nominal functions. We will know it after stress testing this.
> Linear pool math rounding

- pkg/deployments/tasks/20210812-wsteth-rate-provider/test/task.deploy.ts
Very simple test just to check that we're matching the response from wstETH.
> Add test for wstETH rate provider deployment

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/PoolTokenCache.sol
- pkg/distributors/contracts/Reinvestor.sol
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/Reinvestor.test.ts
A collection of suggestions from Certora
Most notably we allow anyone to refresh (poke) the pool token list that the exiter and reinvestor use
> Distributor: MultiRewards certora improvements

- pkg/asset-manager-utils/contracts/AaveATokenAssetManager.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/MultiRewardsAuthorization.sol
- pkg/distributors/contracts/RewardsScheduler.sol
- pkg/distributors/contracts/interfaces/IMultiRewards.sol
- pkg/distributors/test/Exiter.test.ts
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
- pkg/distributors/test/Reinvestor.test.ts
- pkg/distributors/test/RewardsScheduler.test.ts
Allows a rewarder to schedule a reward for the MultiRewards contract
Once the reward startTime has passed, anyone can poke the contract to notify the MultiRewards contract of the reward
[OpenZeppelin Defender](https://openzeppelin.com/defender/) willl interact with this contract to start scheduled rewards
> Distributor: MultiRewards rewards scheduler

- pkg/pool-weighted/contracts/smart/InvestmentPool.sol
From Certora. Discarded old PR; too many changes, and I don't want to reorder anything now. Just removed the "section" comments so they weren't wrong.
> Correct comments, and optimize weight interpolation

- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/test/Exiter.test.ts
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
- pkg/distributors/test/Reinvestor.test.ts
Fix for issue [C01] of the OZ audit.
> MultiRewards: use Math.mul when dealing with time

- pkg/distributors/contracts/MerkleOrchard.sol
- pvt/benchmarks/merkleClaim.ts
- pvt/benchmarks/package.json
Not as pretty as before but will most likely substantially reduce gas costs.
> Use a single transfer per token in MerkleOrchard

- pkg/distributors/contracts/MultiRewards.sol
Adds/standardizes natspec for public/external functions [OZ-L05]
Renames a few things per OZ suggestions [OZ-L05]
> Distributors: Multirewards naming and natspec [OZ-LO4/OZ-L05]

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/test/StablePhantomPoolFactory.test.ts
This will be required for proportional exits (only on emergency)
> Phantom: Use minimum BPT amount

- pkg/distributors/contracts/MultiRewards.sol
- pkg/pool-stable/contracts/StableMath.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/smart/LiquidityBootstrappingPool.sol
Fixes a few pending low severity and informational issues.
> Small fixes based on OZ audit report

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable/contracts/StableMath.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/contracts/meta/StableOracleMath.sol
- pkg/pool-stable/contracts/test/MockStableMath.sol
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
- pkg/pool-weighted/contracts/smart/InvestmentPool.sol
- pkg/pool-weighted/contracts/smart/LiquidityBootstrappingPool.sol
- pkg/pool-weighted/contracts/test/MockWeightedMath.sol
This is a bit overdue - these were contracts as at some point they held some state, but there's no point now, and I believe we all think of them as libraries already anyway.
> Make WeightedMath and StableMath libraries

- pkg/distributors/contracts/MerkleRedeem.sol
- pkg/distributors/contracts/MultiRewards.sol
- pkg/distributors/contracts/MultiRewardsAuthorization.sol
- pkg/distributors/contracts/interfaces/IDistributor.sol
- pkg/distributors/test/Exiter.test.ts
- pkg/distributors/test/MultiRewards.test.ts
- pkg/distributors/test/MultiRewardsCallbacks.test.ts
- pkg/distributors/test/MultiRewardsSharedSetup.ts
- pkg/distributors/test/Reinvestor.test.ts
- pkg/pool-stable/contracts/StableMath.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/test/StablePool.test.ts
- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/smart/LiquidityBootstrappingPool.sol
This simply merges the `oz-audit` branch into `master`, bringing in all the changes that resulted from the report.
> OZ audit fixes

- pkg/distributors/contracts/MerkleOrchard.sol
> MerkleOrchard: removed unused FixedPoint library

- pkg/distributors/contracts/MerkleOrchard.sol
> Distributors: remove unused Ownable library from the merkle orchard

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
Closes #888
Reduces gas by offloading token indexing to the client
(tagging: @evgenyboxer for visibility as this changes the contract interface slightly)
> MerkleOrchard: User-supplied token list

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
Renaming to reflect that these contracts distribute tokens on behalf of distributors
closes https://github.com/balancer-labs/balancer-v2-monorepo/issues/886
> Orchard Renaming

- pkg/distributors/contracts/MerkleOrchard.sol
> Orchard: use private state variables

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
re: https://github.com/balancer-labs/balancer-v2-monorepo/pull/902/files#r722411624
closes #911
> Orchard: Distribution events

- pkg/pool-utils/contracts/BalancerPoolToken.sol
Discovered when writing Fei documentation. Cleaner class diagram this way.
> Remove extraneous base class

- pkg/standalone-utils/contracts/BatchRelayerLibrary.sol
- pkg/standalone-utils/contracts/interfaces/IStaticATokenLM.sol
- pkg/standalone-utils/contracts/relayer/AaveWrapping.sol
- pkg/standalone-utils/test/LidoWrapping.test.ts
This needs tests but I want to make this available for if we need to get something out for the frontend team to test with
> feat: add relayer module for wrapping Aave tokens

- pkg/pool-linear/contracts/LinearMath.sol
- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/contracts/test/MockLinearMath.sol
Minor thing, for consistency with the others (#863).
> Make LinearMath a library

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/contracts/LinearPoolUserData.sol
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/interfaces/IRateProvider.sol
- pkg/pool-utils/contracts/rates/PriceRateCache.sol
- pvt/helpers/src/models/pools/linear/LinearPool.ts
This is the result of my review of `LinearPool` and interactions with `BasePool`. The changes in this PR should not modify the contract's behavior: they only favor readability. Separate PRs will cover bug fixes.
> LinearPool: code review

- pkg/pool-linear/contracts/LinearPool.sol
- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-utils/contracts/BasePool.sol
- pvt/helpers/src/models/pools/linear/LinearPool.ts
Follow up to #1028. The underlying issue is similar to the one fixed in #998.
> Make linear swap percentage change stricter

- pkg/pool-linear/contracts/LinearMath.sol
Follow up of https://github.com/balancer-labs/balancer-v2-monorepo/pull/1065
> Get rid of unnecessary FP multiplication

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This should reduce gas costs in all scenarios, assuming all tokens have a rate provider except BPT.
> Phantom immutable rates

- pkg/distributors/contracts/MultiDistributor.sol
Certora reported that this reduces gas costs for free seeing as the `MultiDistributor` is a singleton. I can't replicate this using benchmarks but there's no harm in including it.
> MultiDistributor: make any internal variables/functions private

- pkg/distributors/contracts/DistributionScheduler.sol
- pkg/distributors/contracts/MultiDistributor.sol
- pkg/distributors/contracts/interfaces/IDistributionScheduler.sol
- pkg/distributors/test/DistributionScheduler.test.ts
- pkg/distributors/test/MultiDistributor.test.ts
No point in breaking this down really as it's so small. Here's a scheduler.
There's probably some renaming to do before this is properly complete (`scheduleId` is a terrible name) but eh.
fixes #959
> MultiDistributor: Add working implementation of DistributionScheduler

- pkg/pool-weighted/contracts/WeightedPool2Tokens.sol
Looks like there was some nasty spaces that came in through applying my suggestion in #1071
> Whitespace change to appease linter gods

- pkg/pool-stable/contracts/meta/MetaStablePool.sol
- pkg/pool-stable/contracts/meta/StableOracleMath.sol
- pkg/pool-stable/contracts/test/meta/MockStableOracleMath.sol
- pkg/pool-weighted/contracts/oracle/OracleWeightedMath.sol
- pkg/pool-weighted/contracts/oracle/OracleWeightedPool.sol
- pkg/pool-weighted/contracts/test/MockOracleWeightedMath.sol
Continuation of #863 and #1027.
> Make oracle contracts libraries

- .github/workflows/ci.yml
- pkg/gauges/test/BalancerTokenAdmin.test.ts
We haven't picked up a couple of breakages in the test suite because we're not actually running CI for the gauges package.
I've added it to CI and fixed up any issues.
> Fix gauges package tests

- pkg/gauges/contracts/GaugeController.vy
> Allow voting for multiple gauges at once

- pkg/liquidity-mining/contracts/AuthorizerAdaptor.sol
- pkg/liquidity-mining/contracts/BalancerMinter.sol
- pkg/liquidity-mining/contracts/BalancerTokenAdmin.sol
- pkg/liquidity-mining/contracts/VotingEscrowDelegationProxy.sol
- pkg/liquidity-mining/contracts/interfaces/IAuthorizerAdaptor.sol
- pkg/liquidity-mining/contracts/interfaces/IBalancerMinter.sol
- pkg/liquidity-mining/contracts/interfaces/IBalancerTokenAdmin.sol
- pkg/liquidity-mining/contracts/interfaces/IGaugeController.sol
- pkg/liquidity-mining/contracts/interfaces/IVeDelegation.sol
- pkg/liquidity-mining/contracts/interfaces/IVotingEscrow.sol
- pkg/liquidity-mining/contracts/veBALDeploymentCoordinator.sol
Draft PR as this is still in development but having a PR open helps discussion.
This PR adds the veBALDeploymentCoordinator contract which implements much of the setup of the veBAL system to avoid mistakes during setup and enforcing certain timings.
> Add veBALDeploymentCoordinator

- pkg/liquidity-mining/contracts/veBALDeploymentCoordinator.sol
As discussed on the standup, if we wanted to permission triggering the first stage of the activation we could bundle together the call to `performFirstStage` with a call which adds the admin permissions over the Authorizer.
We can then remove the `authenticate` modifier which complicates the governance procedure (requirement for contract to be deployed before proposal can be made)
> refactor: remove authentication from veBALDeploymentCoordinator

- pkg/asset-manager-utils/test/RebalancingRelayer.test.ts
- pkg/pool-utils/test/BasePool.test.ts
- pkg/pool-utils/test/LegacyBasePool.test.ts
- pkg/vault/contracts/TimelockAuthorizer.sol
- pkg/vault/test/AssetManagement.test.ts
- pkg/vault/test/ExitPool.test.ts
- pkg/vault/test/FlashLoan.test.ts
- pkg/vault/test/InternalBalance.test.ts
- pkg/vault/test/JoinPool.test.ts
- pkg/vault/test/PoolRegistry.test.ts
- pkg/vault/test/SwapValidation.test.ts
- pkg/vault/test/Swaps.test.ts
- pkg/vault/test/TimelockAuthorizer.test.ts
- pkg/vault/test/VaultAuthorization.test.ts
- pvt/helpers/src/constants.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizerDeployer.ts
- pvt/helpers/src/models/authorizer/types.ts
- pvt/helpers/src/models/vault/VaultDeployer.ts
> Authorizer: Improve grant/revoke delays granularity

- pkg/deployments/tasks/2022xxxx-timelock-authorizer/test/task.fork.ts
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerMigrator.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
> Authorizer: Improve granter/revoker interface

- pkg/pool-weighted/contracts/lib/GradualValueChange.sol
- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Pulls out some miscellaneous refactors from #1253
> Misc refactor

- pkg/vault/test/PoolRegistry.test.ts
As the title says.
PS: awesome project guys =)
> Fixed typo on comment (poolregistry test)

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
As of [0c41cf7](https://github.com/balancer-labs/balancer-v2-monorepo/pull/1253/commits/0c41cf762a878dddd55cb405f469ea33880cf924), we're deprioritising being able to cheaply call `_getTotalTokens()`.
I've gone through the usage of this function and replaced with equivalent values which are held in memory. As the arrays uses to calculate the value of `_getTotalTokens()` come directly from the Vault we can trust them to be accurate.
> Avoid usage of _getTotalTokens in BaseWeightedPool

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
> Avoid SLOAD when updating weights

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
Follows on from #1273 to pass in `_denormWeightSum` on all calls to `_normalizeWeight` and `_denormalizeWeight`.
In most calls to these functions we're iterating over all tokens so we might as well optimise for this case and remove the unary forms of these functions.
> Use cached denormWeightSum for all normalization operations

- pkg/pool-weighted/test/ManagedPool.test.ts
This PR alters some basic managed pool tests and makes them fatster by:
- removing a test I deemeed unnecessary (the weight sum, which is an internal detail)
- improving transparency on how we test weights
- removing unnecessary tests for all token combinations (multiple tokens are handled with for loops - we don't need to test all combinations like we do for weighted pool)
> Reduce managed pool tests

- pkg/pool-weighted/test/GradualValueChange.test.ts
> Fix failing weighted pool tests

- pkg/liquidity-mining/contracts/admin/ChildChainGaugeTokenAdder.sol
- pkg/liquidity-mining/contracts/gauges/ChildChainLiquidityGaugeFactory.sol
- pkg/liquidity-mining/contracts/interfaces/IChildChainLiquidityGaugeFactory.sol
- pkg/liquidity-mining/contracts/interfaces/IChildChainStreamer.sol
- pkg/liquidity-mining/contracts/interfaces/IRewardsOnlyGauge.sol
- pkg/liquidity-mining/test/ChildChainGaugeTokenAdder.test.ts
> Add ChildChainGaugeTokenAdder contract

- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/index.ts
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/arbitrum.json
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/kovan.json
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/mainnet.json
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/optimism.json
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/polygon.json
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/output/rinkeby.json
done for consistency w/ other outputs
> change 'factory' to 'NoProtocolFeeLiquidityBootstrappingPoolFactory'

- pkg/deployments/src/network.ts
- pkg/deployments/tasks/20220517-protocol-fee-withdrawer/input.ts
- pkg/deployments/tasks/20220517-protocol-fee-withdrawer/output/mainnet.json
The target was changed three days ago.
> Update SNX impl input

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pvt/helpers/src/models/pools/weighted/types.ts
Reuse code between getSwapFeePercentage and getGradualSwapFeeUpdateParams.
Add startWeights to getGradualWeightUpdateParams, for symmetry with swap fee params.
> Managed Pool: reuse and symmetry

- pkg/pool-stable/contracts/meta/MetaStablePool.sol
- pkg/pool-utils/contracts/rates/PriceRateCache.sol
- pkg/solidity-utils/contracts/math/LogExpMath.sol
- pkg/solidity-utils/contracts/openzeppelin/SafeCast.sol
Propagate Tom's math insight to the rest of the codebase.
> Cheaper range checking

- pkg/pool-utils/contracts/BasePool.sol
- pkg/pool-utils/contracts/LegacyBasePool.sol
> BasePool Docs (NatSpec)

- pkg/balancer-js/src/pool-utils/encoder.ts
- pkg/interfaces/contracts/solidity-utils/helpers/IRecoveryMode.sol
- pkg/pool-stable/contracts/StablePool.sol
- pkg/pool-stable/test/StablePool.test.ts
- pkg/pool-utils/contracts/RecoveryMode.sol
- pkg/pool-utils/test/LegacyBasePool.test.ts
- pvt/helpers/src/models/pools/base/BasePool.ts
- pvt/helpers/src/models/pools/base/types.ts
Rename enter/exit Recovery Mode the less-confusable enable/disable. Also clarify some type names.
> Rename Recovery Mode enter/exit

- pkg/pool-utils/test/LegacyBasePool.test.ts
One last bit of renaming... didn't want to do anything in the deployment branch
> Fix recovery mode event test

- pkg/interfaces/contracts/standalone-utils/IProtocolFeesWithdrawer.sol
- pkg/standalone-utils/contracts/ProtocolFeesWithdrawer.sol
Our SNX coordinator needs to be able to speak to the ProtocolFeeWithdrawer in order to allowlist the tokens again but we have no good interface for this. This PR adds this interface.
> Create an interface for interacting with the ProtocolFeeWithdrawer

- pkg/deployments/tasks/20220413-arbitrum-root-gauge-factory/index.ts
- pkg/deployments/tasks/20220413-arbitrum-root-gauge-factory/output/mainnet.json
- pkg/deployments/tasks/20220413-polygon-root-gauge-factory/index.ts
- pkg/deployments/tasks/20220413-polygon-root-gauge-factory/output/mainnet.json
These will be relevant once https://github.com/balancer-labs/balancer-v2-monorepo/pull/1352 is merged as we need these to compute their action ids.
> Add missing gauge impl outputs

- pkg/governance-scripts/contracts/BaseCoordinator.sol
- pkg/governance-scripts/contracts/test/TestCoordinator.sol
- pkg/governance-scripts/test/BaseCoordinator.test.ts
This PR adds tests for the BaseCoordinator contract with some minor changes to functionality to accommodate this.
> Add tests for BaseCordinator

- .github/workflows/deployment-checks.yml
- pkg/deployments/ci/prepare-config.ts
Looks like #1388 isn't enough so lets split across different RPCs.
> Use infura for CI tasks which don't need archive access

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/ignored-functions.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/mainnet/expected-collisions.json
- pkg/deployments/action-ids/optimism/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
- pkg/deployments/src/actionId.ts
Only added token and pool functions for now, as we'll soon have a lot of those.
> Add support for ignored function signatures

- pkg/pool-utils/test/BasePool.test.ts
Somehow we were not testing for this :shrug:
> Add missing BasePool paused test

- pkg/pool-stable-phantom/test/StablePhantomPool.test.ts
I have PTSD from this test occasionally failing with 'Expected "300001" to be equal 300000'
> StablePhantom: intermittent test failure

- pkg/deployments/src/task.ts
- pkg/deployments/tasks/20220325-gauge-controller/index.ts
- pkg/deployments/tasks/20220325-mainnet-gauge-factory/index.ts
- pkg/deployments/tasks/20220325-ve-delegation/index.ts
- pkg/deployments/tasks/20220413-child-chain-gauge-factory/index.ts
- pkg/deployments/tasks/20220530-preseeded-voting-escrow-delegation/index.ts
This also makes `deploy` much more similar to `deployAndVerify`.
> Prefer deploy to deployAndVerify for Vyper contracts

- pkg/deployments/action-ids/goerli/action-ids.json
- pkg/deployments/action-ids/goerli/expected-collisions.json
- Covering tasks, scripts and deprecated.
> [Goerli] Adding action IDs for deployments.

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
This PR is a noop, just reordering functions to a more logical order
> Reorder code for root transfers in TimelockAuthorizer

- pkg/interfaces/contracts/vault/IBasePool.sol
- pkg/pool-utils/contracts/BasePool.sol
- pkg/standalone-utils/contracts/BalancerQueries.sol
- pkg/vault/contracts/test/MockPool.sol
I moved the query fns to the interface.
> Remove dependency of BalancerQueries on BasePool

- pkg/pool-stable-phantom/contracts/StableMath.sol
- pkg/pool-stable-phantom/contracts/test/MockStableMath.sol
- pkg/pool-stable-phantom/test/StableMath.test.ts
Don't think we need this anymore.
> StableMath: remove unused method for token protocol fees

- pkg/liquidity-mining/contracts/BoostV2.vy
- pkg/liquidity-mining/hardhat.config.ts
This PR imports the Boost2 contract from https://github.com/curvefi/curve-veBoost/blob/db3dec43b6e4fac0fca1f01509f9133563f43ebb/contracts/BoostV2.vy
I've got a couple of modifications I'd like to make but this PR aims to be just show verifiably that  we're starting from a sound starting point.
> pull in BoostV2 contract from Curve

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
This PR aims to minimise the diff between master and #1496 by pulling in all the noop modifications to layout so that the diff just contains new features.
> Stable yield diff minimisation

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Illustrating the dangers of deferring tests :) _adjustBalancesByTokenRatios() was not actually returning anything. (And the docs were wrong.)
> Stable: Add missing return

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
Updates to comments only. Catches references to renamed functions in comments, adds Natspec for undocumented external functions, etc.
> Stable: various doc updates

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Really a nit here, but didn't want it to go in the comment one.
> Stable: move function closer to use

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
> Update authorizer docs

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
Proof we need to finish the tests = this
> Stable: no comment

- pkg/pool-stable-phantom/contracts/StableMath.sol
- pkg/pool-stable-phantom/contracts/test/MockStableMath.sol
- pvt/helpers/src/models/pools/stable-phantom/math.ts
These are a proportional join we no longer support.
> Delete unused StableMath functions

- pkg/pool-stable-phantom/contracts/StablePhantomPool.sol
- pkg/pool-stable-phantom/contracts/StablePoolProtocolFees.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
This extracts fees from the main contract into its own module. No changes in behavior.
> Add StableProtocolFees

- pkg/pool-stable-phantom/contracts/StablePoolProtocolFees.sol
- pkg/pool-stable-phantom/contracts/StablePoolStorage.sol
Propagate the registered balances/index convention to the other parts of the Stable contract
> Stable: use consistent naming across entire contract

- pkg/pool-stable-phantom/contracts/StablePoolProtocolFees.sol
- pkg/solidity-utils/contracts/helpers/WordCodec.sol
We don't need a full slot for these values.
> Pack values in storage

- pkg/pool-linear/contracts/LinearPool.sol
Caught some minor out-of-date comments (e.g., resulting from changes in BasePool). Added NatSpec to public/external functions.
> LinearPool: even finaler touches

- pkg/pool-stable/test/ComposableStablePool.test.ts
Best viewed by ignoring whitespace changes.
> Improve post join swap exit tests

- pkg/pool-linear/contracts/aave/AaveLinearPoolFactory.sol
- pkg/pool-linear/contracts/button-wood/UnbuttonAaveLinearPoolFactory.sol
- pkg/pool-linear/contracts/erc4626/ERC4626LinearPoolFactory.sol
- pkg/pool-linear/test/AaveLinearPool.test.ts
- pkg/pool-linear/test/AaveLinearPoolFactory.test.ts
- pkg/pool-linear/test/ERC4626LinearPool.test.ts
- pkg/pool-linear/test/ERC4626LinearPoolFactory.test.ts
- pkg/pool-linear/test/UnbuttonAaveLinearPoolFactory.test.ts
- pkg/pool-stable/contracts/ComposableStablePoolFactory.sol
- pkg/pool-utils/contracts/factories/BasePoolSplitCodeFactory.sol
- pkg/pool-utils/contracts/test/MockPoolSplitCodeFactory.sol
- pkg/pool-utils/test/factories/BasePoolSplitCodeFactory.test.ts
- pkg/pool-weighted/contracts/WeightedPoolFactory.sol
- pkg/pool-weighted/contracts/WeightedPoolNoAMFactory.sol
- pkg/pool-weighted/contracts/smart/BaseManagedPoolFactory.sol
- pkg/pool-weighted/contracts/smart/LiquidityBootstrappingPoolFactory.sol
- pkg/pool-weighted/test/LiquidityBootstrappingPoolFactory.test.ts
- pkg/pool-weighted/test/WeightedPoolFactory.test.ts
- pkg/pool-weighted/test/WeightedPoolNoAMFactory.test.ts
- pvt/benchmarks/misc.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
All pools will now use this, so move from ComposableStable and Managed factories up into the base factory
> Move FeesProvider up to the pool factory base contract

- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/test/InvariantGrowthProtocolFees.behavior.ts
- pkg/pool-weighted/test/WeightedPool.test.ts
- pvt/benchmarks/joinExit.ts
- pvt/benchmarks/multihop.ts
- pvt/benchmarks/singlePair.ts
We've very likely going to have to cut this token count to fit inside the bytecode limit. It makes sense to do this first so it doesn't cause noise in a later diff.
> Cut token count in WeightedPool from 20 to 8

- .github/workflows/ci.yml
These take > 30 minutes sometimes. You can also tell which benchmark has the issue now.
> Split benchmark tasks

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/optimism/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
Now that we have some initial pools, we can compute these.
> Add stable and linear action ids

- pkg/interfaces/contracts/liquidity-mining/ILiquidityGauge.sol
- pkg/liquidity-mining/contracts/gauges/StakelessGauge.sol
- pkg/liquidity-mining/contracts/gauges/ethereum/LiquidityGaugeV5.vy
> Removing getCurrentRelativeWeight from ILiquidityGauge 

- pkg/pool-weighted/contracts/BaseWeightedPool.sol
Now that pausing and recovery mode are BasePool concerns, these comments are simply outdated.
> Remove old references to pausing

- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
Maybe this was a merge conflict?
> Restore preJoin invariant calculation

- pkg/pool-weighted/contracts/test/MockWeightedPool.sol
- pkg/pool-weighted/test/WeightedPool.test.ts
- pvt/helpers/src/contract.ts
Similar to https://github.com/balancer-labs/balancer-v2-monorepo/pull/1657, except there's no bug here.
> Add only owner tests to WeightedPool

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
In the natspec for the external functions for collecting AUM fees from ManagedPool we say that we return the amount of BPT which is minted to the manager. We actually return the total amount of BPT minted for both the manager and the protocol.
This PR separates out these two values so we can return the correct values here.
> Return only manager's BPT from external AUM collection functions

- pkg/standalone-utils/test/UnbuttonWrapping.test.ts
Small cleanup: deleting duplicate functions from `UnbuttonWrapping` test, and using helpers from `standalone-utils` as in other tests from the same package.
> Cleanup: reusing helper functions in UnbuttonWrapping test.

- pkg/pool-weighted/contracts/smart/ManagedPool.sol
- pkg/solidity-utils/contracts/helpers/ERC20Helpers.sol
Nothing of consequence really, just tidying up stuff.
> Misc managed changes

- pkg/pool-utils/contracts/protocol-fees/InvariantGrowthProtocolSwapFees.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/pool-weighted/test/PostJoinExitProtocolFees.test.ts
Pulls out all the non rate related code from #1678
> Rework WeightedPoolProtocolFees to return percentages rather than amounts

- pkg/pool-weighted/test/WeightedPool.test.ts
I've changed the join type to be a "proper" proportional join rather than just an arbitrary inputs join with proportional inputs to fix the failing test
> Fix failing test in #1678

- pkg/pool-stable/contracts/ComposableStablePoolRates.sol
- pkg/pool-stable/contracts/ComposableStablePoolStorage.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolStorage.sol
These changes should have a negligible effect on performance, but greatly reduce the immutable bytecode footprint.
> Reduce ComposableStable bytecode size

- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/test/WeightedPool.test.ts
- pvt/helpers/src/models/pools/base/BasePool.ts
> Expose actual supply on weighted pools

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
```
npx hardhat save-action-ids --id 20220906-composable-stable-pool --network mainnet --name ComposableStablePool --address 0xa13a9247ea42d743238089903570127dda72fe44
npx hardhat save-action-ids --id 20220906-composable-stable-pool --network polygon --name ComposableStablePool --address 0xb553c155f95ab42b674d6fe501693e30d54a47e2
npx hardhat save-action-ids --id 20220906-composable-stable-pool --network arbitrum --name ComposableStablePool --address 0xcc98357eaf3e227bdef6b97780aae84bea9b02b0
```
> New ComposableStablePool action ids

- pkg/pool-utils/contracts/protocol-fees/ProtocolFeeCache.sol
- pkg/pool-utils/test/ProtocolFeeCache.test.ts
- pkg/pool-weighted/contracts/BaseWeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/pool-weighted/test/WeightedPool.test.ts
- pkg/pool-weighted/test/YieldProtocolFees.test.ts
Results from WeightedPool walkthrough.
> Weighted pool changes

- pkg/deployments/action-ids/arbitrum/action-ids.json
- pkg/deployments/action-ids/goerli/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
- pkg/deployments/action-ids/optimism/action-ids.json
- pkg/deployments/action-ids/polygon/action-ids.json
```
$ npx hardhat save-action-ids --id 20220908-weighted-pool-v2 --network mainnet --name WeightedPool --address 0x6a5ead5433a50472642cd268e584dafa5a394490
Generating action IDs for WeightedPool of 20220908-weighted-pool-v2
$ npx hardhat save-action-ids --id 20220908-weighted-pool-v2 --network polygon --name WeightedPool --address 0x9d75cc71555ddabcb89b52c818c2c689e2191401
Generating action IDs for WeightedPool of 20220908-weighted-pool-v2
$ npx hardhat save-action-ids --id 20220908-weighted-pool-v2 --network arbitrum --name WeightedPool --address 0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd
Generating action IDs for WeightedPool of 20220908-weighted-pool-v2
$ npx hardhat save-action-ids --id 20220908-weighted-pool-v2 --network optimism --name WeightedPool --address …
```
> Weighted Pools V2 action ids

- pkg/deployments/package.json
- pkg/distributors/package.json
- pkg/governance-scripts/package.json
- pkg/interfaces/package.json
- pkg/liquidity-mining/package.json
- pkg/pool-linear/package.json
- pkg/pool-stable/package.json
- pkg/pool-utils/package.json
- pkg/pool-weighted/package.json
- pkg/solidity-utils/package.json
- pkg/standalone-utils/package.json
- pkg/vault/package.json
- pvt/benchmarks/package.json
- pvt/helpers/package.json
- pvt/helpers/src/contract.ts
- yarn.lock
Addresses below comment from `pvt/helpers/src/contract.ts`
> // From https://github.com/nomiclabs/hardhat/issues/611#issuecomment-638891597, temporary workaround until
> // https://github.com/nomiclabs/hardhat/issues/1716 is addressed.
> Use Hardhat's linking

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
- pkg/pool-weighted/contracts/managed/vendor/BaseWeightedPool.sol
Here's some low-hanging fruit changes we can make.
> Begin flattening ManagedPool

- pkg/pool-stable/contracts/test/MockComposableStablePool.sol
- pkg/pool-stable/hardhat.config.ts
- pkg/pool-stable/package.json
- pkg/pool-weighted/hardhat.config.ts
- pkg/pool-weighted/package.json
- pvt/common/hardhat-base-config.ts
- yarn.lock
We're now ignoring all code size warnings on test files.
> Upgrade hh ignore warnings

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
Another minor step in removing unnecessary code from BasePool.
> Push limits on token numbers up to ManagedPool

- pkg/pool-weighted/contracts/lib/WeightedExitsLib.sol
- pkg/pool-weighted/contracts/lib/WeightedJoinsLib.sol
- pkg/pool-weighted/contracts/managed/vendor/BaseWeightedPool.sol
And you get a library! And you get a library!
> Push weighted join and exit types into a library

- pkg/standalone-utils/contracts/relayer/VaultActions.sol
> Removing return values from VaultActions

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BaseWeightedPool.sol
builds on #1759
This PR inlines the ManagedPool specific code (LP allowlist and swaps toggle) with the dispatch code.
> Flatten `_doJoin`

- pkg/pool-utils/contracts/lib/PoolRegistrationLib.sol
- pkg/pool-utils/contracts/test/MockPoolRegistrationLib.sol
- pkg/pool-utils/test/PoolRegistrationLib.test.ts
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pvt/helpers/src/constants.ts
- pvt/helpers/src/models/vault/Vault.ts
> Extend PoolRegLib

- pkg/pool-weighted/contracts/lbp/LiquidityBootstrappingPool.sol
- pkg/pool-weighted/contracts/lib/ValueCompression.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolTokenLib.sol
- pkg/pool-weighted/contracts/test/MockValueCompression.sol
- pkg/pool-weighted/test/ValueCompression.test.ts
Prep for circuit breakers. This will be used to compress things other than weights, and anyway weights aren't mentioned in the code (only "values"), so this seemed like a good name.
> Rename WeightCompression to ValueCompression

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
Really small things that were already merged (or about to be) when I noticed them
> Misspellings and readability

- pkg/distributors/package.json
- pkg/governance-scripts/package.json
- pkg/interfaces/package.json
- pkg/liquidity-mining/package.json
- pkg/pool-linear/package.json
- pkg/pool-stable/package.json
- pkg/pool-utils/package.json
- pkg/pool-weighted/package.json
- pkg/solidity-utils/package.json
- pkg/standalone-utils/package.json
- pkg/vault/package.json
- pvt/common/hardhat-base-config.ts
- yarn.lock
This uses some of the new features to make warnings be errors.
> Upgrade ignore-warnings

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/vendor/BasePool.sol
This PR takes us from 27.576kB to 27.479kB
> Basepool bytecode reduction

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
For simplicity I'm collecting AUM fees even when the mint/burn amount is zero.
> Collect AUM fees on adding/removing tokens

- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
Was writing some docs on Foundry testing, using WeightedMath as an example, found an unfinished comment. Finished it, added another, and defined a constant for clarity.
> Improve docs; weighted math foundry

- pkg/interfaces/contracts/pool-utils/IControlledManagedPool.sol
- pkg/pool-utils/contracts/controllers/ManagedPoolController.sol
- pkg/pool-utils/test/ManagedPoolController.test.ts
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
- pkg/pool-weighted/test/managed/ownerOnlyActions.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
Change updateWeightsGradually (for ManagedPools) to take an array of tokens (part of the prep for composability).
> Add tokens to UpdateWeightsGradually

- pkg/pool-weighted/test/ManagedPool.test.ts
- pkg/pool-weighted/test/managed/BasePool.test.ts
Changes based on https://github.com/balancer-labs/balancer-v2-monorepo/pull/1828#pullrequestreview-1117777757
> Update ManagedPool tests to be based around swap/join/exit actions

- pkg/pool-weighted/contracts/WeightedMath.sol
- pkg/pool-weighted/test/foundry/WeightedMath.t.sol
> Add exitSwap implementation and fuzz test

- pkg/balancer-js/src/utils/errors.ts
- pkg/interfaces/contracts/solidity-utils/helpers/BalancerErrors.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/managed/AddRemove.test.ts
This adds the missing items mentioned in #1842
> Misc add/remove token changes

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
This PR adds the concept of "virtual supply" to `ManagedPoolSettings` so we can override it in `ManagedPool` to subtract off the preminted BPT.
> Add virtual `_getVirtualSupply` getter

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
Needed for https://github.com/balancer-labs/balancer-v2-monorepo/pull/1855#discussion_r981520164
> Merge return values from _collectAumManagementFees

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
See https://github.com/balancer-labs/balancer-v2-monorepo/pull/1846#pullrequestreview-1124092238.
https://github.com/balancer-labs/balancer-v2-monorepo/pull/1846#discussion_r982687923 was addressed in a separate commit https://github.com/balancer-labs/balancer-v2-monorepo/commit/40428a9d767adbb259887e7cffdd0ea8ab32ebdc in case we don't want to go that way.
> Addressing managed pool settings outstanding comments

- pkg/pool-utils/contracts/lib/ComposablePoolLib.sol
- pkg/pool-weighted/contracts/managed/ManagedPool.sol
Addresses review comments on #1856 as I managed to push the changes on the wrong branch.
> Composable review notes

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/vault/Vault.ts
> Add joinSwaps to ManagedPool

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
> Composable exits

- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
Addresses https://github.com/balancer-labs/balancer-v2-monorepo/pull/1858#discussion_r982772610
> Add test for return value of collectAUMManagementFees

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
This removes some bytecode (just a little).
> Move library calls into helper function

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
These are all up to the owner.
Closes https://github.com/balancer-labs/balancer-v2-monorepo/issues/1263
> Adjust managed pool limits

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/test/ManagedPool.test.ts
~~We need tests for this before merging.~~
> Properly override recovery mode exit in ManagedPool

- pkg/pool-weighted/contracts/managed/ManagedPool.sol
- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
- pkg/pool-weighted/contracts/test/MockManagedPoolSettings.sol
- pkg/pool-weighted/test/ManagedPoolSettings.test.ts
Check the allowlist independent of the MustAllowlistLP state
> Even more flexible allowlist

- pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol
Codename: 4D chess.
Also adding some small code reuse when collecting fees while not initialized to revert in add / remove / external collect.
> Updating fee collection timestamp every time aum fees are collected

- pkg/pool-weighted/contracts/lib/CircuitBreakerLib.sol
> Import Math

- pkg/liquidity-mining/contracts/test/MockLiquidityGauge.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolProtocolFees.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolRates.sol
- pkg/pool-stable/contracts/test/MockComposableStablePoolStorage.sol
- pkg/pool-weighted/contracts/test/MockBasePool.sol
- pkg/pool-weighted/contracts/test/MockWeightedPoolProtocolFees.sol
- pkg/standalone-utils/contracts/test/MockStaticATokenLM.sol
Having 3 difference variants of this revert message hurts me greatly.
> Standardize "not implemented" error

- pkg/pool-utils/contracts/test/MockVault.sol
- pvt/helpers/src/models/pools/linear/LinearPool.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
> Match `Swap` event from `MockVault` with `IVault` event.

- pkg/deployments/README.md
I've tried the API and it works for deprecated contracts by appending `deprecated/` to the task ID
> Update deployments readme

- pkg/governance-scripts/hardhat.config.ts
- pkg/liquidity-mining/hardhat.config.ts
- pkg/pool-linear/hardhat.config.ts
- pkg/pool-utils/hardhat.config.ts
- pkg/solidity-utils/hardhat.config.ts
- pkg/standalone-utils/hardhat.config.ts
- pkg/vault/hardhat.config.ts
We had only applied these to some of the packages.
> Ignore silenced solc warnings on all packages

- pkg/deployments/hardhat.config.ts
If my understanding is correct, we don't need to check action IDs that we've just generated; we should only check for uniqueness after creation.
Note for the reviewer: hide whitespaces when checking diff.
Closes #1502.
> Check action ID uniqueness when creating new ones

- pkg/pool-weighted/test/CircuitBreakerLib.test.ts
Set bounds more clearly in one of the CircuitBreaker tests (caused intermittent failures; see the audit).
> Flaky circuit breaker test

- pkg/deployments/action-ids/mainnet/action-ids.json
These are required in order to pause Pools, etc.
> Add managed pool action ids

- pkg/distributors/hardhat.config.ts
We now apply our rules for silencing hardhat warnings in `pkg/distributors`
> Silence hardhat warnings in distributors package

- pkg/deployments/DEPLOYING.md
- pkg/deployments/package.json
- pkg/deployments/src/types.ts
- pkg/deployments/src/verifier.ts
- yarn.lock
We need this new version to be able to deploy to gnosis and bsc.
> Update hardhat verifier

- README.md
Instructions are expected to work with Node v14.x and Yarn 2; this PR clarifies this explicitly. 
See #1986.
> Add note about Node / Yarn versions in README.

- package.json
Update main `package.json` with correct node version. See [engines ref](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines).
See #1957 and https://github.com/balancer-labs/balancer-v2-monorepo/pull/1985#issuecomment-1306072875.
> Update node engine in main package.json.

- pkg/interfaces/CHANGELOG.md
Small documentation update, since #1601 might be superseded and this change should be in already (the interface is already merged to master).
N/A
> Add `IL2GaugeCheckpointer` to interfaces changelog.

- pkg/interfaces/CHANGELOG.md
- pkg/vault/CHANGELOG.md
Update `v2-interfaces` changelog with the addition of the adaptor entrypoint, and vault with the timelock authorizer.
N/A
> Changelog update

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
> Fix linter

- audits/README.md
…e report
The 3rd report from Trail of bits had a broken link. Also, the date seemed not to correspond with the date where the report was stored. Updated the two.
- [x ] Bug fix 
- [ x] The diff is legible and has no extraneous changes
> Quick fix, fix broken link to audit from Trail of bits

- pkg/deployments/src/index.ts
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/test/task.fork.ts
- pkg/deployments/tasks/20220513-double-entrypoint-fix-relayer/test/task.fork.ts
- pkg/deployments/tasks/20220530-preseeded-voting-escrow-delegation/test/test.fork.ts
- pkg/deployments/tasks/20220609-stable-pool-v2/test/task.fork.ts
- pkg/deployments/tasks/20220707-distribution-scheduler/test/test.fork.ts
- pkg/deployments/tasks/20220714-fee-distributor-v2/test/test.fork.ts
- pkg/deployments/tasks/20220725-protocol-fee-percentages-provider/test/task.fork.ts
- pkg/deployments/tasks/20220817-aave-rebalanced-linear-pool/test/test.fork.ts
- pkg/deployments/tasks/20220822-mainnet-gauge-factory-v2/test/task.fork.ts
- pkg/deployments/tasks/20220823-arbitrum-root-gauge-factory-v2/test/task.fork.ts
- pkg/deployments/tasks/20220823-optimism-root-gauge-factory-v2/test/task.fork.ts
- pkg/deployments/tasks/20220823-polygon-root-gauge-factory-v2/test/task.fork.ts
- pkg/deployments/tasks/20220916-batch-relayer-v4/test/test.fork.ts
- pkg/deployments/tasks/20221021-managed-pool/test/task.fork.ts
- pkg/deployments/tasks/20221111-authorizer-adaptor-entrypoint/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210721-liquidity-bootstrapping-pool/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210727-meta-stable-pool/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210811-ldo-merkle/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210907-investment-pool/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210913-bal-arbitrum-merkle/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20210928-mcb-arbitrum-merkle/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20211203-batch-relayer/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20220413-arbitrum-root-gauge-factory/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20220413-polygon-root-gauge-factory/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20220420-fee-distributor/test/test.fork.ts
- pkg/deployments/tasks/deprecated/20220628-optimism-root-gauge-factory/test/task.fork.ts
- pkg/deployments/tasks/deprecated/20220720-batch-relayer-v3/test/test.fork.ts
This PR adds an `index.ts` for the deployments package code to make it simpler to deprecate tasks and generally make things nicer.
> Add index.ts for `deployments/src`

- pkg/deployments/tasks/20221123-pool-recovery-helper/readme.md
I forgot to set a proper description.
> Fix recovery readme

- pkg/pool-linear/test/LinearPool.test.ts
- pkg/pool-utils/contracts/test/MockVault.sol
- pkg/pool-weighted/test/WeightedPoolProtocolFees.behavior.ts
- pvt/helpers/src/models/vault/Vault.ts
This improves MockVault so that it also supports managed balances, which is a requirement for implementing #2042.
> Add support for cash and managed to MockVault

- pkg/interfaces/contracts/pool-utils/IRecoveryModeHelper.sol
- pkg/pool-utils/contracts/RecoveryModeHelper.sol
- pvt/helpers/src/models/vault/Vault.ts
Minor suggestions from https://github.com/balancer-labs/balancer-v2-monorepo/pull/2068#pullrequestreview-1196518480.
N/A.
> Recovery mode helper suggestions

- pkg/deployments/tasks/20221122-composable-stable-pool-v2/index.ts
- pkg/deployments/tasks/20221122-composable-stable-pool-v2/input.ts
This extends the deployment task so that a Pool is also deployed and verified, automatically verifying all future Pools in that network, as well as providing a Pool to compute action IDs.  Similar to #2040. 
We'll likely at some point want to extract some of this code into helpers in the base task code.
This task does not yet exist on `master` since #2065 is not merged, so I'm targetting that branch. Merge into `master` after #2065 goes in.
> Verify Pool on ComposableStablePool task

- pvt/benchmarks/misc.ts
Fix benchmarks in #2078.
Merge into #2078's branch before merging to master.
> Fix benchmarks (Refactor ManagedPool constructor arguments)

- pkg/deployments/CHANGELOG.md
- pkg/deployments/package.json
> Patch deployments package

- pkg/liquidity-mining/contracts/NullVotingEscrow.sol
It's an ERC20 token which has zero balances and zero total supply. Natspec should explain the purpose.
We could get away with just `balanceOf` and `totalSupply` but for paranoia's sake I thought it best to implement the IERC20 interface.
> Add NullVotingEscrow contract

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
- pkg/liquidity-mining/contracts/gauges/ChildChainGaugeFactory.vy
This PR copies in the code for boost-aware L2 gauges
Gauge code is taken from https://polygonscan.com/address/0xbb1b19495b8fe7c402427479b9ac14886cbbaaee
Factory code is taken from https://polygonscan.com/address/0xabc000d88f23bb45525e447528dbf656a9d55bf5
The gauge is for the pool https://curve.fi/#/polygon/pools/atricrypto3/deposit (Can verify by checking the token address under "Contracts" header and checking this is `lp_token` on the gauge.) 
The gauge has a `factory` getter to verify the above address.
> Pull in base for new L2 gauges

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
Builds on #2108 
This splits killing and unkilling so the adaptor can distinguish between them.
> Split killing and unkilling on new gauges

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
Builds on #2108
This adds our standard modification so that relayers can move gauge deposits without an approval.
> Add infinite allowance for Balancer Vault

- pkg/liquidity-mining/contracts/VeBoostV2.vy
I've copied across the EIP1271 mechanism from `LiquidityGaugeV5` to `veBoostV2`.
> Add EIP1271 support to boostv2

- pkg/solidity-utils/contracts/helpers/SingletonAuthentication.sol
Noticed this during an unrelated review.
> Remove extraneous import/dependency

- pkg/deployments/addresses/arbitrum.json
- pkg/deployments/addresses/bsc.json
- pkg/deployments/addresses/gnosis.json
- pkg/deployments/addresses/goerli.json
- pkg/deployments/addresses/mainnet.json
- pkg/deployments/addresses/optimism.json
- pkg/deployments/addresses/polygon.json
> update address lookup

- pkg/deployments/CHANGELOG.md
Was pending update from #2136: this has been merged.
N/A
> Update deployments changelog.

- pkg/deployments/src/task.ts
- pkg/deployments/tasks/20220325-single-recipient-gauge-factory/output/goerli.json
Removed an unused import and added a missing address to fix CI
> Fix linter and deployment address checks

- pkg/standalone-utils/test/ProtocolFeeSplitter.test.ts
This PR removes the duplication of the top-level describe blocks for each caller and instead defines functions to specify a successful or forbidden action. We then call one of these functions depending on the caller.
> Remove duplication in ProtocolFeeSplitter tests

- pkg/deployments/action-ids/goerli/action-ids.json
- pkg/deployments/action-ids/mainnet/action-ids.json
Follow-up on #2160.
This is required for #2151 to migrate liquidity mining permissions properly.
N/A
> Add action IDs for gauge adder v3

- pkg/deployments/DEPLOYING.md
Minor updates to `DEPLOYING.md`, reflecting the rather recent changes in the artifact generation (`artifact` vs `abi` and `bytecode`).
N/A
> Update `DEPLOYING` readme

- pkg/deployments/tasks/20221202-timelock-authorizer/test/task.fork.ts
This adds fork tests for minting and migrating the authorizer. We already know that these are correct by due to regular testing + checking that the new authorizer returns true for `canPerform` checks on important permissions however it doesn't hurt to have it here as well.
> Add fork tests for most important actions after authorizer migration

- pkg/deployments/README.md
Minor deployments README update (managed pool is already in the "deprecated" section).
N/A
> Update active deployments list (managed pool)

- pkg/deployments/tasks/scripts/20230130-ta-transition-migrator/input.ts
- pkg/deployments/tasks/scripts/20230130-ta-transition-migrator/test/task.fork.ts
Follow-up on #2173 (see https://github.com/balancer-labs/balancer-v2-monorepo/pull/2173#discussion_r1086629495).
Just fork tests improvements; no changes in contract features nor artifacts.
See #1991
> `TimelockAuthorizerTransitionMigrator`: fork tests improvement

- pkg/pool-weighted/contracts/WeightedPool.sol
- pkg/pool-weighted/contracts/WeightedPoolFactory.sol
- pkg/pool-weighted/contracts/test/MockWeightedPool.sol
- pkg/pool-weighted/test/WeightedPoolFactory.test.ts
- pvt/benchmarks/misc.ts
- pvt/common/hardhat-base-config.ts
- pvt/helpers/src/models/pools/weighted/WeightedPoolDeployer.ts
Minimal version implementation for Weighted Pool V3.
No tests nor extra modules; simple getters at the top contract level for pool and factory.
Builds on top of `weighted-pool-v3` hotfix branch. Not to be merged to master.
- (see note) Tests are included for all code paths
N/A
> [Weighted Pool V3] Add Version

- pkg/deployments/package.json
- yarn.lock
Follow-up on #2196; this PR adds the solidity linter to `deployments` workspace.
N/A
> Add solidity linter to deployments workspace

- pkg/deployments/tasks/20230206-composable-stable-pool-v3/readme.md
- pkg/deployments/tasks/20230206-weighted-pool-v3/readme.md
- pkg/deployments/tasks/deprecated/20220908-weighted-pool-v2/readme.md
- pkg/deployments/tasks/deprecated/20221122-composable-stable-pool-v2/readme.md
Just aesthetics in deployment docs.
N/A
> Pretty forum links in READMEs

- pkg/interfaces/contracts/pool-linear/IERC4626.sol
This interface is used in multiple LinearPools, so could be moved up into /interfaces vs being repeated in every deployment.
> Add interface used in multiple Linear Pools

- pkg/liquidity-mining/contracts/gauges/gnosis/GnosisRootGauge.sol
- pkg/liquidity-mining/contracts/gauges/gnosis/GnosisRootGaugeFactory.sol
Supersedes the venerable #1433 (which I will close when done). That branch was 1) too old to merge; and 2) mixed code and deployment, since it predated our current rigorous deployment process.
This first one just adds the GnosisRootGauge and factory.
Note that the resolution of #2217 might affect this. I'm not addressing it here to avoid stealing @jubeira 's thunder.
Closes #2216.
> Add GnosisRootGauge and associated factory

- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
Self-descriptive.
Closes https://github.com/balancer-labs/balancer-v2-monorepo/issues/2236
> Improve docs for 'MIN_DELAY'

- pkg/interfaces/contracts/standalone-utils/IProtocolIdRegistry.sol
- pkg/standalone-utils/contracts/ProtocolIdRegistry.sol
- pkg/standalone-utils/test/ProtocolIdRegistry.test.ts
* [Deployment preparation template](?expand=1&template=deployment-preparation-template.md)
* [Deployment template](?expand=1&template=deployment-template.md)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203851568634045
> Protocol id registry added

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
Master seems to be broken (lint in Vault).
> Fix master (lint issue)

- README.md
- pkg/deployments/README.md
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/readme.md
- pkg/deployments/tasks/20220513-double-entrypoint-fix-relayer/readme.md
- pkg/deployments/tasks/20220628-gauge-adder-v2/readme.md
- pkg/deployments/tasks/20221124-authorizer-adaptor-entrypoint/readme.md
- pkg/deployments/tasks/20221205-veboost-v2/readme.md
- pkg/deployments/tasks/20230109-gauge-adder-v3/readme.md
- pkg/deployments/tasks/20230206-erc4626-linear-pool-v3/readme.md
- pkg/deployments/tasks/scripts/20220610-snx-recovery-coordinator/readme.md
- pkg/deployments/tasks/scripts/20230109-gauge-adder-migration-v2-to-v3/readme.md
- pkg/governance-scripts/contracts/deprecated/20220606-snx-recovery/README.md
- pkg/governance-scripts/contracts/deprecated/20220606-tribe-bal-minter/README.md
- pkg/governance-scripts/contracts/deprecated/20220628-gauge-adder-migration/README.md
- pkg/pool-linear/README.md
- pkg/pool-weighted/README.md
Separate extraneous random fixes in this prerequisite PR to #2261 
> Moar link cleanup

- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
Straggler from https://github.com/balancer-labs/balancer-v2-monorepo/pull/2259
> Fix failing test

- pkg/distributors/contracts/MerkleOrchard.sol
- pkg/distributors/test/MerkleOrchard.test.ts
Fix for the Merkle Orchard contract, removing optimizations when claiming distributions. We don't expect to use this contract regularly; we just need it to work properly for one final distribution, so removing optimizations is fine.
Issue described in [this post](https://medium.com/immunefi/balancer-logic-error-bugfix-review-74f5edca8b1a).
Based on `merkle-orchard-v2` branch, which is branched from https://github.com/balancer-labs/balancer-v2-monorepo/commit/a8e5f93c555cc842af586f74022f48dbcd58bf67 (where the build info for Orchard V1 was generated). This is to be verified by the reviewer.
This should not be merged back into master since the contract was removed from the codebase long ago, and this is a patch release.
See #2218.
> Merkle orchard: claim fixes

- pkg/deployments/hardhat.config.ts
- pkg/deployments/src/actionId.ts
When there's a particular endpoint failure in CI, it's a bit annoying to figure out which one it is.
This PR adds a few more logs to identify failures easily.
N/A
> Minor logging improvements to 'check' tasks.

- pkg/deployments/tasks/20230217-gnosis-root-gauge-factory/readme.md
Add missing output link for the Gnosis Root Gauge deployment.
> Gnosis Root Gauge: add outputs to readme

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
In https://github.com/balancer-labs/balancer-v2-monorepo/pull/2250 I removed a bunch of tests. In https://github.com/balancer-labs/balancer-v2-monorepo/pull/2271, I mentioned that maybe those removals were excessive. That turned out to be incorrect: the removals were right, but the test descriptions were bad (in some cases even incorrect), and that caused the confusion. This PR fixes those.
> Fix test removal

- pkg/deployments/tasks/20210418-authorizer/readme.md
- pkg/deployments/tasks/20210418-vault/readme.md
- pkg/deployments/tasks/20211202-no-protocol-fee-lbp/readme.md
- pkg/deployments/tasks/20220325-authorizer-adaptor/readme.md
- pkg/deployments/tasks/20220413-child-chain-gauge-factory/readme.md
- pkg/deployments/tasks/20220517-protocol-fee-withdrawer/readme.md
- pkg/deployments/tasks/20220527-child-chain-gauge-token-adder/readme.md
- pkg/deployments/tasks/20220721-balancer-queries/readme.md
- pkg/deployments/tasks/20220725-protocol-fee-percentages-provider/readme.md
- pkg/deployments/tasks/20220812-child-chain-reward-helper/readme.md
- pkg/deployments/tasks/20220916-batch-relayer-v4/readme.md
- pkg/deployments/tasks/20221123-pool-recovery-helper/readme.md
- pkg/deployments/tasks/20221124-authorizer-adaptor-entrypoint/readme.md
- pkg/deployments/tasks/20230206-weighted-pool-v3/readme.md
This is already in the checklist; no excuses :) I don't know how we keep missing this.
> Add Avalanche outputs to readme

- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
Continuation of https://github.com/balancer-labs/balancer-v2-monorepo/pull/2294, this time revamping the entire test section related to these functions, to both make the tests clearer, and also to add new test scenarios for added functionality.
Since the diff is relatively large (as I pretty much had to rewrite many of the tests), it might be better to simply review the new tests directly (instead of comparing).
> Improve add/remove Granter tests

- pkg/liquidity-mining/package.json
- yarn.lock
This should improve compiler downloads and reduce CI failures; see [here](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.3) for reference.
@NomicFoundation :heart: 
N/A
> `hardhat-vyper` plugin update: 3.0.2 --> 3.0.3

- pkg/liquidity-mining/contracts/test/MockChildChainGauge.sol
- pkg/liquidity-mining/test/L2BalancerPseudoMinter.test.ts
Tests for BAL pseudo minter in #2313 (builds on top). We can either review / merge separately, or merge this into the implementation and review all at once (up to the reviewer).
Tests are pseudo-minter specific. There are a few tests missing at the base layer, but that is tech debt and out of scope for the pseudo minter (I'll add them later).
> `L2BalancerPseudoMinter` tests

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerDelays.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerRoot.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
Closes https://github.com/balancer/balancer-v2-monorepo/issues/2242
> Support scheduling for revoke actions

- pvt/benchmarks/deployment.ts
Reorganize the deployment benchmark (replace LBP factory with the pool for consistency), and add deployment size of the Batch Relayer, as it's growing with each new protocol wrapper.
> Add batch relayer deployment benchmark

- README.md
Small doc update; selecting the correct Node version unequivocally is handy.
N/A
> Improve readme: suggested Node version

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
Title is self-descriptive. Refactor only.
N/A
> `ChildChainGauge` refactor: voting escrow --> voting escrow delegation proxy

- pkg/liquidity-mining/test/ChildChainGauge.test.ts
- pvt/helpers/src/models/pools/weighted/WeightedPool.ts
- pvt/helpers/src/models/tokens/TokenList.ts
WIP on top of #2325; to be merged into the branch before reviewing everything.
> `ChildChainGauge` tests

- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pkg/vault/test/authorizer/TimelockAuthorizer.test.ts
> Do not allow repeated executors

- pkg/interfaces/CHANGELOG.md
- pkg/interfaces/package.json
The new deployments package needed one of these, so I was forced to pub.
> Publish interfaces v0.4.0

- pkg/liquidity-mining/contracts/gauges/ChildChainGauge.vy
- pkg/liquidity-mining/test/ChildChainGauge.test.ts
- pkg/liquidity-mining/test/ChildChainGaugeFactory.test.ts
Minor improvement to simplify `ChildChainGauge`'s constructor.
N/A
> Refactor: Improve `ChildChainGauge` constructor

- pkg/deployments/tasks/20230315-silo-linear-pool/input.ts
- pkg/deployments/tasks/20230315-silo-linear-pool/test/test.fork.ts
Missed a couple links, etc. in the fork test, since it couldn't be run on this side.
> Adjust SiloLinearPool fork test

- pkg/liquidity-mining/contracts/gauges/ChildChainGaugeFactory.sol
> Remove unnecessary LM import

- .github/workflows/ci.yml
Feeling petty today; little nit ran across when investigating other parts of the configuration.
> Typo in ci config

- pkg/deployments/action-ids/goerli/action-ids.json
This adds all of the missing action ids for Pools that originate in factories.
> Populate goerli action ids

- pkg/interfaces/contracts/liquidity-mining/IL2LayerZeroDelegation.sol
- pkg/liquidity-mining/contracts/L2LayerZeroBridgeForwarder.sol
- pkg/liquidity-mining/contracts/test/MockL2LayerZeroDelegation.sol
- pkg/liquidity-mining/test/L2LayerZeroBridgeForwarder.test.ts
Add a hook for veBAL supply update to the L2LayerZeroDelegation (interface and implementation). Will be incorporated into the deployment PR #2410 .
> L2 Bridge Forwarder: add veBAL supply update hook

- pkg/deployments/tasks/20230411-managed-pool-v2/index.ts
- pkg/deployments/tasks/20230411-managed-pool-v2/input.ts
Add deployment of the mock managed pool to the task.
> Add mock managed pool deployment

- pkg/deployments/README.md
I didn't scroll over far enough to notice this...
> Ascii art fix

- pvt/helpers/src/models/pools/weighted/types.ts
- pvt/helpers/src/models/types/TypesConverter.ts
Noticed while updating the PR that removes the WeightedPoolDeployer.
> Remove dead controller code

- pkg/interfaces/contracts/liquidity-mining/IVotingEscrowRemapper.sol
- pkg/liquidity-mining/contracts/VotingEscrowRemapper.sol
Closes #2452 (see issue for details).
> Use `uint16` for chainId in `VotingEscrowRemapper`.

- pkg/interfaces/CHANGELOG.md
Missing from last-minute update in #2463.
N/A
> Update interfaces changelog

- pkg/interfaces/contracts/vault/ITimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizerManagement.sol
- pkg/vault/test/authorizer/TimelockAuthorizerDelays.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerExecute.test.ts
- pkg/vault/test/authorizer/TimelockAuthorizerPermissions.test.ts
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
Supercedes https://github.com/balancer/balancer-v2-monorepo/pull/2413, adding tests and interface improvements.
> Timelock authorizer scheduled tasks auditability

- pkg/vault/contracts/authorizer/TimelockAuthorizerManagement.sol
- pkg/vault/test/authorizer/TimelockAuthorizerActors.test.ts
This fixes issue L2 raised by Certora in [their audit](https://github.com/balancer/balancer-v2-monorepo/pull/2488). The code contains explanations as to why we're doing this. We don't _need_ to implement this change, but it is a nice UX improvement.
> Forbid adding cancelers for non-existent or non-pending executions

- pkg/governance-scripts/contracts/TimelockAuthorizerMigrator.sol
- pkg/governance-scripts/test/TimelockAuthorizerMigrator.test.ts
We'll want to setup a lower transfer delay in testnets (e.g. 5 days), it doesn't make sense to have such a large delay there.
> Make the root transfer delay configurable

- pkg/interfaces/contracts/vault/ITimelockAuthorizer.sol
- pkg/vault/contracts/authorizer/TimelockAuthorizer.sol
- pvt/helpers/src/models/authorizer/TimelockAuthorizer.ts
These were a remnant of past times, only used internally.
> Remove Timelock permission ids

- pkg/governance-scripts/contracts/20230518-gauge-adder-migration-v3-to-v4/GaugeAdderMigrationCoordinator.sol
- pkg/governance-scripts/contracts/20230518-gauge-adder-migration-v3-to-v4/readme.md
- pkg/governance-scripts/contracts/xxxx-gauge-adder-migration-v3-to-v4/readme.md
We will deploy the gauge factory for ZK EVM soon, so it's safe to assume we will have this gauge type.
Also refactors the directory and README.
N/A
> Add Polygon ZK EVM to gauge adder migrator (V3 --> V4)

- pkg/deployments/README.md
As an intermediate step before removing the workspace completely, this PR adds a deprecation notice while the announcements roll out.
See #2504.
N/A
> Deployments deprecation notice.

- pkg/standalone-utils/test/CompoundV2Wrapping.test.ts
Minor fix for TS test; some types were off, but the test worked anyways.
N/A
> Fix types in TS test for `CompoundWrapping`.

- pkg/interfaces/contracts/liquidity-mining/IAvalancheBridgeLimitsProvider.sol
- pkg/liquidity-mining/contracts/gauges/avalanche/AvalancheRootGauge.sol
- pkg/liquidity-mining/contracts/gauges/avalanche/AvalancheRootGaugeFactory.sol
- pkg/liquidity-mining/contracts/test/MockAvalancheRootGauge.sol
- pkg/liquidity-mining/contracts/test/MockAvalancheRootGaugeFactory.sol
- pkg/liquidity-mining/test/AvalancheRootGauge.test.ts
Introduce the Avalanche Root Gauge; stakeless gauge for the Avalanche network.
Unlike most root gauge implementations, this one had elements that would have been too difficult to test in a fork (i.e., requiring exact mintAmount values), so this has mocks and unit tests for just those features.
Closes #2481
> Avalanche Root Gauge

- pkg/standalone-utils/contracts/relayer/VaultActions.sol
- pkg/standalone-utils/test/VaultActions.test.ts
#2515 with two extra commits that weren't merged because of a service degradation in GH PRs.
N/A
> Relayer: Chain internal balance operations (outstanding comments)

- pkg/pool-utils/CHANGELOG.md
- pkg/pool-utils/package.json
Updating docs to reflect new deployment: https://www.npmjs.com/package/@balancer-labs/v2-pool-utils/v/4.1.1.
N/A
> `v2-pool-utils` NPM release: v4.1.0/1.

- pkg/standalone-utils/contracts/BatchRelayerLibrary.sol
- pkg/standalone-utils/contracts/relayer/GaugeActions.sol
- pkg/standalone-utils/contracts/test/MockBatchRelayerLibrary.sol
- pkg/standalone-utils/test/AaveWrapping.test.ts
- pkg/standalone-utils/test/CompoundV2Wrapping.test.ts
- pkg/standalone-utils/test/EulerWrapping.test.ts
- pkg/standalone-utils/test/GaugeActions.test.ts
- pkg/standalone-utils/test/GearboxWrapping.test.ts
- pkg/standalone-utils/test/LidoWrapping.test.ts
- pkg/standalone-utils/test/ReaperWrapping.test.ts
- pkg/standalone-utils/test/SiloWrapping.test.ts
- pkg/standalone-utils/test/TetuWrapping.test.ts
- pkg/standalone-utils/test/UnbuttonWrapping.test.ts
- pkg/standalone-utils/test/VaultActionsRelayer.setup.ts
- pkg/standalone-utils/test/YearnWrapping.test.ts
Stab at #2399 (see details in ticket).
Tests pending; this is an initial draft for early feedback.
Closes #2399.
> Add checkpoint gauges capability to `GaugeActions` (relayer)

- pkg/standalone-utils/contracts/BatchRelayerLibrary.sol
- pkg/standalone-utils/contracts/test/MockBatchRelayerLibrary.sol
Minor argument name refactor for consistency with `GaugeActions`.
N/A
> Refactor: Relayer argument

- pkg/pool-stable/contracts/ComposableStablePool.sol
Doc clarification for `getRate` in `ComposableStablePool`.
Closes #2532
> Doc fix for `getRate`.

- pkg/interfaces/contracts/liquidity-mining/IL1StandardBridge.sol
- pkg/liquidity-mining/contracts/gauges/base/BaseRootGauge.sol
- pkg/liquidity-mining/contracts/gauges/base/BaseRootGaugeFactory.sol
- pkg/liquidity-mining/contracts/gauges/optimism/OptimismRootGauge.sol
Introduces the root gauge for Base. I believe we determined that it's not necessary to worry about L2 gas, which makes this gauge extremely simple. See code comments for details.
We now have multiple roots using the same interface L1StandardBridge. Should we pull that up to interfaces?
Closes #2539
> Root Gauge for the Base network

- pkg/liquidity-mining/package.json
- yarn.lock
Potential [fix for CI issue](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.5).
N/A
> Hardhat-vyper upgrade: 3.0.3 --> 3.0.5

- funding.json
> adding verification

- pkg/liquidity-mining/test/DistributionScheduler.test.ts
- pkg/pool-utils/contracts/external-fees/ProtocolFeeCache.sol
- pkg/pool-weighted/test/WeightedPool.test.ts
- pkg/pool-weighted/test/foundry/CircuitBreakerLib.t.sol
- pkg/standalone-utils/contracts/test/MockEulerToken.sol
remove redundant words in comment
> chore: remove redundant words in comment

- pkg/pool-linear/contracts/LinearPoolRebalancer.sol
> chore: fix minor error

- audits/test-report.md
i was reading audit and small misspelling
> chore: fix misspell in test-report.md
